### ISSUE TITLE
ls_osa_mutex_create 函数的代码逻辑错误？

### ISSUE THREAD

**Issue by ifoxhz** [alibaba/AliOS-Things#1001]
文件：ls_osa.c
函数：ls_osa_mutex_create（）

  *mutex = (aos_mutex_t *)aos_malloc(sizeof(aos_mutex_t));
    if (*mutex) {
        return -1;
    }
应该是判读内存分配是否成功，估计是逻辑弄错了？

**Comment by xiaowenxia** [comment]
我反馈一下，非常感谢  :+1:
