### ISSUE TITLE
linux 系统 vscode安装alios-things库后最下面没有显示编译上传等图标

### ISSUE THREAD

**Issue by Hardzeng** [alibaba/AliOS-Things#1009]
![image](https://user-images.githubusercontent.com/50788896/60887116-274a2a00-a286-11e9-9290-14246e2083c4.png)

**Comment by xiaowenxia** [comment]
打开了AliOS Things源码才会看到哦。

**Comment by Hardzeng** [comment]
谢谢，了解了
