### ISSUE TITLE
请问是否可以直接用手机配网，不通过智能生活平台？

### ISSUE THREAD

**Issue by jifanchn** [alibaba/AliOS-Things#1015]
这几天摸了一下ALiOS-Things、MK3060，我理解到配网一定要在这个平台上注册（？），然后通过默认APP或者SDK配网。

我希望使用MK3060直接通过MQTT连接阿里云物联网平台，把一些工业产品的数据上传到云端，通过大数据组件进行处理，并没有使用智能生活平台的需求。

希望在工厂内烧写IOT三元组，在现场通过更简单地通过APP某个接口配网。

请问一下应该怎么做？

**Comment by snowwolfjay** [comment]
别用AliOS不就成了，自己组个网，不然很多功能不久赘余的了。

**Comment by jifanchn** [comment]
比研究第三方的SDK强吧，另外我确实想用阿里的物联网平台啊，MQTT，OTA什么的都用，这个可以说是各种成本都比较低的办法了。
