### ISSUE TITLE
ESP32的OTA有支持的计划吗？

### ISSUE THREAD

**Issue by hexiangdong2017** [alibaba/AliOS-Things#1016]
OTA例程中标注支持以下单片机：
- mk3060
- mk3080
- developerkit
- esp8266
ESP8266既然都支持OTA，ESP32官方SDK中也具有OTA的API，请问AliOS Things有支持ESP32的OTA的计划吗？

**Comment by xiaowenxia** [comment]
esp32我们也验证是没有问题的，你可以试一试。

**Comment by hexiangdong2017** [comment]
好的，谢谢@xiaowenxia

**Comment by zxf1025** [comment]
我 用VSCODE就没编译成功过 为什么呢
