### ISSUE TITLE
Help Wanted:AliOS Things中串口中断应该调用哪个API

### ISSUE THREAD

**Issue by hexiangdong2017** [alibaba/AliOS-Things#1018]
HAL的uart中只有主动接收的函数hal_uart_recv和hal_uart_recv_II，没有串口中断的函数，请问串口中断应该使用什么API？@xiaowenxia

**Comment by xiaowenxia** [comment]
目前没有这样的api，可以自己封装相关MCU的中断函数来实现。

**Comment by hexiangdong2017** [comment]
I2C、SPI是否也没有相应的中断？
