### ISSUE TITLE
新SDK编译hello world@3080可以但是@3060失败

### ISSUE THREAD

**Issue by jiajiabusy** [alibaba/AliOS-Things#1021]
![image](https://user-images.githubusercontent.com/45744636/62259336-898aea80-b440-11e9-9464-b433021c0827.png)

这是什么原因呢？？？

**Comment by xiaowenxia** [comment]
```
aos make clean
```

**Comment by jiajiabusy** [comment]
已经clean好多次了，用3080可以编译很多app但是用3060一直失败



------------------ 原始邮件 ------------------
发件人: "夏晓文"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 上午9:53
收件人: "alibaba/AliOS-Things"<AliOS-Things@noreply.github.com>; 
抄送: "Hero|||"<657028267@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/AliOS-Things] 新SDK编译hello world@3080可以但是@3060失败 (#1021)



aos make clean
