### ISSUE TITLE
求助庆科EWM3080B应该使用哪个版本进行开发？

### ISSUE THREAD

**Issue by xiaoyaodian** [alibaba/AliOS-Things#1026]
我现在使用的是master版本编译3080成功了，但是下载进板子不能显示helloworld,要怎么做？是boot不对还是下载的bin文件不对？求助

**Comment by xiaoyaodian** [comment]
![image](https://user-images.githubusercontent.com/53965785/62819498-a03fe880-bb88-11e9-8119-9e40ac5bf992.png)

**Comment by xiaoyaodian** [comment]
![image](https://user-images.githubusercontent.com/53965785/62819503-af269b00-bb88-11e9-8cb1-c569badbef2d.png)
烧录成功但是串口没有数据

**Comment by xiaoyaodian** [comment]
![image](https://user-images.githubusercontent.com/53965785/62819522-fe6ccb80-bb88-11e9-9fba-d11c352fced1.png)

**Comment by xiaoyaodian** [comment]
第一次下载是不是需要把boot一起修改下载呢？要怎么做？

**Comment by xiaowenxia** [comment]
看起来还是处于bootloader中，重启一下。

**Comment by xiaoyaodian** [comment]
没用啊重启多少遍都是这样

**Comment by xiaowenxia** [comment]
你不要烧录`*.ota.bin`文件，这个是给ota升级用的，看看同目录下面的readme里面的说明。
