### ISSUE TITLE
请问 庆科3080 不能进入GPIO中断

### ISSUE THREAD

**Issue by xiaoyaodian** [alibaba/AliOS-Things#1027]
使用EWM3080 2.1.0alithing 分支 GPIO 输入输出都正常但是进不来GPIO口中断服务函数，要怎么做，是hal文件没有适配吗？platform\mcu\下也找不到MK3080的适配文件
![image](https://user-images.githubusercontent.com/53965785/62992971-26f60d80-be88-11e9-9d08-fad813e2db0c.png)

**Comment by xiaowenxia** [comment]
mk3080用的mcu是[rtl8710bn](https://github.com/alibaba/AliOS-Things/tree/rel_2.1.0/platform/mcu/rtl8710bn)，gpio的hal代码是适配了的。

**Comment by xiaoyaodian** [comment]
@xiaowenxia 可是，GPIO进不了中断服务函数啊，   hal_gpio_enable_irq(&input, IRQ_TRIGGER_BOTH_EDGES, gpio_isr_handler, (void *) MICO_GPIO_7);

**Comment by xiaoyaodian** [comment]
编译的时候会自动适配rtl8710bn下的hal函数吗？

**Comment by xiaowenxia** [comment]
![image](https://user-images.githubusercontent.com/16155447/62998482-439d4000-be9e-11e9-9014-c7211dc5df43.png)
看源码，`IRQ_TRIGGER_BOTH_EDGES`并没有作用，你换成`IRQ_TRIGGER_FALLING_EDGE`或者`IRQ_TRIGGER_RISING_EDGE`试一次。

同样，`hal_gpio_init()`好像也对`IRQ_MODE`的gpio模式没有作用，换成其他的试一试。

**Comment by xiaoyaodian** [comment]
![image](https://user-images.githubusercontent.com/53965785/63000889-d214c000-bea4-11e9-93b2-f318fdf2892b.png)

**Comment by xiaoyaodian** [comment]
@xiaowenxia 大佬，这样写还是不行啊

**Comment by xiaowenxia** [comment]
你参考下mk3080（`board/mk3080/board.c`）的配网按键的[相关代码](https://github.com/alibaba/AliOS-Things/blob/rel_2.1.0/board/mk3080/board.c#L60)，也是使用gpio中断功能。
