### ISSUE TITLE
About Python3

### ISSUE THREAD

**Issue by AndyHEQI** [alibaba/AliOS-Things#1037]
Ali things支持Python3了吗

**Comment by xiaowenxia** [comment]
目前暂时还不支持哈。

**Comment by RandyHEQI** [comment]
请我有支持Python3的计划吗？大概在哪个季度？谢谢

**Comment by nichenghyx** [comment]
python2 安装pip 时报错，DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support 。在2020年的时候就不支持了，这个什么时候支持python3

**Comment by xiaowenxia** [comment]
目前已经正在适配python3了 :handshake:
