### ISSUE TITLE
AliOS-Things代码烧录出错

### ISSUE THREAD

**Issue by ThisIsMarxMA** [alibaba/AliOS-Things#1041]
**Describe the bug**

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**> Executing task: aos upload helloworld@developerkit <

aos-cube version: 0.3.5
[INFO]: Currently in aos_sdk_path: 'd:\AliOSThings\AliOS-Things'
[AliOS-Things] ERROR: Import scons_upload.py: failed No module named scons_upload
---
终端进程已终止，退出代码: 4294967295

**Comment by KtQiu** [comment]
You can try
`pip install --upgrade setuptools
pip install --upgrade wheel`

**Comment by xiaowenxia** [comment]
什么AliOS Things 版本呢？`aos upload`命令不支持`2.0`版本以下，包括`1.3.x`版本。

**Comment by JunJianX** [comment]
@xiaowenxia 那应该怎么烧录呢？
