### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by craftor** [alibaba/AliOS-Things#1048]
`kernel/debug/debug_panic.c:159:13: error: 'backtrace' defined but not used [-Werror=unused-function]
 static void backtrace(char *PC, int *SP, char *LR,
             ^
cc1.exe: all warnings being treated as errors`

请问这个怎么解决？

**Comment by xiaowenxia** [comment]
什么开发板呢？试试注释掉`kernel/debug/debug_panic.c`中的backtrace函数，或者makefile中去掉`-Werror=unused-function`这个gcc选项。

**Comment by craftor** [comment]
解决了，谢谢哈
