### ISSUE TITLE
3.0.0工程编译出错

### ISSUE THREAD

**Issue by craftor** [alibaba/AliOS-Things#1052]
win10,vs code，阿里云开发板，直接clone下来3.0.0的工程，编译出错：

Generate Raw OTA image: out/blink@developerkit/binary/blink@developerkit_ota.bin ...
Generate Compressed OTA image: out/blink@developerkit/binary/blink@developerkit_ota.bin.xz ...
101072
6e37de03568a25c8d75cb4718e1347d2
此时不应有 -f。
make.exe[1]: *** [build/build_rules/aos_target_build.mk:397: blink@developerkit] Error 255
make.exe: *** [build/Makefile:393: main_app] Error 2
[AliOS-Things] ERROR: "e:/08AIoT/AliOS-Things/build\cmd/win32/make.exe" returned error code 2.
[AliOS-Things] ERROR: Command "e:/08AIoT/AliOS-Things/build\cmd/win32/make.exe HOST_OS=Win32 TOOLS_ROOT=e:/08AIoT/AliOS-Things/build -e -f build/Makefile" in "e:\08AIoT\AliOS-Things"
---
The terminal process terminated with exit code: 2

**Comment by xiaowenxia** [comment]
这个问题已经解决了，重新拉取仓库试一试：
```sh
git pull
```
