### ISSUE TITLE
[直播] AliOS Things 3.0 入门与实践，快速接入阿里云物联网平台的正确姿势！

### ISSUE THREAD

**Issue by xiaowenxia** [alibaba/AliOS-Things#1054]
## 已经结束！

点击观看[直播回放](https://developer.aliyun.com/article/720812?spm=a2c6h.13262185.0.0.697f4a00UV3zN9)。

**AliOS Things 3.0 入门与实践，快速接入阿里云物联网平台的正确姿势！**

本次直播主讲AliOS Things 3.0应用开发从零开始手把手教学，让设备数据上云不再麻烦，主讲内容有：
1） AliOS Things 3.0 介绍、阿里云物联网平台介绍。
2） AliOS Things 环境搭建。
3） AliOS Things 应用开发快速上手。
4） AliOS Things 实践：传感器数据上云简单应用。

欢迎在评论区提前向分享人提问！

### AliOS Things 技术图谱

![](https://img.alicdn.com/tfs/TB1dkGSjuL2gK0jSZPhXXahvXXa-4880-2390.png)

### 获取AliOS Things 源码
* [AliOS Things Github开源地址](https://www.github.com/alibaba/AliOS-Things)
* [AliOS Things 码云高速下载地址](https://gitee.com/mirrors/AliOS-Things)
* [AliOS Things组件在线裁剪工具](https://aliosthings.iot.aliyun.com/)

### 文档
* [AliOS Things wiki文档地址](https://github.com/alibaba/AliOS-Things/wiki)
* [开发者社区文档中心](https://dev.iot.aliyun.com/doc) | 基础产品 AliOS Things 专栏

### AliOS Things 常用文档

* [AliOS Things 构建系统说明](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-build-system.zh)
* [AliOS Things 2.1 配置系统说明](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Build-Configuration.zh)
* [AliOS Studio 说明文档](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Studio)
* [AliOS Things 维测典型案例分析 —— 内存泄漏](https://yq.aliyun.com/articles/718916?spm=5176.10695662.1996646101.searchclickresult.7e9f140frmDxc0&aly_as=z42qIOKz)
* [AliOS Things 3.0 应用开发指南](https://developer.aliyun.com/article/720516?spm=a2c6h.12873581.0.0.73ab319agYlbIo&groupCode=iot)
* [使用AliOS Things 3.0快速构建用户应用 BlinkAPP](https://developer.aliyun.com/article/720197?spm=a2c6h.12873581.0.0.73ab319agYlbIo&groupCode=iot)
* [Linkkit SDK 用户手册](code.aliyun.com/edward.yangx/public-docs/wikis/user-guide/Linkkit_User_Manual)

### aos-cube命令速查表

![](https://img.alicdn.com/tfs/TB1U11UjAL0gK0jSZFAXXcA9pXa-2258-1138.png)

### AliOS Things 启动流程

![](https://img.alicdn.com/tfs/TB1SU5Tjrr1gK0jSZFDXXb9yVXa-1712-1438.png)

### AliOS Things 实践源码

请下载本次直播的[实践源码](https://aos-app-dev.oss-cn-shanghai.aliyuncs.com/developerkit_sensor.zip)。

要使用该源码，需要更改AOS_SDK_PATH路径：

* 编辑 `.aos`:
```
AOS_SDK_PATH=/Users/xxw/workspace/github/AliOS-Things
DEPENDENCIES=
MD5SUM_HEADER=a1a4b53ab917fb4a6cb08289b6007fe0
```
更改 `/Users/xxw/workspace/github/AliOS-Things` 为你的`AliOS-Things`源码路径。

* 编辑 `Config.in`:

```
......
config AOS_SDK_PATH
    string
    default "/Users/xxw/workspace/github/AliOS-Things"
......
```

更改 `/Users/xxw/workspace/github/AliOS-Things` 为你的`AliOS-Things`源码路径。

> windows用户的路径示例为：`C:/workspace/github/AliOS-Things`，注意路径中用的是斜杠`/`，不是反斜杠`\`。

同时也需要更改设备的三元组信息和wifi信息：

```c
#define PRODUCT_KEY "<product-key>"
#define PRODUCT_SECRET "<product-secret>"
#define DEVICE_NAME "<device-name>"
#define DEVICE_SECRET "<device-secret>"

/* modify to your wifi information */
#define WIFI_SSID "aiot"
#define WIFI_PASSWD "12345678"
```

##### 如何快速git clone github上的源码

1. 首先git clone gitee的国内git仓库。
2. 再添加一个新的remote仓库为github的仓库。
3. 然后git fetch --all就可以把github的仓库快速clone下来。
4. 新建github的本地分支，也可以删除掉gitee远程仓库。

具体步骤如下：

```
$ git clone git@gitee.com:mirrors/AliOS-Things.git
$ cd AliOS-Things
$ git remote add github git@github.com:alibaba/AliOS-Things.git
$ git fetch –all
$ git checkout –b github_rel_3.0.0 –track github/rel_3.0.0
```

操作图：

![](https://img.alicdn.com/tfs/TB1YCyVjrr1gK0jSZR0XXbP8XXa-967-534.gif)

欢迎进入以下任意一个钉钉群观看直播：

<p>
<img src="https://img.alicdn.com/tfs/TB1tftfjeL2gK0jSZPhXXahvXXa-585-818.jpg" width = "300" alt="图片名称" align=center />
<img src="https://img.alicdn.com/tfs/TB1Sytgjhn1gK0jSZKPXXXvUXXa-585-818.jpg" width = "300" alt="图片名称" align=center />
</p>

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年
http://weibo.ws/zZNbxG

阿里云企业级服务器1折限时特惠
http://weibo.ws/SIyDRE

阿里云建站 速成美站 - 千套模板，价格低至500元
http://weibo.ws/yVQAYW
