### ISSUE TITLE
按照Quick Start.zh文档，搭建环境，执行aos make helloworld@linuxhost -c config && aos make报错

### ISSUE THREAD

**Issue by tanglv** [alibaba/AliOS-Things#1062]
**Describe the bug**
按照Quick Start.zh文档，搭建环境，执行aos make helloworld@linuxhost -c config && aos make报错，log如下
执行命令
aos make helloworld@linuxhost -c config && aos make
![image](https://user-images.githubusercontent.com/9816185/67388421-2afe8400-f5cb-11e9-8752-22859afeea21.png)

换命令执行
aos make helloworld@linuxhost -c profile-linkkitapp_asr5501_defconfig  && aos make

![image](https://user-images.githubusercontent.com/9816185/67388618-95afbf80-f5cb-11e9-916b-a59ca8a4be31.png)

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):ubuntu16.04
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tanglv** [comment]
w10环境编译ok，但是linux环境不行

**Comment by xiaowenxia** [comment]
`uname -a` 看看系统信息。

**Comment by tanglv** [comment]
![image](https://user-images.githubusercontent.com/9816185/67392861-e1fefd80-f5d3-11e9-8f5b-3dcec8b83395.png)

**Comment by tanglv** [comment]
> `uname -a` 看看系统信息。

![image](https://user-images.githubusercontent.com/9816185/67392926-f8a55480-f5d3-11e9-87da-d6ffff120039.png)

**Comment by xiaowenxia** [comment]
你是windows上挂载的AliOS Things文件夹到ubuntu虚拟机么？

**Comment by tanglv** [comment]
> 你是windows上挂载的AliOS Things文件夹到ubuntu虚拟机么？
没有挂在文件系统，是直接在/home目录下面的家目录，环境都按照文档安装好了，编译报错
![image](https://user-images.githubusercontent.com/9816185/67460404-7e291300-f66d-11e9-95ee-d57efec60d84.png)

**Comment by tanglv** [comment]
> 你是windows上挂载的AliOS Things文件夹到ubuntu虚拟机么？

哈喽，还有人吗？帮忙解决一下，ubuntu开发环境也是主流啊

**Comment by xiaowenxia** [comment]
@tanglv 你的源码下载的对吗？是不是没有下载完全？ubuntu系统是比较常用的一个开发环境，一直是有测试验证的。
