### ISSUE TITLE
aliosthings调度疑问

### ISSUE THREAD

**Issue by 5huabin** [alibaba/AliOS-Things#1070]
每个任务都可以通过krhino_sched_policy_set()来设置其调度策略是RR还是FIFO，那么同一个优先级列表既有FIFO任务，又有RR任务时应该怎么执行。比如：有4个任务处于就绪态，2个是FIFO的，2个是RR的，则是怎么执行的。

**Comment by andy2012zwj** [comment]
整体任务调度还是按照FIFO来执行的，只是执行到RR任务的时候，RR任务最多执行设定的tick就会被切换走
