### ISSUE TITLE
web serial error: Error: Could not locate the bindings file. 

### ISSUE THREAD

**Issue by asdfw-sdf** [alibaba/AliOS-Things#1071]
An error occurred after the update  : web serial error: Error: Could not locate the bindings file.

**Comment by asdfw-sdf** [comment]
啊，可以用中文的吗？早知道不搜了，

**Comment by xiaowenxia** [comment]
这个问题这两天会修复掉哈。

**Comment by asdfw-sdf** [comment]
第一用不知道怎么回复，谢谢各位~

**Comment by iJiangs** [comment]
这个问题解决了吗 我今天也遇到了这个问题
我的nodejs版本是v12.19.0

**Comment by wxdhd121** [comment]
我也遇到了，不知道什么情况
![image](https://user-images.githubusercontent.com/46323092/99391519-41cdf200-2915-11eb-818b-212614e4689c.png)

**Comment by QiquWong** [comment]
遇到同样的问题，试了各种各样解决方案仍没解决，现在还有其他解决方案吗？
