### ISSUE TITLE
庆科MK3080模组 使用JLink下载问题？

### ISSUE THREAD

**Issue by xp187oo** [alibaba/AliOS-Things#1072]
请问庆科MK3080模组使用OpenOcd下载程序该如何操作？我现在参照这个网址https://github.com/alibaba/AliOS-Things/wiki/MK3060-Hardware-Setup做了测试，不能解决下载的问题，希望庆科或者阿里的工程师细化，修复一下这个问题

**Comment by andy2012zwj** [comment]
aos cube还有AliOS Things分别用的是哪个版本
