### ISSUE TITLE
win10 aos 异常,upload程序失败

### ISSUE THREAD

**Issue by siberianfox** [alibaba/AliOS-Things#1073]
**Describe the bug**
win10 上面的aos没法下载程序，aos upload无效，提示不存在该命令，什么原因

>Executing task: aos upload littlevgl_starterkit@starterkit <
>Usage: aos [OPTIONS] COMMAND [ARGS]...
>Try "aos -h" for help.
>
>Error: No such command "upload"
>The terminal process terminated with exit code: 1
>
>Terminal will be reused by tasks, press any key to close it.

**Comment by siberianfox** [comment]
换了aos 0.3.7 可以，自动安装的0.3.8会有这个问题

**Comment by andy2012zwj** [comment]
win10上使用0.3.7吧，安装时候指定版本号aos-cube==0.3.7，0.3.8的问题还要再确认一下
