### ISSUE TITLE
jsengine 错误

### ISSUE THREAD

**Issue by glen8** [alibaba/AliOS-Things#1078]
**Describe the bug**

**environment**
1. branch(version): AliOS-Things 3.0
2. Desktop OS(windows linux or macOS):window 10
3. example: 
console.log("=================================");
console.log("        demo-hello-world         ");
console.log("=================================");
**Expected behavior**

**Screenshots**

![error](https://user-images.githubusercontent.com/4090812/69507145-7c07ec00-0f6c-11ea-93ad-29bb0163dba7.png)

**Additional context**

**Comment by xiaowenxia** [comment]
@glen8 你好，这个错误已经修复了:smile:
