### ISSUE TITLE
OTA升级中的差分算法是什么

### ISSUE THREAD

**Issue by liborui** [alibaba/AliOS-Things#1079]
**Is your feature request related to a problem? Please describe.**
OTA升级中的差分算法是什么？不知道是否能开源出来。
在科研论文中对差分算法有很多研究，我想将其应用到AliOS Things中进一步减小OTA体积

**Describe the solution you'd like**

**Additional context**

**Comment by andy2012zwj** [comment]
目前我们计划OTA相关算法都不开源
