### ISSUE TITLE
RHINO_CONFIG_INTRPT_STACK_OVF_CHECK打开之后，编译报错

### ISSUE THREAD

**Issue by zt19901990** [alibaba/AliOS-Things#1080]
**Describe the bug**
helloworld@developerkit项目，
打开RHINO_CONFIG_INTRPT_STACK_OVF_CHECK功能之后，编译报错
undefined reference to `g_intrpt_stack_bottom'

**Comment by andy2012zwj** [comment]
目前RHINO_CONFIG_INTRPT_STACK_OVF_CHECK功能不支持，需要专门适配才可以。
