### ISSUE TITLE
关于设备接入天猫精灵有Aligenie,飞燕平台，阿里IOT生活物联平台等，有什么区别？

### ISSUE THREAD

**Issue by panguoxian** [alibaba/AliOS-Things#1082]
我只是想设备接入天猫精灵，然后，这几个平台有什么不同？

一脸懵圈。。

想使用AliOS-Things,要如何入门？github教程看不太懂。。请指教如何入门。
突然感觉AliOS-things好复杂。。

比如新建一个项目，应该如何使用AliOS里我所选硬件平台操作？
谢谢！！

**Comment by andy2012zwj** [comment]
飞燕平台和生活物联网平台是同一个，是阿里云IoT提供的（https://iot.aliyun.com/products/livinglink）；Aligenie是天猫精灵那边的云平台。
连接飞燕平台的话，需要用到物联网平台设备端SDK（linkkit），可参考下面的文档
https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Linkkit-Application.zh
