### ISSUE TITLE
使用AliOS 3.0 vsCode开发,如何自动补全SKD里的函数等？

### ISSUE THREAD

**Issue by panguoxian** [alibaba/AliOS-Things#1083]
使用AliOS-Things，在vsCode新建项目，写代码时不能自动补全，SDK里的函数等。

因为新建项目并不在SDK里，文件夹下也没有SDK里的相关驱动等文件。

或是有什么插件或方法可以自动补全？

**Comment by xiaowenxia** [comment]
参考vscode文档：https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference  把 SDK路径添加到`c_cpp_properties.json`文件`includePath`项中试试哈。

**Comment by panguoxian** [comment]
> 参考vscode文档：https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference 把 SDK路径添加到`c_cpp_properties.json`文件`includePath`项中试试哈。

已解决非常感谢
