### ISSUE TITLE
AliOS-Things 如何通过AliOS，操作支持芯片的硬件，应该查阅什么文档？

### ISSUE THREAD

**Issue by panguoxian** [alibaba/AliOS-Things#1084]
比如我新建一个工程，硬件选的是esp8266，假如我要操作GPIO，应该如何操作？

查阅什么文档？

使用helloworld printf 也打印不出任何数据。
谢谢

**Comment by andy2012zwj** [comment]
开发板需要到硬件厂商的官方找一下文档，printf打印没有输出，可以看下user_init接口里的串口配置是否正确

**Comment by panguoxian** [comment]
> 开发板需要到硬件厂商的官方找一下文档，printf打印没有输出，可以看下user_init接口里的串口配置是否正确

感谢！
