### ISSUE TITLE
Alios-things调试helloworld，可以运行到main,当无法跳转到application_start.

### ISSUE THREAD

**Issue by unitsoftrover** [alibaba/AliOS-Things#1088]
跟踪可以运行到krhino_start->cpu_first_task_start，可以转到汇编代码。
 MOVS    R0, #0
    MSR     PSP, R0

    ;make PendSV exception pending
    LDR     R0, =SCB_ICSR
    LDR     R1, =ICSR_PENDSVSET
    STR     R1, [R0]

    ;goto PendSV_Handler
    CPSIE   I
    B       .
在运行到 CPSIE   I，并没有引起中断，继续运行到B 。，无法跟踪到PendSV_Handler.
可能这个地方有问题无法切换到aos的主任务。
我在keil中调试，可以成功中断到PendSV_Handler，切换到aos的主任务。
不知道是什么原因导致的，用的芯片是STM32F103C8T6，ROM64K,RAM20K,程序编译后ROM需要40k,RAM需要17K，内存应该够了。

**Comment by iotmoe** [comment]
我也遇到了此类问题，helloworld一直编译不过去。

**Comment by walker2048** [comment]
103内存太小了，不建议用，目前用这个板子的估计都放弃了
