### ISSUE TITLE
波特率问题

### ISSUE THREAD

**Issue by fly9118** [alibaba/AliOS-Things#1089]
**Is your feature request related to a problem? Please describe.**

调试helloworld 时，波特率时921600，但是硬件不支持，如何调成9600供硬件平台esp8266
**Describe the solution you'd like**

**Additional context**

**Comment by andy2012zwj** [comment]
8266平台上，可以通过这个接口（hal_uart_init、uart_init_new）来看

**Comment by panguoxian** [comment]
platform/mcu/esp8266/bsp/drive/uart.c

uart_init_new(uart_dev_t *uart)
{
 ...............
uart_config.baud_rate = BIT_RATE_115200;
................
}
