### ISSUE TITLE
有没有英文文档的计划？

### ISSUE THREAD

**Issue by JammyZhou** [alibaba/AliOS-Things#11]
目前的文档都是中文，为了让更多国外芯片厂商和开发人员参与进来，有没有计划发布英文版的文档？

**Comment by woksdl** [comment]
谢谢意见，我们会考虑

**Comment by lluwang** [comment]
If there were any developer/volunteer that can help not only on the quality of the code, but also the docs, that would be great. ^_^

**Comment by junjiec** [comment]
已经逐步增加英文文档，此issue暂时关闭
