### ISSUE TITLE
增加微秒级delay API

### ISSUE THREAD

**Issue by wanglingsong** [alibaba/AliOS-Things#110]
目前aos里只提供aos_msleep这样一个毫秒级的delay/sleep API。无法进行微秒级的时间控制，例如解析DHT11的数据编码。所以希望能提供一个微秒级的delay/sleep API，比如：aos_usleep

**Comment by wanglingsong** [comment]
请问有进展吗？

**Comment by librae8226** [comment]
目前看起来在板级根据实际硬件clock配置通过计算tick来阻塞方式实现比较可行，如果有更好办法请comment

**Comment by wanglingsong** [comment]
没有意见。

**Comment by librae8226** [comment]
软件方式的暂无计划。如果需要可以根据实际硬件平台使用硬件定时器
参考 ./include/hal/soc/timer.h 接口

**Comment by wanglingsong** [comment]
我比较好奇的是close了这个issue之后，你们怎么跟踪？还是你们已经决定不考虑引入这个feature？

**Comment by librae8226** [comment]
如果还有问题的话可以 reopen 的哈。
如上所述，目前除了从厂商对接的hal api提供该feature以外，暂无加入os统一api的计划。
