### ISSUE TITLE
esp8266 linkkitAPP例程，一键配网成功后，清除再次配网，找不到设备

### ISSUE THREAD

**Issue by panguoxian** [alibaba/AliOS-Things#1100]
alios things 3.0版本

esp8266 模组使用linkkitAPP例程，短按，后使用天猫精灵找队友进行配网成功

长按：清除配网，并重启。
再次短按：再次配网，配网找不到设备。使用手机APP也相同情况。

进入配网打印如下：

[  36.320]<A>AOS awss config press 2

[  36.320]<A>AOS VALUE_KEY_CLICK

[  36.320]<A>AOS do_awss_active 1

[  36.320]<F>awss enable awss

[  36.320]<A>AOS IOTX_AWSS_ENABLE

找不到原因。有经验的朋友指点一二。

谢谢！！

**Comment by andy2012zwj** [comment]
你好，该问题可到以下链接提工单处理：https://selfservice.console.aliyun.com/ticket/category/iot/recommend/3576
