### ISSUE TITLE
esp8266 linkkitapp 天猫精灵，零配（配网）偶尔成功，经常找不到设备

### ISSUE THREAD

**Issue by panguoxian** [alibaba/AliOS-Things#1101]
环境：

alios things 3.0
aos make menuconfig 里已经打开零配

问题：

esp8266 linkkitapp零配偶而成功，经常找不到设备。

相同代码，使用天猫精灵进行零配（配网），偶尔成功配网。

当清除配置后，天猫精灵就再也找不到设备。

清除配置 使用 do_awss_reset();

进入零配网 使用 do_awss_active();

是不是使用 do_awss_active 进入 awss_config_press就一定能进入配网？
void do_awss_active()
{
    LOG("do_awss_active %d\n", awss_running);
    awss_running = 1;
#ifdef WIFI_PROVISION_ENABLED
    extern int awss_config_press();
    awss_config_press();
#endif
}

**Comment by andy2012zwj** [comment]
你好，该问题可以到这个链接提工单处理：https://selfservice.console.aliyun.com/ticket/createIndex
