### ISSUE TITLE
钉钉群二维码已经过期，能够更新下

### ISSUE THREAD

**Issue by shuizhengqi1** [alibaba/AliOS-Things#1103]
首页的那个已经加不了了，遇到的问题整了好几天都没整明白，能不能更新下群二维码？

**Comment by andy2012zwj** [comment]
我们会尽快同步上去，请参考下这个链接能否访问：https://img.alicdn.com/tfs/TB1KgBhjXY7gK0jSZKzXXaikpXa-1170-818.png

**Comment by xiaowenxia** [comment]
钉钉群二维码已经更新:smile:
