### ISSUE TITLE
can not create a project using jsengine template

### ISSUE THREAD

**Issue by CJayakumar** [alibaba/AliOS-Things#1110]
Hello Team,

We cannot create a project using jsengine template. The steps provided in the README file but it cannot help.Please provide the steps to create a project using jsengine with build info.

Thank you

**Comment by xiaowenxia** [comment]
@CJayakumar Sorry, The document for JSEngine is not ready, but we have legacy documents in Chinese[check here](https://studio.iot.aliyun.com/device-doc#ebagtb.html), Hope these documents can help you.
