### ISSUE TITLE
能否通过配置烧写.BIN的时候写入默认的wifi  password和ssid

### ISSUE THREAD

**Issue by woshi520laoxie** [alibaba/AliOS-Things#1112]
由于ESP32开发板使用阿里APP始终无法连接网络
是否可以通过某种方式修改
linkkitapp@esp32devkitc
而设置默认的ssid   和 password
比如通过menuconfig 配置wifi  的账号和密码，因为使用smartconfig就是为了
把ssid和password告知模块，但是使用app无法连接。

**Comment by xiaowenxia** [comment]
ssid 和 password写在代码里面就好了呀。

**Comment by woshi520laoxie** [comment]
是的，有没有教程介绍这个ssid 和 password写入的位置呢?

**Comment by woshi520laoxie** [comment]
你好啊，你大概知道查找到&nbsp; ssid 和 password 的位置吗？
因为整个工程不小，需要一点一点的去分析的话，这个时间就长了。
我只能是一点一点的看看，大概运行方式。能提点一下就最好了。
