### ISSUE TITLE
Wrong python version:  Python 3.6.5 :: Anaconda, Inc. , please install python2.7

### ISSUE THREAD

**Issue by SQSFly** [alibaba/AliOS-Things#1120]
**Describe the bug**

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by suqisheng** [comment]
我用anaconda创建了python2.7 的环境，但是依然提示wrong version

**Comment by walker2048** [comment]
需要先在命令行中激活环境，你也可以先看看当前环境的python版本是否正确
