### ISSUE TITLE
Wifi not connected with b-l475e-iot01a board

### ISSUE THREAD

**Issue by CJayakumar** [alibaba/AliOS-Things#1121]
Hello Team,

We build the linkkitapp against the b_l475e board and uploaded the binary.
In the teraterm we were got the below message.

start-----------hal
             Welcome to AliOS Things
[   5.010]<E>atparser sem_wait failed
netm[  10.010]<E>atparser sem_wait failed
[  15.010]<E>atparser sem_wait failed
[  20.010]<E>atparser sem_wait failed
[  25.010]<E>atparser sem_wait failed

[  30.010]<E>atparser sem_wait failed

[  35.010]<E>atparser sem_wait failed

[  40.010]<E>atparser sem_wait failed

[  45.010]<E>atparser sem_wait failed

[  50.010]<E>atparser sem_wait failed

[  55.010]<E>atparser sem_wait failed

**[  55.010]<A>AOS start_netmgr**

[  57.020]<W>net mgr none config policy

[  57.020]<W>NETMGR_WIFI net mgr none config policy

[  60.020]<E>MQTT handler is null

[  60.020]<W>[und] CMP not ready

So we could not find the option to input the ssid and password.

Please help us to resolve the issue.

**Comment by andy2012zwj** [comment]
Hi，have you reffered to this document 
https://github.com/alibaba/AliOS-Things/wiki/stm32-networking
