### ISSUE TITLE
Ubuntu 系统默认的 kconfig工具，导致编译失败。

### ISSUE THREAD

**Issue by qinpan1003** [alibaba/AliOS-Things#1125]
**Describe the bug**
Ubuntu 16、CentOS 7系统， aos_kconfig.mk 使用系统默认的 kconfig工具，导致生成的 .config 选项带有 CONFIG_ 前缀，编译失败。

**environment**
1. branch(version): rel_3.0.0
2. Desktop OS(windows linux or macOS): Ubuntu 16、CentOS 7，系统已预装 kconfig 工具
3. example: aos make helloworld@linuxhost -c config && aos make

**Expected behavior**
期望：编译成功
实际：kconfig 配置出现警告、编译提示APP为 NULL

**Screenshots**
![image](https://user-images.githubusercontent.com/19748676/75410637-7fd65080-5957-11ea-824a-87567874f8d2.png)

**Additional context**
修改方法：build/build_rules/aos_kconfig.mk  强制下载、使用 AliOS 提供的 kconfig 工具。
验证结果：强制使用AliOS提供的 kconfig 工具，可以生成不带 CONFIG_ 前缀的 .config ，可以正常编译。

![image](https://user-images.githubusercontent.com/19748676/75410663-94b2e400-5957-11ea-8ad4-5f416903cae9.png)

![image](https://user-images.githubusercontent.com/19748676/75410708-b90ec080-5957-11ea-8423-327866a24377.png)

![image](https://user-images.githubusercontent.com/19748676/75410726-c62baf80-5957-11ea-8153-20b0e7f3361e.png)

**Comment by librae8226** [comment]
Verifed and merged.
