### ISSUE TITLE
Keil编译出现警告：A3912W：Option 'c' is deprecated

### ISSUE THREAD

**Issue by hhwjsw711** [alibaba/AliOS-Things#1130]
**Is your feature request related to a problem? Please describe.**
您好，我在测试华大芯片过程中编译出现警告，警告如下

![Snipaste_2020-03-03_17-00-57](https://user-images.githubusercontent.com/37205280/75759732-fe285d80-5d70-11ea-90e1-8aba8ff0243b.png)

我猜测是因为Keil的版本或者是编译工具版本不同引起的错误

我目前使用的Keil版本，如下

![Snipaste_2020-03-03_17-06-28](https://user-images.githubusercontent.com/37205280/75759965-62e3b800-5d71-11ea-90f2-94dcdf442645.png)

我目前使用的编译工具版本，如下

![Snipaste_2020-03-03_17-08-03](https://user-images.githubusercontent.com/37205280/75760072-96264700-5d71-11ea-9e91-370036b20781.png)

建议在Keil/IAR工程支持列表可以注明测试版本，如下

![Snipaste_2020-03-03_17-08-56](https://user-images.githubusercontent.com/37205280/75760153-c53cb880-5d71-11ea-96a6-457d2d6d310a.png)

谢谢，祝一切好！

**Describe the solution you'd like**

**Additional context**

**Comment by andy2012zwj** [comment]
你好，这个原因是生成的汇编代码的编译脚本中有-c的编译选项，keil不支持，这个应该不影响使用
