### ISSUE TITLE
编译 天猫精灵mesh接入工程成功，如何烧录到板子 pca10040？

### ISSUE THREAD

**Issue by xuhongv** [alibaba/AliOS-Things#1134]
我想编译天猫精灵 mesh的工程，现已编译成功，如何 烧录到指定的板子？
我手上也有这个板子！

`aos make blemesh_tmall@pca10040`

**environment**
1. branch(version): master 6c449089577cd99faa9b1f546cc5f421c3ff5a6b
2. Desktop OS : linux 
3. example: blemesh_tmall

**Comment by andy2012zwj** [comment]
参考这个链接，看看是否可以，https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things%E5%BC%80%E5%8F%91%EF%BC%9A%E8%AE%A9%E4%BD%A0%E7%9A%84%E5%BC%80%E5%8F%91%E6%9D%BF%E6%94%AF%E6%8C%81AliOS-Studio%E7%83%A7%E5%BD%95
