### ISSUE TITLE
如何添加.lib

### ISSUE THREAD

**Issue by sunhao-jz** [alibaba/AliOS-Things#1140]
我准备移植一个第三方的库，是.lib文件，但是vscode我如何包含这个库？

**Comment by andy2012zwj** [comment]
你好，可以在相应模块的makefile里添加静态库依赖，参考如下。 
$(NAME)_PREBUILT_LIBRARY := $(LIB_PATH)/libxxx.a

**Comment by sunhao-jz** [comment]
$(NAME)_PREBUILT_LIBRARY := $(LIB_PATH)/STemWin_CM3_OS_wc16_ARGB.lib   是这样写吗？我的库文件名是STemWin_CM3_OS_wc16_ARGB.lib

**Comment by andy2012zwj** [comment]
$(LIB_PATH)是lib库针对于.mk文件的相对路径

**Comment by sunhao-jz** [comment]
那我这个.lib的文件可以直接包含吗？还是说要转成.a的？

**Comment by andy2012zwj** [comment]
要确认一下，MCU架构、编译配置要一致

**Comment by sunhao-jz** [comment]
我用的就是stm32f103vct6吗，M3的内核
