### ISSUE TITLE
使用AliOS-Things/example/udataapp无法配网，netmgr无效

### ISSUE THREAD

**Issue by EienSakura** [alibaba/AliOS-Things#1143]
![9 ~S`)ZR7$I~G_XGC}3 HP4](https://user-images.githubusercontent.com/50508678/77222005-2645f800-6b8a-11ea-978a-a97043281c16.png)

**Comment by EienSakura** [comment]
开发板为developer kit

**Comment by andy2012zwj** [comment]
你好，能确认下使用linkkitapp是否可以通过netmgr命令配网；另外，确认下wifi固件已经升级：https://github.com/alibaba/AliOS-Things/wiki/wifi_upgrade_guide.md
