### ISSUE TITLE
Developer kit JS编译报错

### ISSUE THREAD

**Issue by EienSakura** [alibaba/AliOS-Things#1144]
![image](https://user-images.githubusercontent.com/50508678/77245045-83a77b00-6c56-11ea-8c35-c68c8823d3b5.png)
![image](https://user-images.githubusercontent.com/50508678/77245058-91f59700-6c56-11ea-920f-dc91e0789907.png)
这个open未定义怎么回事，我看似乎sample里是这样的，还有这个board.json应该怎么设置，port从哪里获取？

**Comment by xiaowenxia** [comment]
@EienSakura open未定义，是因为需要

**Comment by EienSakura** [comment]
> @EienSakura open未定义，是因为需要在menuconfig中配置使能gpio功能：
> 
> 进入：`Middleware` > `JSEngine` > `JSEngine Addon Modules` > `Hardware Addon Modules`
> 
> ![image](https://user-images.githubusercontent.com/16155447/77280462-519e2380-6cff-11ea-95aa-b0d61bb777f1.png)
> 
> `board.json`怎么配置可以参考这篇文档：https://studio.iot.aliyun.com/device-doc#booofy.html

![image](https://user-images.githubusercontent.com/50508678/77284916-cc207080-6d0a-11ea-825c-deccd540439d.png)
运行之后报了这个是怎么解决

**Comment by xiaowenxia** [comment]
@EienSakura `board.json`怎么写的呢？提示board.json解析失败。

**Comment by EienSakura** [comment]
> @EienSakura `board.json`怎么写的呢？提示board.json解析失败。
![image](https://user-images.githubusercontent.com/50508678/77289240-8cf71d00-6d14-11ea-9b7a-a551b813439d.png)

![image](https://user-images.githubusercontent.com/50508678/77289251-91233a80-6d14-11ea-8491-400232481edf.png)
![image](https://user-images.githubusercontent.com/50508678/77289267-997b7580-6d14-11ea-9c4b-b4a47f01394b.png)

**Comment by EienSakura** [comment]
{
  "I2C": [
    {
      "id": "shtc1",
      "port": 2,
      "address_width": 7,
      "freq": 100000,
      "mode": 1,
      "dev_addr": 224
    }
  ]
}

console.log('start i2c test.....................');
setInterval(function () {

  var shtc1Handle = I2C.open('shtc1');
  var Reg = [0xEF, 0xC8];
  I2C.write(shtc1Handle, Reg);
  var retArray = I2C.read(shtc1Handle, 2);
  console.log('ID:' + retArray[1]);
  Reg[0] = 0x80;
  Reg[1] = 0x5D;
  I2C.write(shtc1Handle, Reg);
  Reg[0] = 0x7C;
  Reg[1] = 0xA2;
  I2C.write(shtc1Handle, Reg);
  var TempHumm = I2C.read(shtc1Handle, 6);
  console.log('read len:' + TempHumm.length);
  var i = 0;
  for (i = 0; i < TempHumm.length; i++) {
    console.log('rawData[' + i + ']:' + TempHumm[i]);
  }
  I2C.close(shtc1Handle);
}, 2000);
console.log('end i2c test........................');

**Comment by EienSakura** [comment]
@xiaowenxia 拜托大佬指导一下，我这边是想做一个往云平台上上传温湿度数据的项目，看wiki那边的例子又一直报错
