### ISSUE TITLE
be-cli的编译问题

### ISSUE THREAD

**Issue by EienSakura** [alibaba/AliOS-Things#1146]
![image](https://user-images.githubusercontent.com/50508678/77275892-54474b80-6cf4-11ea-9d47-5ac28fdc92b3.png)
这边这样子怎么解决，reboot也无法解决

**Comment by andy2012zwj** [comment]
软件环境和编译命令可以描述一下吗

**Comment by EienSakura** [comment]
编译命令：be -p bone
环境：windows
就是按着这个这个http://aliosthings.io/#/zh-cn/boneengine_firstjs?id=1-%e5%87%86%e5%a4%87%e5%b7%a5%e4%bd%9c做的

**Comment by EienSakura** [comment]
开发板是developer kit

**Comment by EienSakura** [comment]
> 软件环境和编译命令可以描述一下吗

编译命令：be -p bone
环境：windows
就是按着这个这个http://aliosthings.io/#/zh-cn/boneengine_firstjs?id=1-%e5%87%86%e5%a4%87%e5%b7%a5%e4%bd%9c做的

**Comment by xiaowenxia** [comment]
@EienSakura be-cli工具使用，参考这个文档哈：[be-cli quickstart](https://github.com/alibaba/AliOS-Things/wiki/be-cli-quickstart)。

**Comment by EienSakura** [comment]
> @EienSakura be-cli工具使用，参考这个文档哈：[be-cli quickstart](https://github.com/alibaba/AliOS-Things/wiki/be-cli-quickstart)。

![image](https://user-images.githubusercontent.com/50508678/77281065-084ed380-6d01-11ea-82c8-c9afb6edac26.png)
还是有问题
