### ISSUE TITLE
AliOS-Things udataapp@developkit mqtt连接不上云服务器

### ISSUE THREAD

**Issue by EienSakura** [alibaba/AliOS-Things#1149]
3.0和master版本都试过了都不行，WiFi和热点也都试过，也都不行
`             Welcome to AliOS Things           
[   0.150]<A>AOS uData:  udata_service_mgr_init successfully 

[   0.160]<A>AOS uData:  abs_data_open successfully

[   0.170]<A>AOS uData:  register service type 0  success

[   0.180]<A>AOS sensor:  drv_mag_memsic_mmc3680kj_open successfully 

[   0.180]<A>AOS uData:  abs_data_open successfully

[   0.190]<A>AOS uData:  register service type 1  success

[   0.200]<A>AOS uData:  abs_data_open successfully

[   0.210]<A>AOS uData:  register service type 2  success

[   0.220]<A>AOS sensor:  drv_als_liteon_ltr553_open successfully 

[   0.230]<A>AOS uData:  abs_data_open successfully

[   0.230]<A>AOS uData:  register service type 3  success

[   0.240]<A>AOS sensor:  drv_ps_liteon_ltr553_open successfully 

[   0.250]<A>AOS uData:  abs_data_open successfully

[   0.260]<A>AOS uData:  register service type 4  success

[   0.270]<A>AOS sensor:  drv_baro_bosch_bmp280_open successfully 

[   0.280]<A>AOS sensor:  drv_baro_bosch_bmp280_ioctl successfully 

[   0.280]<A>AOS uData:  abs_data_open successfully

[   0.290]<A>AOS uData:  register service type 5  success

[   0.300]<A>AOS sensor:  drv_temp_sensirion_shtc1_open successfully 

[   0.310]<A>AOS uData:  abs_data_open successfully

[   0.320]<A>AOS uData:  register service type 6  success

[   0.320]<A>AOS sensor:  drv_humi_sensirion_shtc1_open successfully 

[   0.330]<A>AOS uData:  abs_data_open successfully

[   0.340]<A>AOS uData:  register service type 8  success

[   0.350]<A>AOS uData:  cali_example_example_init successfully 

[   0.360]<A>AOS uData:  abs_data_cali_init successfully 

[   0.360]<A>AOS uData:  udata_init successfully

[   0.370]<E>sal_wifi Uart dev is not configured, use the default cfg

uart 1 enter uart_receive_start_dma instance 0x40004800== Build on: Mar 24 2020 11:10:30 ===
[   2.400]<A>AOS uData:  udata_subscribe successfully

[   2.410]<A>AOS uData:  udata_subscribe successfully

[   2.410]<I>wifi_port Will connect via at cmd: AT+WJAP=P30,987654321

[   7.420]<E>wifi_port AT command AT+WJAP=P30,987654321 failed

[   7.620]<I>wifi_port AT command AT+WMAC? succeed, rsp: 
+WMAC:e47deb141618

OK

[   7.630]<I>wifi_port mac result: 

[   7.630]<I>NETMGR_WIFI Got ip : 192.168.43.155, gw : 192.168.43.1, mask : 255.255.255.0

[   7.660]<I>wifi_port AT command AT+WMAC? succeed, rsp: 
+WMAC:e47deb141618

OK

[   7.670]<I>wifi_port mac result: 

[   7.680]<A>AOS Hello, WiFi GOT_IP event! at board/developerkit/aos/board_cli.c 216

[   7.690]<A>AOS Hello, WiFi GOT_IP event! at board/developerkit/aos/board_cli.c 216

[   7.700]<A>AOS wifi_service_event!

[   7.710]<W>MQTT Using default hostname: 'a1c01AmHDLo.iot-as-mqtt.cn-shanghai.aliyuncs.com'

[   7.720]<W>MQTT Using default port: [443]

[   7.730]<W>MQTT Using default client_id: a1c01AmHDLo.DevelopKit2Temp|timestamp=2524608000000,_v=sdk-c-3.0.1,securemode=2,signmethod=hmacsha256,lan=C,_ss=1,gw=0,ext=0|

[   7.750]<W>MQTT Using default username: DevelopKit2Temp&a1c01AmHDLo

[   7.750]<W>MQTT Using default password: ******

[   7.760]<W>MQTT Using default request_timeout_ms: 5000, configured value(0) out of [1000, 10000]

[   7.770]<W>MQTT Using default keepalive_interval_ms: 60000, configured value(0) out of [30000, 1200000]

[   7.790]<W>MQTT Using default read_buf_size: 3072

[   7.790]<W>MQTT Using default write_buf_size: 3072

[   7.800]<I>MQTT MQTT init success!

[   7.990]<I>HAL_TLS Loading the CA root certificate ...

[   8.000]<I>HAL_TLS  ok (0 skipped)

[   8.000]<I>HAL_TLS Connecting to /a1c01AmHDLo.iot-as-mqtt.cn-shanghai.aliyuncs.com/443...

[prt] dns server: 223.5.5.5
[   8.030]<I>sal_wifi Server conn (0) successful.

[  13.020]<E>atparser sem_wait failed

[  13.090]<I>sal_wifi Server closed event.

[  13.090]<I>sal_wifi Server conn (0) closed.

[  13.100]<I>HAL_TLS ip address: 106.15.100.2

[  13.110]<I>HAL_TLS setsockopt SO_SNDTIMEO timeout: 10s

[  13.180]<I>sal_wifi Server conn (0) successful.

[  18.120]<E>atparser sem_wait failed

[  18.120]<I>HAL_TLS  ok

[  18.120]<I>HAL_TLS   . Setting up the SSL/TLS structure...

[  18.130]<I>HAL_TLS  ok

[  18.140]<I>HAL_TLS Performing the SSL/TLS handshake...

[  23.340]<I>sal_wifi Server conn (0) disconnected.

[  23.820]<E>atparser sem_wait failed

[  33.830]<E>HAL_TLS failed  ! mbedtls_ssl_handshake returned -0x6800

[  33.840]<E>sal_wifi HAL_SAL_Close 777 failed

[  33.840]<I>HAL_TLS ssl_disconnect

[  33.850]<E>HAL_TLS handle is NULL

[  33.850]<E>MQTT TCP or TLS Connection failed`

**Comment by andy2012zwj** [comment]
你好，这个开发板是developerkit吧，另外可以换成udata_demo.udata_cloud_demo试一下
