### ISSUE TITLE
延迟函数

### ISSUE THREAD

**Issue by sunhao-jz** [alibaba/AliOS-Things#1151]
Alios 延迟函数是哪个api aos_sleep?

**Comment by sunhao-jz** [comment]
有没有用ticks的延迟

**Comment by andy2012zwj** [comment]
可以用void aos_msleep(int ms)函数，单位是ms；另外可以通过以下函数实现tick和ms的转换：krhino_ms_to_ticks，krhino_ticks_to_ms

**Comment by sunhao-jz** [comment]
是的，延迟OK了
