### ISSUE TITLE
mk3080  阿里云直连固件

### ISSUE THREAD

**Issue by sunhao-jz** [alibaba/AliOS-Things#1155]
下载包里有两个固件，一个是带OTA的这两个固件有什么区别？有没有什么说明文档？

**Comment by andy2012zwj** [comment]
带OTA的固件里没有boot，只有os部分；另外一个bin文件包含boot和os部分。
第一次烧录的时候，可以烧录第二个固件（boot+os部分）；OTA升级的时候，只烧录ota固件就可以；

**Comment by sunhao-jz** [comment]
boot是启动引导程序吗？

**Comment by andy2012zwj** [comment]
是的

**Comment by sunhao-jz** [comment]
在一键配网中，有一个用到手机端的APP  云智能  这个APP在哪里下载？

**Comment by sunhao-jz** [comment]
还有这个固件是连接飞燕平台的还是物联网lot平台的？
