### ISSUE TITLE
STM32f103直接通过at指令驱动MK3080

### ISSUE THREAD

**Issue by sunhao-jz** [alibaba/AliOS-Things#1157]
需要移植哪几个文件，才能上云？底层nal文件的驱动连接在哪个文件里？

**Comment by andy2012zwj** [comment]
你好，可以参考该文档来实现：https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-3.0-AT%E6%A8%A1%E7%BB%84%E9%A9%B1%E5%8A%A8%E4%B8%80%E7%AB%99%E5%BC%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

**Comment by sunhao-jz** [comment]
Welcome to AliOS Things           
[   0.372]<E>atparser at dev init failed


[   0.377]<E>atparser assign dev fd fail


[   0.383]<E>linkkit_at AT parser device add failed!


[   2.389]<E>linkkit_at at_device_config 542 failed

[   2.395]<E>linkkit_at connect_wifi_by_cmd 585 failed

**Comment by sunhao-jz** [comment]
我移植直连阿里云的库，这些错误是什么意思？而且at串口无法使能
