### ISSUE TITLE
keil编译出3.1出现警告

### ISSUE THREAD

**Issue by aktoey** [alibaba/AliOS-Things#1158]
port_s.S: Warning: A3912W: Option 'c' is deprecated.
panic_armcc.S: Warning: A3912W: Option 'c' is deprecated.
startup_stm32l496xx_keil.s: Warning: A3912W: Option 'c' is deprecated.
怎么去掉这些警告

**Comment by andy2012zwj** [comment]
这些告警暂不影响使用
