### ISSUE TITLE
EMW3080怎么烧录原始的alios things 固件

### ISSUE THREAD

**Issue by Torchwoods** [alibaba/AliOS-Things#1159]
rel_3.1.0,版本的固件，想将编译出来的bin文件（linkkit_demo@mk3080.bin）烧录到EMW3080开发板上，怎么使用串口烧录的？

**Comment by andy2012zwj** [comment]
可以参考该文档烧录https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Studio#%E7%83%A7%E5%BD%95---upload
