### ISSUE TITLE
js解释器资源占用怎么样？

### ISSUE THREAD

**Issue by kolychen** [alibaba/AliOS-Things#116]
1.JS解释器资源占用怎么样？

2. 有考虑过lua吗，或做过资源占用对比吗？

**Comment by junjiec** [comment]
https://github.com/alibaba/AliOS-Things/tree/master/framework/bone_engine
先参考一下这里

**Comment by fenggui321** [comment]
@junjiec 你给的链接里面相关说明的链接失效了（README.md没有更新吧）。
另外：看了下doc目录，说为了支持更多人入门alios就支持了下js。没整明白从目前流行的开发语言来看js开发者数量好像也不支持这个结论。从资源消耗，与C结合程度，与lua或者其它排名靠前语言如何？另外：到目前为止用这个模块的体验和数据支持进一步开发增强JS么？如果没必要，还不如集中精力追freertos

**Comment by guoxiyuan** [comment]
@fenggui321  支持JS是为了给开发者提供一种脚本开发语言运行和编程环境，在python，LUA，JS中，从占用资源性价比上（RAM，ROM，CPU）我们更倾向选择 JS 语言，包括从即将要提供的图形化开发工具的考虑；后续JS 支持方向上，我们会持续优化和支持跟多JS本地扩展模块，提供IDE图形开发/调试工具（整合 Native 扩展模块，所见即所得，类似Node-RED），JSE 语法能力增强以及性能优化，当然 JSE 语法能力增强可能会消耗跟多的资源，需要客户根据自身的需求来做选择，目前JSE大概消耗10KB左右 RAM；

**Comment by fenggui321** [comment]
GUI啊，这块不太懂，不做评论

**Comment by wurei** [comment]
gui不是iotos的重点，ANSI C的gui也不少，比如nuklear/imgui已经很不错了，嵌入式脚本里面主流的还是lua比较多
