### ISSUE TITLE
Port Guide For Ali TEE Air

### ISSUE THREAD

**Issue by TheSilentDawn** [alibaba/AliOS-Things#1170]
**Is your feature request related to a problem? Please describe.**
Our team try to build a secure solution based on Arm-v8m TrustZone feature by leveraging Ali TEE Air. However, the results after google are only for ck802t and Nuvoton M2351.

**Describe the solution you'd like**
Could you please provide an Ali TEE Air port guide document for other platform? Especially STM32L5xxx series . 
Or Could you please provide the off-the-shelf library for STM32L552-EV board?
Thanks.

**Additional context**

**Comment by wqqqy** [comment]
> **Is your feature request related to a problem? Please describe.**
> Our team try to build a secure solution based on Arm-v8m TrustZone feature by leveraging Ali TEE Air. However, the results after google are only for ck802t and Nuvoton M2351.
> 
> **Describe the solution you'd like**
> Could you please provide an Ali TEE Air port guide document for other platform? Especially STM32L5xxx series .
> Or Could you please provide the off-the-shelf library for STM32L552-EV board?
> Thanks.
> 
> **Additional context**

Hi!
Do you have the code and documentation for Ali TEE Air on ck802t and Nuvoton M2351?
