### ISSUE TITLE
esp8266 看门狗都没支持上？ alios下如何使用看门狗呢？

### ISSUE THREAD

**Issue by mylove3588** [alibaba/AliOS-Things#1172]

**Comment by andy2012zwj** [comment]
esp8266底层watchdog驱动未适配

**Comment by mylove3588** [comment]
我看hal层是未实现的，知道如何启用SDK里边的看门狗吗，一直未找到启动初始化相关API

**Comment by JalonFungar** [comment]
同问啊兄弟，现在用aliosthings开发，运行三天卡死了。偶发；没看门狗搞个屁，出货了几k，每天让我瑟瑟发抖。

**Comment by mylove3588** [comment]
用的哪个版本？ 我测试3.1版本也会偶尔死机&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/AliOS-Things"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午2:02
收件人:&nbsp;"alibaba/AliOS-Things"<AliOS-Things@noreply.github.com&gt;;
抄送:&nbsp;"bing"<415543968@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/AliOS-Things] esp8266 看门狗都没支持上？ alios下如何使用看门狗呢？ (#1172)





 
同问啊兄弟，现在用aliosthings开发，运行三天卡死了。偶发；没看门狗搞个屁，出货了几k，每天让我瑟瑟发抖。

**Comment by JalonFungar** [comment]
Version：rel_3.0.0
Hardware：博安通esp8266-12f
数量：4PCS（3PCS work well , 1PCS failed）
场景：挂了三天，无故卡死。
尝试方案：:我做了超时重启重连和wifi断开重连；给串口发送客制化command一般会有回复的，但是客制化的串口命令NACK，基本判定模块已经挂了。（很难复现）

PS：老哥解决了同步下哈~

**Comment by mylove3588** [comment]
我测试一般是WIFI断开 然后重连的时候，链接上马上就挂了，频繁断开链接，有时候一天会挂，有时候一周都没事，暂无办法~






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/AliOS-Things"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午2:17
收件人:&nbsp;"alibaba/AliOS-Things"<AliOS-Things@noreply.github.com&gt;;
抄送:&nbsp;"bing"<415543968@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/AliOS-Things] esp8266 看门狗都没支持上？ alios下如何使用看门狗呢？ (#1172)





 
Version：rel_3.0.0
 Hardware：博安通esp8266-12f
 数量：4PCS（3PCS work well , 1PCS failed）
 场景：挂了三天，无故卡死。
 尝试方案：:我做了超时重启重连和wifi断开重连；给串口发送客制化command一般会有回复的，但是客制化的串口命令NACK，基本判定模块已经挂了。（很难复现）
 
PS：老哥解决了同步下哈~
