### ISSUE TITLE
下载了AliOS-Things的docker之后，编译显示无法找到board

### ISSUE THREAD

**Issue by desword** [alibaba/AliOS-Things#1180]
**Describe the bug**
下载了AliOS-Things的docker之后，编译显示无法找到board

$ aos make helloworld@linuxhost -c config && aos make 
aos-cube :0.3.0b3
ERROR: can not find board linuxhost

**environment**
1. branch(version):  rel_3.1.0
2. Desktop OS(windows linux or macOS): Linux 16.04 LTS

但是我在platform/board里面找到了有linuxhost，

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
