### ISSUE TITLE
fatal error: k_types.h: No such file or directory

### ISSUE THREAD

**Issue by lincoln310** [alibaba/AliOS-Things#1184]
**Describe the bug**

官方定制下载的一个工程，缺少很多东西，我们做了下列操作：
1. 先是从aliosthings源代码中把build文件夹copy过来
2. 修改了build/config.in中缺少的内容
3. 选择example和board进行build
报如下错误：

#
# configuration written to .config
#
Making config file for first time
processing components: helloworld stm32f429zi-nucleo
*** All Components: helloworld stm32f429zi-nucleo osal_aos mcu_stm32f4xx_cube kernel_init network rhino newlib_stub ulog lwip lib_rbtree vfs
Build AOS Now
TOOLCHAIN_PATH=
Compiling helloworld
Compiling board_stm32f429zi-nucleo
In file included from platform/board/stm32f429zi-nucleo/config/k_config.c:5:0:
./core/rhino/include/k_api.h:28:10: fatal error: k_types.h: No such file or directory
 #include "k_types.h"
          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [out/helloworld@stm32f429zi-nucleo/modules/platform/board/stm32f429zi-nucleo/config/k_config.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [main_app] Error 2

**environment**
1. branch(version):  release3.1
2. Desktop OS(windows linux or macOS): macos
3. example: 

**Expected behavior**
希望能编译成功

**Screenshots**
![image](https://user-images.githubusercontent.com/7071490/84104935-66aa6900-aa49-11ea-8539-c2ea97daa643.png)

**Additional context**
我们想用stm32f407，但是没有已有的可用模板，所以需要移植制作一个。

**Comment by andy2012zwj** [comment]
可以从github上下载相关版本的代码，请参考stm32f429zi移植；
