### ISSUE TITLE
ESP32 连接缓慢 (ESP32 BLE Connect slowly)

### ISSUE THREAD

**Issue by JunJianX** [alibaba/AliOS-Things#1240]
**Is your feature request related to a problem? Please describe.**
为什么esp32作为bleperipheral工作时，将CONFIG_BT_MAX_CONN限制为1时，第二次连接就特别慢啊？

Why is esp32 working as a bleperipheral, when CONFIG_BT_MAX_CONN is limited to 1, the second connection is particularly slow?

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
