### ISSUE TITLE
VSCode安装aos-cube出错

### ISSUE THREAD

**Issue by yangwanglong** [alibaba/AliOS-Things#1249]
打开VSCode的时候右下角提示我是否安装aos-cube，我点了yes之后开始安装，下面是安装结果输出
Installing builtin aos-cube, please wait...
pip3 install --upgrade pip --trusted-host=mirrors.aliyun.com -i https://mirrors.aliyun.com/pypi/simple/
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: pip in c:\users\long\appdata\roaming\python\python36\site-packages (20.3.3)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future  version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip3 install virtualenv --trusted-host=mirrors.aliyun.com -i https://mirrors.aliyun.com/pypi/simple/
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: virtualenv in c:\users\long\appdata\roaming\python\python36\site-packages (20.2.2)
Requirement already satisfied: importlib-metadata>=0.12 in c:\users\long\appdata\roaming\python\python36\site-packages (from virtualenv) (3.3.0)
Requirement already satisfied: six<2,>=1.9.0 in c:\program files\python\lib\site-packages (from virtualenv) (1.12.0)
Requirement already satisfied: importlib-resources>=1.0 in c:\users\long\appdata\roaming\python\python36\site-packages (from virtualenv) (3.3.0)
Requirement already satisfied: filelock<4,>=3.0.0 in c:\users\long\appdata\roaming\python\python36\site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\users\long\appdata\roaming\python\python36\site-packages (from virtualenv) (0.3.1)
Requirement already satisfied: appdirs<2,>=1.4.3 in c:\users\long\appdata\roaming\python\python36\site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: zipp>=0.5 in c:\users\long\appdata\roaming\python\python36\site-packages (from importlib-metadata>=0.12->virtualenv) (3.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\users\long\appdata\roaming\python\python36\site-packages (from importlib-metadata>=0.12->virtualenv) (3.7.4.3)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
virtualenv C:\Users\Long\.aos\python-venv --no-download
Error: spawn virtualenv ENOENT

然后右下角提示
install aos-cube ERROR

这是什么原因啊？   要怎么弄啊？

**Comment by FlyLu** [comment]
这个问题我刚刚遇到，好像是系统已经安装了virtualen，所以没法用
参考如下步骤
1. 命令行中 pip uninstall virtualenv
2. vscode 输入shift+ctrl+p，在输入alios-studio:install aos-cube
