### ISSUE TITLE
AliOS security vulnerability contact / process 

### ISSUE THREAD

**Issue by sei-vsarvepalli** [alibaba/AliOS-Things#1251]
**Is your feature request related to a problem? Please describe.**

 I would like to know where to send information about security issues found in AliOS 

**Describe the solution you'd like**

A Githuh Security Advisory workflow started to privately communicate issues https://github.com/alibaba/AliOS-Things/security/advisories 

**Additional context**

**Comment by skylarCai** [comment]
The information and hazards of the vulnerabilities in AliOS Things can be described by visiting the https://security.alibaba.com/
