### ISSUE TITLE
请问有支持js开发ui的计划吗？

### ISSUE THREAD

**Issue by camel007** [alibaba/AliOS-Things#1267]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by ElliottSeer** [comment]
我们已经有HaaS UI 的JS解决方案了，并且可供免费使用。更多信息可以加入钉钉群获取
![image](https://user-images.githubusercontent.com/40886115/109122826-21b79580-7784-11eb-96ae-7cd8ca6b54fe.png)

**Comment by FreshLuoBoGan** [comment]
> 我们已经有HaaS UI 的JS解决方案了，并且可供免费使用。更多信息可以加入钉钉群获取 ![image](https://user-images.githubusercontent.com/40886115/109122826-21b79580-7784-11eb-96ae-7cd8ca6b54fe.png)

这个群进不去，方便再发一个吗？

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。

**Comment by YiluMao** [comment]
哦，这个问题也是您提的呀，那我们就在另一个问题里面讨论吧

**Comment by ElliottSeer** [comment]
> > 我们已经有HaaS UI 的JS解决方案了，并且可供免费使用。更多信息可以加入钉钉群获取 ![image](https://user-images.githubusercontent.com/40886115/109122826-21b79580-7784-11eb-96ae-7cd8ca6b54fe.png)
> 
> 这个群进不去，方便再发一个吗？

试试这个
![image](https://user-images.githubusercontent.com/40886115/150908694-c7854b7a-1a7a-4e3d-b6a5-6a0e72dc63eb.png)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。
