### ISSUE TITLE
hal I2C 接口小建议

### ISSUE THREAD

**Issue by shaoguoji** [alibaba/AliOS-Things#127]
在 aos 的 hal I2C 接口中只提供了 hal_i2c_master_send()、hal_i2c_master_recv() 主机数据传输接口，更侧重应用代码，而没有更具体的 hal_i2c_start()、hal_i2c_stop()、hal_i2c_wirte_byte() 等「细粒度」操作。这样在编写不同传感器驱动时不能很灵活实现各种操作序列，不知道这是不是可以改进的地方呢……

![we can do it](http://i.dailymail.co.uk/i/pix/2010/05/06/article-1273938-09297B21000005DC-915_468x508.jpg)

**Comment by jason-sophia** [comment]
@shaoguoji  请问hal_i2c_start()、hal_i2c_stop()、hal_i2c_wirte_byte() 有什么具体的使用场景？目前的接口无法满足吗？

**Comment by shaoguoji** [comment]
@jason-sophia比如需要重复起始信号时

**Comment by chenlingjun888** [comment]
需要重复起始信号的读写也可以封装在读写的逻辑里面的。让用户去了解i2c内部时序如何运作是不友好的。
