### ISSUE TITLE
使用VScode插件的Alios Studio的Web Serial串口连接工具报错

### ISSUE THREAD

**Issue by HyoKImAbsolut** [alibaba/AliOS-Things#1301]
![image](https://user-images.githubusercontent.com/43777779/110213287-50e3aa80-7eda-11eb-8ae8-7c3f48b07388.png)

在linux桌面环境(deepin)和windows下都是这个错误打不开串口工具，可能和系统无关？

AliOS Studio插件版本：v0.12.9
VSCode版本：1.54.1

**Comment by HyoKImAbsolut** [comment]
一键docker安装的Web VSCode里也是一样的错误，打不开串口工具

**Comment by JiangJohnny** [comment]
建议自行安装一个串口工具，不要使用这个web serial
