### ISSUE TITLE
最新的Alios-Things如何移植支持其他的芯片或者开发板？比如ESP32，ESP8266或者STM32？

### ISSUE THREAD

**Issue by D-zz** [alibaba/AliOS-Things#1318]

**Comment by jinliangli** [comment]
可以参考这个文档移植的： https://github.com/alibaba/AliOS-Things/blob/master/documentation/manual/bsp_development.md

有问题也可以随时沟通。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。
