### ISSUE TITLE
提个建议build里的cmd命令工具

### ISSUE THREAD

**Issue by anonymous5l** [alibaba/AliOS-Things#1319]
**Is your feature request related to a problem? Please describe.**
主机为linux64 archlinux  默认不带sellinux 但是cmd/build里的工具cp 和rm 等都是带sellinux的`aos make`的时候就会发生错误找不到`libsellinux`共享库 

**Describe the solution you'd like**
针对linux的版本工具可以去掉`libsellinx`依赖

**Additional context**
现在用`ln`命令暂时解决了这个问题

**Comment by JiangJohnny** [comment]
非常感谢你的建议，我们将考虑如何在archlinux系统下运行。
