### ISSUE TITLE
Developer kit 支持

### ISSUE THREAD

**Issue by sabotage** [alibaba/AliOS-Things#1337]
www.notioni.com 之前发布过一款 alios-things developer kit 和 starter kit, 其实硬件功能还是很丰富的, 作为入门学习硬件非常不错. 但为什么现在的alios-things 不再支持了呢? 希望能够继续支持! 毕竟市场上还有很多在售卖.

**Comment by YiluMao** [comment]
能不能帮忙提供下developer kit 和 starter kit相关的信息？

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。
