### ISSUE TITLE
HaaS Studio的一点问题

### ISSUE THREAD

**Issue by qxdn** [alibaba/AliOS-Things#1341]
![BF1ZJSQSHBLA%S%27%{4PLD](https://user-images.githubusercontent.com/42409827/141417087-782fa7e2-b6ef-475a-b636-e6090a18e273.png)

插件能否就在Haas Studio创建的工程下激活，而不是每个vscode工作区都激活并设置环境变量。有点影响原本anaconda环境使用。

`"haasStudio.injectEnv": false`只能设置新开的terminal不激活，但是每次打开vscode的时候还是会改变环境变量

**Comment by zetamind** [comment]
目前暂时还不支持，后续会进行改进

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。
