### ISSUE TITLE
进程间通信，可以参考哪里？

### ISSUE THREAD

**Issue by FreshLuoBoGan** [alibaba/AliOS-Things#1348]
https://haas.iot.aliyun.com/aliosthings/index.html

我在这个指导文档中没有找到进程间通信的接口，但是我看图里面有，麻烦请教一下，我可以参考哪里。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。

**Comment by YiluMao** [comment]
你可以看看我们微内核分支的代码
目前我们3.3还没有支持进程，所以这部分代码是没有的

**Comment by YiluMao** [comment]
另外，有没有兴趣加入我们？
https://talent.alibaba.com/off-campus-position/727473?trace=qrcode_share

可以把简历给我哈

**Comment by FreshLuoBoGan** [comment]
> 你可以看看我们微内核分支的代码 目前我们3.3还没有支持进程，所以这部分代码是没有的

微内核分支代码麻烦引导一下。

**Comment by FreshLuoBoGan** [comment]
> 另外，有没有兴趣加入我们？ https://talent.alibaba.com/off-campus-position/727473?trace=qrcode_share
> 
> 可以把简历给我哈

**Comment by skylarCai** [comment]
> > 你可以看看我们微内核分支的代码 目前我们3.3还没有支持进程，所以这部分代码是没有的
> 
> 微内核分支代码，我去哪里可以看到，

请切换到[rel_microkernel](https://github.com/alibaba/AliOS-Things/tree/rel_microkernel) 分支，此分支为微内核代码

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
        您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
        如果“HaaS百事通”没有解决您的问题，我们会在两个工作日回复您。

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
