### ISSUE TITLE
【AliOS Things】 首届灭虫活动，找Bug，赢大奖！

### ISSUE THREAD

**Issue by jiyong3998** [alibaba/AliOS-Things#1350]
简介：针对AliOS Things的所有组件模块，通过Monkey Test，压测等多种方式，测试组件及系统的稳定性。

**预热时间** ：即日起—2022年2月14日【在此期间您可以报名参与此活动，并开始您的灭虫准备工作】

**活动时间** ：2022年2月14日—2022年3月6日【在此期间您可以提交您的灭虫反馈】

**发奖时间** ：活动结束一周内发布获奖名单

**参与方式** ：点击链接报名按钮即，并按照指示操作即可参与活动

**报名链接** ：
[https://developer.aliyun.com/learning/topic/team/aliosthings/1](https://developer.aliyun.com/learning/topic/team/aliosthings/1)

**活动规则** ：
（选定一个案例，通过下面几种方式参与灭虫活动并获得累计积分，每种方式可重复参加，例：您可以发现并解决多个HaaS的代码Bug，并提交Pull Requests（后面简称PR）到gitee AliOS Things 开源社区。 HaaS活动方最终按照累计积分进行排名，优胜者获取一定的物质奖励。）

1、【10积分】发现并解决HaaS的 **代码** Bug，并提交PR到gitee AliOS Things 开源社区

2、【3积分】发现HaaS的 **代码** Bug，并将Bug信息和复现步骤提交到gitee AliOS Things 开源社区Issues板块

3、【3积分】发现并解决HaaS的 **文档** Bug，并提交PR到gitee AliOS Things 开源社区

4、【1积分】发现HaaS的 **文档** Bug，并将Bug信息和建议提交到gitee AliOS Things 开源社区Issues板块

[<点击此处进入gitee AliOS Things 开源社区>](https://gitee.com/alios-things-admin/AliOS-Things)

[<点击此处进入gitee AliOS Things 开源社区Issues板块>](https://gitee.com/alios-things-admin/AliOS-Things/issues)

注意事项 ：

1、阿里云IoT对活动积分累计规则及活动细则有最终解释权；

2、首期活动持续3个周，活动开始后开发者自行购买HaaS200板 [点击此处购买Haas200开发板](https://item.taobao.com/item.htm?spm=a230r.1.14.16.59783972B9gBun&id=645971366946&ns=1&abbucket=14#detail)

3、开发者发现AliOS Things的bug（包括代码/文档），并在gitee上提交PR或Issues以获取一定的积分，合理的PR/Issue均可获取积分；

4、针对单个模块某个功能存在的bug，开发者可以提交多个PR或者Issue，最终仅核算1次有效积分；

5、针对单个模块某个功能存在多个bug，开发者可以提交多个PR或者Issue，最终按功能真实bug数量核算有效积分；

6、针对单个文档的bug，开发者可以提交几个PR或者Issue，最终按bug数量核算有效积分；

7、凡是发现代码/文档bug并在GitHub上提交PR或Issue的参与者，均可获得 **参与奖** 。

**细则** ：

a. 开发者提交的patch要确保能够集成；

b. 开发者发现的bug需要先在issues页面提交问题；

c. 如果开发者有解决方案，开发者需要提交Pull Request，并按照如下格式提交commit：

IssueID： xxxx： description

[Detail]

Issue description:

xxxx

Rootcause:

xxxx

Solution:

xxxx

Requirement description:

xxxx

Solution:

xxxx

[Verified Cases]

Build Pass: xxxx

Test Pass: HaaS200

其中，

IssueID的xxxx 使用提交Iussues的ID

description部分描述PR的主要功能，不超过80个字符，只能用英文

Build Pass 指定编译系统类型，可选址为Linux, MacOS, Windows

4）其他字段尽量详细，如不存在则可以留白

**下面是一个详细案例** ：

BugID: 3875: Fix I2C open failed issue

[Detail]

Issue description:

I2C failed to open and return -6 error code

Rootcause:

I2C has not been inited after params check,

get device handler is unsupported

Solution:

Get device handler after I2C initialization

Requirement description:

Solution:

[Verified Cases]

Build Pass: Linux

Test Pass: Node-MCU

**活动福利**

一等奖：按照积分排名，第一名获得华为手表一个， 价值2000元左右

二等奖：按照积分排名，第二名获得Apple AirPods 耳机一个，价值1000元左右

三等奖：按照积分排名，第三名获得机械键盘一个，价值500元左右

参与奖：参与灭虫活动，且提交Bug有效，即可获得耳机一个，价值40元左右

**点击链接报名并开始准备起来吧**

[https://developer.aliyun.com/learning/topic/team/aliosthings/1](https://developer.aliyun.com/learning/topic/team/aliosthings/1)

**Comment by jinliangli** [comment]
还等什么， 抓紧参与吧！！

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
