### ISSUE TITLE
haas100开发板连接Wi-Fi总是断开连接然后快速重连

### ISSUE THREAD

**Issue by duanshuai007** [alibaba/AliOS-Things#1354]
连接Wi-Fi的时候非常频繁的断开连接，然后又快速的重新连上。

**Comment by qisheng-seu** [comment]
亲，您可以按照以下步骤排查下，
1、确认天线是否正确连接。
2、CLI中敲入 aos_mac WIFI 命令查询下HaaS100的wifi mac地址是否正确设置，您也可以通过路由器端查询连接上的HaaS100的mac地址是否合法。
3、确认HaaS100和路由器的距离是否在5米以内，太远的距离可以导致wifi连接不稳定。
![image](https://user-images.githubusercontent.com/59914082/155049682-a2f41f1c-a23f-4d61-85a4-acba3fcb0e87.png)

**Comment by duanshuai007** [comment]
1，2，3都分别确认了，没有问题。
但还是会出现掉线的情况。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by duanshuai007** [comment]
人工支持

**Comment by qisheng-seu** [comment]
亲，针对您的问题，我们已经紧急请求芯片合作厂商帮忙一起排查。现在需要您辛苦帮忙提供问题全程的串口日志，谢谢！！

**Comment by duanshuai007** [comment]
4256775/cw1200_bh | [WSM] Issue unjoin command (RX).

  4256776/net_wq | [STA] Unjoin.

  4256776/net_wq | wlan0: deauthenticated from 0x2005a21cM (Reason: 3)

  4256776/net_wq | ieee80211_set_disassoc 1 0

  4256779/net_wq | cw1200_bss_info_changed=0x2000 hw_priv:0x200394c0 priv:0x2003a208

  4256779/net_wq | [STA] Freq 2437 (wsm ch: 6).

  4256779/net_wq | cw1200_bss_info_changed=0x109f hw_priv:0x200394c0 priv:0x2003a208

  4256779/net_wq | [STA] BSS_CHANGED_ARP_FILTER enabled: 0, cnt: 1

  4256779/net_wq | BSS_CHANGED_ASSOC.

  4256779/net_wq | [STA] Slot time :20 us.

  4256779/net_wq | [CQM] RSSI threshold subscribe: 0 +- 0

  4256779/net_wq | [CQM] Beacon loss subscribe: 0

  4256779/net_wq | [CQM] TX failure subscribe: 0

  4256780/net_wq | cw1200_bss_info_changed=0x4000 hw_priv:0x200394c0 priv:0x2003a208

  4256780/net_wq | ignore IEEE80211_CONF_CHANGE_MONITOR (0) IEEE80211_CONF_CHANGE_IDLE (1)

  4256780/net_wq | nl80211_send_deauth

  4256780/net_wq | bwifi send event, id:3
  4256780/wifi_even | [WIFI] status CONNECTED, event 3
  4256780/wifi_even | disconnected from AP
  4256780/wifi_even | on_wifi_disconnect event_id:3
  4256780/wifi_even | wifi disconnected (reason=3, locally_generated=0)
  4256780/wifi_even | [WIFI] change status:CONNECTED->IDLE
[4259.567]<E>WIFI_SERVICE wifi_connect_failed_cb:300 err=4124

[4259.572]<E>NETMGR_CONN netmgr_conn_state_change:188 old state=5 new state=6

[4259.573]<E>NETMGR_CONN conn_failed:144 wrong state=5

---> wifi disconnect
---> wifi disconnect
01 06 20 0f a0 00 a0 00 00 00 00 00 00 00 00 00 00 07 00 
04 0e 04 05 06 20 00 
01 08 20 20 14 03 03 0f ff 07 09 7a 79 63 75 62 65 07 ff 2c 16 bd d0 12 a6 00 00 00 00 00 00 00 00 00 00 00 
04 0e 04 05 08 20 00 
01 09 20 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
04 0e 04 05 09 20 00 
01 0a 20 01 01 
04 0e 04 05 0a 20 00 
---- wifi state = 1
[4264.575]<E>WIFI_SERVICE get_wifi_config:1111 open /data/temp/temp.conf failed:No such file or directory

[4264.577]<E>WIFI_SERVICE ssid_contain_chinese_check:2191 Error: app ssid is NULL!

[4264.577]<E>WIFI_SERVICE netmgr_wifi_connect:2395 no config found

  4261789/m_wifi_ta | Scan for specific SSID Frog
  4261789/m_wifi_ta | [WIFI] change status:IDLE->SCANNING
  4261789/m_wifi_ta | nl80211: request->n_ssids=1, request->n_channels=13
  4261789/m_wifi_ta | cw1200_bss_info_changed=0x4000 hw_priv:0x200394c0 priv:0x2003a208

  4261789/m_wifi_ta | ignore IEEE80211_CONF_CHANGE_MONITOR (0) IEEE80211_CONF_CHANG  4261947/net_taskl | ieee80211_scan_rx: find qualified SSID in ProbeResp (2437,"Frog",-30,"80:8f:1d:e6:6a:4c")
  4261948/net_taskl | [SCAN] Cancel scan in progress

  4261948/cw1200_bh | cw1200_scan_complete_cb status:0
  4261948/net_wq | [SCAN] Scan canceled.

  4261948/net_wq | cw1200_bss_info_changed=0x4000 hw_priv:0x200394c0 priv:0x2003a208

  4261948/net_wq | ignore IEEE80211_CONF_CHANGE_MONITOR (0) IEEE80211_CONF_CHANGE_IDLE (1)

  4261948/net_wq | scan result0:(2437,"Frog",-33,"80:8f:1d:ef:f1:21")
  4261948/net_wq | scan result1:(2437,"Frog",-30,"80:8f:1d:e6:6a:4c")
  4261948/net_wq | bwifi send event, id:0
  4261949/wifi_even | [WIFI] status SCANNING, event 0
  4261949/wifi_even | scan complete, status:2
  4261949/m_wifi_ta | [WIFI] change status:SCANNING->IDLE
  4261949/m_wifi_ta | scan complete, scan result 2
  4261949/m_wifi_ta | wpa_interface_get_scan_result, count:2
  4261949/m_wifi_ta | haas start scan:0[4264.738]<E>WIFI_SERVICE wifi_start_sta:2173 start wifi

  4261949/wifi_conn | connect to ssid: Frog
  4261949/wifi_conn | bwifi_add_config ssid:Frog, passwd:FrogsHealth@1, hidden:0
  4261950/wifi_conn | eap_peer_config_free 37.
  4261950/wifi_conn | _bwifi_connect
  4261950/wifi_conn | [WIFI] change status:IDLE->IDLE
  4261950/wifi_conn | [WIFI] change status:IDLE->CONNECTING
  4261950/wifi_conn | wpa_supplicant_ssid_bss_match 861.
  4261950/wifi_conn | wpas_select_network_from_last_scan 1720.
  4261950/wifi_conn | bwifi send event, id:1
  4261950/wifi_even | [WIFI] status CONNECTING, event 1
  4261950/wifi_even | wifi connecting in state 0
  4261950/wifi_even | on_wifi_connect event_id:0
  4261950/wifi_conn | eapol_sm_step 920 0xc09fb59.
  4261950/wifi_conn | eap_peer_sm_step 1485.
  4261950/wifi_conn | eapol_sm_step 920 0xc09fb63.
  4261950/wifi_conn | eap_peer_sm_step 1485.
  4261950/wifi_conn | eapol_sm_step 920 0xc09fbc9.
  4261950/wifi_conn | eap_peer_sm_step 1485.
  4261951/wifi_conn | wlan0: add AUTH work

  4261951/net_wq | cw1200_bss_info_changed=0x4000 hw_priv:0x200394c0 priv:0x2003a208

  4261951/net_wq | ignore IEEE80211_CONF_CHANGE_MONITOR (0) IEEE80211_CONF_CHANGE_IDLE (1)

  4261951/net_wq | ieee80211_recalc_channel 0x34000a0c 6 6.
  4261951/net_wq | wlan0: authenticate with 80:8f:1d:e6:6a:4c (try 1)

  4261951/cw1200_bh | [WSM] Issue join command.

  4261951/net_wq | [STA] Join DTIM: 1, interval: 100

  4261951/net_wq | cw1200_disable_listening if_id:0.
  4262045/net_wq | wlan0: RX Auth from 0x20059f1eM (alg=0 transact=2 status=0)

  4262045/net_wq | wlan0: authenticated

  4262045/net_wq | nl80211_send_rx_auth bssid 80:8f:1d:e6:6a:4c

  4262045/net_wq | bwifi send event, id:1
  4262045/net_wq | wlan0: add ASSOC_BEACON_WAIT work

  4262045/net_wq | nl80211_send_rx_auth done

  4262045/net_wq | wlan0: waiting for beacon from 0x2005a14dM for 1000ms

  4262045/wifi_even | [WIFI] status CONNECTING, event 1
  4262045/wifi_even | wifi connecting in state 3
  4262045/wifi_even | on_wifi_connect event_id:0
  4262139/net_wq | wlan0: beacon received

  4262139/net_wq | wlan0: associate with 0x2005a14dM (try 1)

  4262150/net_wq | wlan0: RX AssocResp from 0x20059f1eM (capab=0x1411 status=0 aid=2)

  4262150/net_wq | wlan0: associated

  4262153/net_wq | cw1200_bss_info_changed=0x2000 hw_priv:0x200394c0 priv:0x2003a208

  4262153/net_wq | ieee80211_recalc_channel 0x34000a0c 6 6.
  4262153/net_wq | [STA] Freq 2437 (wsm ch: 6).

  4262153/net_wq | cw1200_bss_info_changed=0xf9 hw_priv:0x200394c0 priv:0x2003a208

  4262153/net_wq | BSS_CHANGED_BEACON_INT

  4262153/net_wq | BSS_CHANGED_ASSOC.

  4262153/net_wq | [STA] Non-GF STA present

  4262153/net_wq | [STA] DTIM 1, interval: 100

  4262153/net_wq | [STA] Preamble: 0, Greenfield: 0, Aid: 2, Rates: 0x00003FCF, Basic: 0x0000000F

  4262155/net_wq | wsm_set_pm 0x0.
  4262155/cw1200_bh | wsm_set_pm_indication.
  4262158/net_wq | [STA] Slot time :9 us.

  4262158/net_wq | [CQM] RSSI threshold subscribe: 0 +- 0

  4262158/net_wq | [CQM] Beacon loss subscribe: 0

  4262158/net_wq | [CQM] TX failure subscribe: 0

  4262158/net_wq | nl80211_send_rx_assoc bssid 80:8f:1d:e6:6a:4c

  4262158/net_wq | bwifi send event, id:1
  4262158/net_wq | eapol_sm_step 920 0xc0b4611.
  4262158/net_wq | EAPOL: SUPP_PAE entering state DISCONNECTED
  4262158/net_wq | EAPOL: SUPP_BE entering state INITIALIZE
  4262158/net_wq | eap_peer_sm_step 1485.
  4262158/net_wq | eap_peer_sm_step 1485.
  4262158/net_wq | eapol_sm_step 920 0xc0b461b.
  4262158/net_wq | eap_peer_sm_step 1485.
  4262158/net_wq | eapol_sm_step 920 0xc0b4879.
  4262158/net_wq | eap_peer_sm_step 1485.
  4262158/net_wq | eapol_sm_step 920 0xc0b4633.
  4262158/net_wq | EAPOL: SUPP_PAE entering state CONNECTING
  4262159/net_wq | EAPOL: SUPP_BE entering state IDLE
  4262159/net_wq | eap_peer_sm_step 1485.
  4262159/net_wq | eap_peer_sm_step 1485.
  4262159/net_wq | nl80211_send_rx_assoc done

  4262159/wifi_even | [WIFI] status CONNECTING, event 1
  4262159/wifi_even | wifi connecting in state 6
  4262159/wifi_even | on_wifi_connect event_id:0
  4262168/net_taskl | RX EAPOL len:99.
  4262168/net_taskl | eapol_sm_step 920 0xc0b1177.
  4262168/net_taskl | eap_peer_sm_step 1485.
  4262168/net_taskl | bwifi send event, id:1
  4262169/net_taskl | nl80211_send_eapol st=0 

  4262169/wifi_even | [WIFI] status CONNECTING, event 1
  4262169/wifi_even | wifi connecting in state 7
  4262169/wifi_even | on_wifi_connect event_id:0
  4262176/net_taskl | RX EAPOL len:155.
  4262176/net_taskl | eapol_sm_step 920 0xc0b1177.
  4262176/net_taskl | eap_peer_sm_step 1485.
  4262177/net_taskl | nl80211_send_eapol st=0 

  4262177/net_taskl | nl80211_new_key 1 0 0x3403000a.
  4262177/net_taskl | eapol_sm_step 920 0xc0b1a69.
  4262177/net_taskl | eap_peer_sm_step 1485.
  4262178/net_taskl | bwifi send event, id:1
  4262178/net_taskl | nl80211_new_key 0 1 0x0.
  4262178/net_taskl | bwifi send event, id:2
  4262178/net_taskl | eapol_sm_step 920 0xc0b0c81.
  4262178/net_taskl | eap_peer_sm_step 1485.
  4262178/net_taskl | eapol_sm_step 920 0xc0b0cb7.
  4262178/net_taskl | EAPOL: SUPP_PAE entering state AUTHENTICATING
  4262178/net_taskl | EAPOL: SUPP_BE entering state SUCCESS
  4262178/net_taskl | eap_peer_sm_step 1485.
  4262178/net_taskl | EAP: EAP entering state DISABLED
  4262178/net_taskl | eap_peer_sm_step 1485.
  4262178/net_taskl | EAPOL: SUPP_PAE entering state AUTHENTICATED
  4262178/net_taskl | EAPOL: SUPP_BE entering state IDLE
  4262178/net_taskl | eap_peer_sm_step 1485.
  4262178/net_taskl | eap_peer_sm_step 1485.
  4262178/wifi_even | [WIFI] status CONNECTING, event 1
  4262178/wifi_even | wifi connecting in state 9
  4262179/wifi_even | on_wifi_connect event_id:0
  4262179/wifi_even | [WIFI] status CONNECTING, event 2
  4262179/wifi_even | wifi mac connected to Frog
  4262179/wifi_even | on_wifi_connect event_id:1
  4262179/wifi_even | [WIFI] change status:CONNECTING->CONNECTED
  4262179/wifi_even | wsm_epta_cmd 60000 40000 3.
  4262179/wifi_even | wsm_epta_cmd 60000 40000 0.
  4262179/wifi_even | Set PS mode 0
  4262179/wifi_even | nl80211_set_power_save disabled
  4262179/wifi_even | config_dpd, ch=6
  4262180/wifi_conn | connect complete, success
  4262244/tcpip_thr | set ip: 192.168.200.71
  4262244/tcpip_thr | set mask: 255.255.255.0
  4262244/tcpip_thr | set gw: 192.168.200.252
  4262244/tcpip_thr | cw1200_bss_info_changed=0x1000 hw_priv:0x200394c0 priv:0x2003a208

  4262244/tcpip_thr | [STA] BSS_CHANGED_ARP_FILTER enabled: 1, cnt: 1

  4262244/tcpip_thr | wsm_epta_cmd 60000 40000 0.
---> wifi dhcp success

**Comment by duanshuai007** [comment]
这部分日志是在正常工作中，然后网络断开，再到重新连接到网络的部分日志信息

**Comment by qisheng-seu** [comment]
亲，感谢您的日志反馈，我们工程师正在紧锣密鼓排查中，会尽快给您回复。谢谢

**Comment by qisheng-seu** [comment]
从您提供的日志看，附近存在2个名为Frog的路由器，请问这两个路由器的加密方式和password都一样吗？看起来和2个同名路由器有关。可以尝试换个不同名字的路由器试试。
4261948/net_wq | scan result0:(2437,"Frog",-33,"80:8f:1d:ef:f1:21")
4261948/net_wq | scan result1:(2437,"Frog",-30,"80:8f:1d:e6:6a:4c")

**Comment by duanshuai007** [comment]
是的，存在4个同名路由器。但是设备已经连接上路由器了，为什么会断开呢，源码会将这个问题视为一个bug并进行修复吗？

**Comment by qisheng-seu** [comment]
看日志是路由器端把设备踢掉的。要继续排查的话需要您提供以下几点信息，
1、换个路由器名字是否还会出现该问题？
2、4个同名路由器的加密方式和密码是否都是一样的？

**Comment by duanshuai007** [comment]
好的，我去试一试。

**Comment by duanshuai007** [comment]
测试了一个多小时。连接我手机开启的热点没掉线。
那这个问题也还是存在的啊，在实际环境中还是有可能出现多个路由器是同样的wifi名和密码的。
最主要是我现在环境下用esp32就没有这个问题，只有haas100开发板有这个问题。

**Comment by qisheng-seu** [comment]
感谢您的反馈。我们内部排查下，晚点给您回复。

**Comment by qisheng-seu** [comment]
请帮忙提供下路由器的型号，我们看下是否有相同路由器复现下？另外你那边是否可以抓wifi air sniffer日志 ？

**Comment by duanshuai007** [comment]
路由器是TP-LINK的TL-WDR7650千兆易展版（AC1900双频千兆无线路由器，在范围内有4个这样的路由器，都具有相同的SSID和PSK）,我这里看不到路由器端的日志。

**Comment by qisheng-seu** [comment]
好的。我将信息反馈给合作方，有解决方案时会第一时间通知您。谢谢

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
