### ISSUE TITLE
部署一直失败

### ISSUE THREAD

**Issue by wenkaitiantian** [alibaba/AliOS-Things#1355]
部署一直失败

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by qisheng-seu** [comment]
亲，为了更高效的让技术工程师排查问题，辛苦帮忙详细点描述下您遇到的问题，以及问题日志或者现场截图。谢谢！！

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
