### ISSUE TITLE
[Bug Report] The link is invalid

### ISSUE THREAD

**Issue by junchengliu** [alibaba/AliOS-Things#1358]
on the page of https://github.com/alibaba/AliOS-Things/tree/master/haas_lib_bundles/python, some link is invalid

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by skylarCai** [comment]
https://github.com/alibaba/AliOS-Things/pull/1405  already fix this problem
