### ISSUE TITLE
esp32 固件下载不了

### ISSUE THREAD

**Issue by rualdeng** [alibaba/AliOS-Things#1362]
https://haas.iot.aliyun.com/haasapi/index.html#/Python/docs/zh-CN/startup/ESP32_startup  esp32 固件列表点击下载不了。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by yong171966** [comment]
https://haas.iot.aliyun.com/haasapi/index.html?spm=a2cpu.b16145223.0.0.595660b1B2CgrL#/Python/docs/zh-CN/startup/ESP32_startup
![image](https://user-images.githubusercontent.com/100329317/155467299-2352f02f-42d9-4ae6-8a41-fdbd840c8d33.png)
验证完成，是可以下载的亲！

**Comment by skylarCai** [comment]
人工支持

**Comment by zy20220224** [comment]
> https://haas.iot.aliyun.com/haasapi/index.html#/Python/docs/zh-CN/startup/ESP32_startup esp32 固件列表点击下载不了。

刚才验证可以正常下载，你在尝试一下。

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
