### ISSUE TITLE
pt_engine_demo solution下，执行 aos make -b haaseduk1 失败

### ISSUE THREAD

**Issue by zy20220224** [alibaba/AliOS-Things#1364]
![image](https://user-images.githubusercontent.com/100339184/155476106-31a0e9d7-ace5-42e6-b175-443750307afa.png)

**Comment by skylarCai** [comment]
请参考  https://github.com/alibaba/AliOS-Things/pull/1361

该问题已解决

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
