### ISSUE TITLE
乐鑫蓝牙配网参数错误

### ISSUE THREAD

**Issue by rualdeng** [alibaba/AliOS-Things#1368]
[bleNetConfig - 蓝牙配网](https://haas.iot.aliyun.com/haasapi/index.html#/Python/docs/zh-CN/haas_extended_api/bleNetConfig?id=blenetconfig-%e8%93%9d%e7%89%99%e9%85%8d%e7%bd%91)

while(bleNetConfig.getWiFiStatus() != bleNetConfig.WIFI_GOT_IP):
报错：
AttributeError:'module' object has no attribute 'WIFI_GOT_IP'

同时 [audio - 音频系统模块](https://haas.iot.aliyun.com/haasapi/index.html#/Python/docs/zh-CN/haas_extended_api/audio?id=audio-%e9%9f%b3%e9%a2%91%e7%b3%bb%e7%bb%9f%e6%a8%a1%e5%9d%97) ，能否把录音这块的功能代码补上，需要测试这块的功能，谢谢！

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by jiyong3998** [comment]
请问是哪个固件呢？

**Comment by ElliottSeer** [comment]
蓝牙配网的问题可以先参照这个patch 近期会fix
https://gitee.com/ElliottSeer/AliOS-Things/blob/master/components/py_engine/adapter/esp32/fs/lib/bleNetConfig.py
把这个文件放在项目里就可以了

**Comment by YiluMao** [comment]
@rualdeng 请问您的问题有没有解决，如果已解决，请关闭这个issue

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
