### ISSUE TITLE
windows用户名含有空格导致aos tool 运行异常  和 解决办法

### ISSUE THREAD

**Issue by victorstone123** [alibaba/AliOS-Things#1373]
aos tools 通过vscode插件的方式默认安装在 c:\Users\<your name>\.vscode\extensions.

如果用户名带有空格，会导致aos tools 运行异常。

解决办法（步骤）： 

1. 将c:\Users\<你的用户名>\.vscode\extensions 文件夹下所有文件和文件夹拷贝到不含空格的新文件夹： <新不带空格文件夹>\extensions.
2. 右键vscode 图标 ->打开文件位置： 找到vscode 启动快捷方式
3. 右键快捷方式 -> 目标
4. 在目标后面添加：  --extensions-dir  <新不带空格文件夹>\extensions

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
