### ISSUE TITLE
aliosthings的ota差分固件生成工具支持非aliosthings系统吗？

### ISSUE THREAD

**Issue by jweihsz** [alibaba/AliOS-Things#1377]
问题描述：
1.目前设备上没有跑rtos系统，请问下使用aliosthings提供的差分包生产工具( https://github.com/alibaba/AliOS-Things/wiki/OTA-Diff-Tools--User-Guide?spm=a2c4g.11186623.0.0.4c2b292cmVQDx7 )生成的差分固件，支持在非aliosthings中使用吗？

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by yanxiaoyong-ch** [comment]
差分工具， diff和patch算法匹配即可，不区分镜像得

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
