### ISSUE TITLE
[Feature Request]: how to operate w25xx with driver/SPI

### ISSUE THREAD

**Issue by sopadilla** [alibaba/AliOS-Things#1384]
### Contact Details

liangyinhao44@163.com

### What do you want?

how can I operate w25qxx with driver/SPI interfaces in haas2.0?
i found that when i try to communicate to w25qxx with existing apis，it doesn't work。

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by wuxn9999** [comment]
请问您使用的是哪一种硬件？
使用的是C语言SPI API还是Python轻应用的SPI API？

**Comment by sopadilla** [comment]
我用的是python轻应用的haas2.0的api接口

**Comment by wuxn9999** [comment]
我们这里有SPI的Python API文档。[https://haas.iot.aliyun.com/haasapi/index.html#/Python/docs/zh-CN/haas_extended_api/driver/spi](url)
您可以对照w25qxx的手册，通过SPI API来操作flash。

**Comment by wuxn9999** [comment]
我们这里有SPI的[Python API文档](https://haas.iot.aliyun.com/haasapi/index.html#/Python/docs/zh-CN/haas_extended_api/driver/spi)。
您可以对照w25qxx的手册，通过SPI API来操作flash。

**Comment by wuxn9999** [comment]
另外您用的是哪一款开发板？您现在操作w25qxx的代码方便发一下吗？

**Comment by YiluMao** [comment]
@sopadilla 请问您的问题有没有解决，如果有解决，请关闭issue，多谢

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
