### ISSUE TITLE
[Feature Request]: how to calibrate device time

### ISSUE THREAD

**Issue by sopadilla** [alibaba/AliOS-Things#1385]
### Contact Details

liangyinhao44@163.com

### What do you want?

using aliyunIoT can get correct time，but how can i calibrate dvice time using api 2.0？

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
You can use the following API:
https://haas.iot.aliyun.com/haasapi/index.html?spm=a2cpu.b16145223.0.0.595660b1bLS6u0#/Python/docs/zh-CN/standard_api/utime

**Comment by YiluMao** [comment]
@sopadilla 请问您的问题有没有被解决，如果已解决，请关闭issue

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
