### ISSUE TITLE
JS轻应用插件没有加载完全

### ISSUE THREAD

**Issue by bawkss** [alibaba/AliOS-Things#1402]
今天打开VsCode建立Ec600SDemo后，状态栏没有出现闪电图标和串口图标。任然只有快速开始图标。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by bawkss** [comment]
您好，我已经收到您的邮件，我将在查看后尽快给您回复.此为系统邮件，请勿回复 © 1998 - 2014 Tencent Inc. All Rights Reserved

**Comment by bawkss** [comment]
人工支持

**Comment by bawkss** [comment]
降级到1.0.68后正常

**Comment by qisheng-seu** [comment]
亲，新1.0.70 版本的HaaS Studio中的快速开始暂时不支持HaaS-JS开发，新的方案正在优化中。请回退到旧版本（例 1.0.68）使用HaaS-JS开发，谢谢。

**Comment by bawkss** [comment]
不是快速开始没有，能新建项目，但是下面状态栏没有闪电图标，就是烧录，编译，串口那一条图标没有不方便。

**Comment by bawkss** [comment]
@qisheng-seu

**Comment by qisheng-seu** [comment]
嗯，烧录，编译，串口这部分在新版本haas studio中都下线了，新版本正在紧急开发中。

**Comment by bawkss** [comment]
其实不要这个功能也可以，加一个电脑上调试，自己调试完成再手动烧录

**Comment by bawkss** [comment]
希望早日维护完成。

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
