### ISSUE TITLE
请求人工支持给一个haas600的tft屏幕Demo程序

### ISSUE THREAD

**Issue by bawkss** [alibaba/AliOS-Things#1411]
如题，显示一段文字或者图片的Demo就行，谢谢大佬。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
稍等，我们尽快处理

**Comment by bawkss** [comment]
谢谢大佬

**Comment by YiluMao** [comment]
确认了一下，我们目前还没有支持这个
您可以自己试试，需要有具体的问题，我们可以支持您
您也可以把您的代码最终开源出来，贡献给社区

**Comment by bawkss** [comment]
好的。

**Comment by bawkss** [comment]
已解决
