### ISSUE TITLE
[Feature Request]: inksdk_demo 编译报错

### ISSUE THREAD

**Issue by frankshen2020** [alibaba/AliOS-Things#1415]
### Contact Details

shenchendky@163.com

### What do you want?

collect2.exe: error: ld returned 1 exit status
scons: *** [out\test_demo\aos.elf] Error 1
scons: building terminated because of errors.
make: *** [all] Error 2
Build takes 0 Minutes 16 Seconds.

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by frankshen2020** [comment]
人工支持

**Comment by YiluMao** [comment]
请问您如下是选择的什么？
<img width="690" alt="image" src="https://user-images.githubusercontent.com/61785395/158044787-6fe86828-e9c6-4887-8cb3-f325863baa74.png">

**Comment by YiluMao** [comment]
测试了HaaS100的硬件，wifi连接阿里云的解决方案
编译没有遇到问题

申请关闭本issue

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
