### ISSUE TITLE
[Feature Request]: 能做一个土壤湿度传感器的例子吗？

### ISSUE THREAD

**Issue by 84788951** [alibaba/AliOS-Things#1418]
### Contact Details

84788951@qq.com

### What do you want?

![image](https://user-images.githubusercontent.com/94699143/158151050-0faa9a77-099d-4369-a82a-68733a30234f.png)
传感器如上图。
能麻烦提供上图土壤湿度的例子吗？esp32 Python轻应用的。

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by wstong999** [comment]
土壤湿度的案例正在开发中，预计月底可以上线，到时请关注（https://haas.iot.aliyun.com/solution/hardware）

**Comment by YiluMao** [comment]
@84788951 请问您的问题有没有被解决，如果已解决，请关闭issue

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
