### ISSUE TITLE
[Bug Report]: spelling error for modbus part 

### ISSUE THREAD

**Issue by yong171966** [alibaba/AliOS-Things#1419]
### What happened?

https://haas.iot.aliyun.com/haasapi/index.html?spm=a2cpu.b16145223.0.0.595660b10zzFt5#/Python/docs/zh-CN/haas_extended_api/modbus

![image](https://user-images.githubusercontent.com/100329317/158372168-dda7c5f2-f7cc-4eb4-8fd8-c8df5fa16c1b.png)

### Version

rel_3.3.0 (Main)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by ethanlcz** [comment]
> ### Contact Details
> _No response_
> 
> ### What happened?
> https://haas.iot.aliyun.com/haasapi/index.html?spm=a2cpu.b16145223.0.0.595660b10zzFt5#/Python/docs/zh-CN/haas_extended_api/modbus
> 
> ![image](https://user-images.githubusercontent.com/100329317/158372168-dda7c5f2-f7cc-4eb4-8fd8-c8df5fa16c1b.png)
> 
> ### Version
> rel_3.3.0 (Main)
> 
> ### What soultions are you seeing the problem on?
> _No response_
> 
> ### Relevant log output
> _No response_

官网已经解决此问题。

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
