### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by coonyshu** [alibaba/AliOS-Things#1424]
### Contact Details

coony@njdys.com

### What do you want?

看到官方haas100可以外接4G模块，具有很大的实用性，目前python轻应用里面不能支持，希望尽快得到支持。我们python项目开发接近尾声，因为项目在国外，目前所有的haas 开发板都是 4g cat1的，无法支持，haas100是目前看得见的、唯一的希望。

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
我们内部讨论下，会尽快回复您

**Comment by YiluMao** [comment]
这个目前是不支持的，建议您可以试着自己添加下
如果遇到问题，可以来我们issue社区提问获取支持

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
