### ISSUE TITLE
[Feature Request]: 可以发布一个Haas600基于UART2TTL传输的摄像头demo吗

### ISSUE THREAD

**Issue by FENGXIAOGITHUB** [alibaba/AliOS-Things#1427]
### Contact Details

245318464@qq.com

### What do you want?

feature request
希望可以发布一个基于Haas600利用串口通讯实现摄像头拍照功能的demo

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by FENGXIAOGITHUB** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YiluMao** [comment]
您好，目前确实没有这个demo
短期也没有计划做这个
如果您有兴趣，可以考虑贡献一个案例到社区
如果需要技术支持，可以提issue获取

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
