### ISSUE TITLE
haas200 更新固件

### ISSUE THREAD

**Issue by xyjand** [alibaba/AliOS-Things#1430]
### Contact Details

xyjand@yeah.net

### What do you want?

选择haas200，C, 轻应用示例，准备更新主板的固件，在编译阶段就有报错：
	change dir to E:\PROJECT\haas\test\t5_c\solutions\test_demo. 
	Build Solution by haas200 
	scons: Reading SConscript files ...
	There is no depend component `curl` found! 
	========
	[{'curl': 'master ? <!CHIP_HAAS1000>'}]
	1
	Reverse value
	lost component check : need install this component
	Try to install missing component...
	Start to install components... 
	Can't find component curl. 
	No component need to install. 
	There is no depend component `curl` found! 
	========
	[{'curl': 'master ? <!CHIP_HAAS1000>'}]
	1
	Reverse value
	lost component check : need install this component
	Try to install missing component...
	Start to install components... 
	Can't find component curl. 
	No component need to install. 
	Please make sure  [{'curl': 'master ? <!CHIP_HAAS1000>'}] are valid, and try it again. 
	make: *** [all] Error -1
	Build takes 0 Minutes 4 Seconds.

	终端将被任务重用，按任意键关闭。

### Version

rel_3.3.0 (Main)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by jinliangli** [comment]
您好，

这个问题是components/oss组件依赖curl组件， 但是HaaS Studio没有正确解析依赖自动下载curl组件。 我们会查看解决。 

临时解决方法： 执行命令在components组件下“git clone https://gitee.com/alios-things/curl.git”下载curl到components/curl。

**Comment by YiluMao** [comment]
@xyjand 请问您的问题有没有被解决，如果已解决，请关闭issue

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
