### ISSUE TITLE
[Feature Request]: OSS上传file的接口有变更，需要有自定义路径传参

### ISSUE THREAD

**Issue by rualdeng** [alibaba/AliOS-Things#1434]
### Contact Details

rualdeng@163.com

### What do you want?

之前的上传file的接口是 ret = oss.uploadFile(keyid,keysecret,endpoint,bucketname,objectname,filename) objectname为oss的自定义路径，新接口为file = oss.uploadFile(ACCESS_KEY, ACCESS_SECRET, OSS_ENDPOINT, OSS_BUCKET, FILENAME)，没有objectname自定义路径了，很不方面。需要自定义路径传参。谢谢！

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by yong171966** [comment]
我们内部会讨论这个接口的，应该可以更新的

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
