### ISSUE TITLE
[Feature Request]: python轻应用OSS上传的时间报错问题

### ISSUE THREAD

**Issue by rualdeng** [alibaba/AliOS-Things#1436]
### Contact Details

rualdeng@163.com

### What do you want?

PutObject fail,code:RequestTimeTooSkewed,message:The difference between the request time and the current time is too large.,requestId:62343B2F9849B434365DD543    
python轻应用 sntp.setTime() 返回0，还是报同样的错。要怎么处理呢？多台机器测试同样的问题。
应该是C底层的问题，帮忙解决一下。谢谢

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by yong171966** [comment]
已经指导开发者怎么处理了，同时开发者也已经提及PR：https://github.com/alibaba/AliOS-Things/pull/1437

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
