### ISSUE TITLE
[Feature Request]: 求一份haas edu k1的蜂鸣器的python文件

### ISSUE THREAD

**Issue by Ryze-b** [alibaba/AliOS-Things#1443]
### Contact Details

2682394086@qq.com

### What do you want?

![image](https://user-images.githubusercontent.com/71574578/159676484-f5ab7c50-a69f-4a90-b99b-a1b4b04a97e3.png)
包含这个函数的文件，谢谢大佬！

### Version

master (Default)

**Comment by sunlrain** [comment]
@Ryze-b - 感谢您提出的需求，蜂鸣器相关的API支持正在开发测试中，预计将在4月10号左右开放出来，敬请关注哦

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
