### ISSUE TITLE
haas轻应用文档错误

### ISSUE THREAD

**Issue by niiutuut** [alibaba/AliOS-Things#1445]
### What happened?

haas轻应用 - Driver - 系统外设库 - PWM - 脉宽调制功能接口 - open - 打开PWM
文档表格格式错误
![image](https://user-images.githubusercontent.com/100279373/159826662-c128d870-d8ac-4559-bced-40efb232fc65.png)

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by ethanlcz** [comment]
> ### Contact Details
> _No response_
> 
> ### What happened?
> haas轻应用 - Driver - 系统外设库 - PWM - 脉宽调制功能接口 - open - 打开PWM 文档表格格式错误 ![image](https://user-images.githubusercontent.com/100279373/159826662-c128d870-d8ac-4559-bced-40efb232fc65.png)
> 
> ### Version
> master (Default)
> 
> ### What soultions are you seeing the problem on?
> _No response_
> 
> ### Relevant log output
> _No response_

谢谢帮忙指正错误，我们预计今天把这个问题修复掉并上线官网。

**Comment by ethanlcz** [comment]
> ### Contact Details
> _No response_
> 
> ### What happened?
> haas轻应用 - Driver - 系统外设库 - PWM - 脉宽调制功能接口 - open - 打开PWM 文档表格格式错误 ![image](https://user-images.githubusercontent.com/100279373/159826662-c128d870-d8ac-4559-bced-40efb232fc65.png)
> 
> ### Version
> master (Default)
> 
> ### What soultions are you seeing the problem on?
> _No response_
> 
> ### Relevant log output
> _No response_

您好，该问题已经修复。

**Comment by ethanlcz** [comment]
![image](https://user-images.githubusercontent.com/78590662/159828696-dc33deb8-b0ac-4eec-8f54-a066e8b88a01.png)

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
