### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by krisaaaaa** [alibaba/AliOS-Things#1455]
### What happened?

A bug happened!
运行环境:win10 vscode
固件版本:haas edu k1 python轻应用

### Version

master (Default)

### What soultions are you seeing the problem on?

haas_dev_demo, py_engine_demo

### Relevant log output

```shell
部署运行的时候这个怎么解决呢？haas edu k1 温湿度上云。
............
4304/main_task | csi_flash_init:224 done.
4308/main_task | sd init failed!
Welcome to AliOS Things
amp shakehand begin...
get_wifi_config:1111 open /data/temp/temp.conf failed:No such file or directory
get_wifi_config:1111 open /data/wifi.conf failed:No such file or directory
reconnect_task_handle:635 no config found
(ash:/data)#
```

**Comment by jinliangli** [comment]
get_wifi_config:1111 open /data/temp/temp.conf failed:No such file or directory
get_wifi_config:1111 open /data/wifi.conf failed:No such file or directory

这个报错只是说明该设备之前没有成功联网过，只需按照案例的文档说明填写正确的wifi的ssid和密码即可。 成功联网一次后，就不会再报这样的消息了。

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
