### ISSUE TITLE
M5需要recorder和SD卡挂载功能，怎么推进这件事？> > ### Contact Details

### ISSUE THREAD

**Issue by rualdeng** [alibaba/AliOS-Things#1460]
> > ### Contact Details
> > [rualdeng@163.com](mailto:rualdeng@163.com)
> > ### What do you want?
> > (https://haas.iot.aliyun.com/haasapi/index.html#/Python/docs/zh-CN/haas_extended_api/audio) 只有audio,没有recorder，需要一份完整的有关recorder,API的文档。可用在m5stack core2板上的。谢谢！
> > ### Version
> > master (Default)
> 
> 目前暂未支持录音功能，请问您是有什么场景下的具体需求吗？

我们现在做的产品需要录音功能，已经和python轻应用团队对接很久了。之前一直在做4G产品，那边有个小技术升级。WIFI版本我们选择以m5stack core2为开发板。基本的python业务逻辑已经做好了，APP也做好了。
还有需要SD挂载的功能。

_Originally posted by @rualdeng in https://github.com/alibaba/AliOS-Things/issues/1452#issuecomment-1077532684_

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by zy20220224** [comment]
m5stack已经支持sd卡了，你在sd卡这里有特别的需求吗？

**Comment by rualdeng** [comment]
> m5stack已经支持sd卡了，你在sd卡这里有特别的需求吗？

需要把文件写入SD卡，昨天查资料弄了一晚，还是挂不上。
axp = Axp192()
axp.setLDOVoltage(2,3300)
axp.setLDOEnable(2,True)
sdcard = SDCard(slot=2, sck=Pin(18), miso=Pin(38), mosi=Pin(23), cs=Pin(4), freq=40000000)
uos.mount(sdcard, '/sd')
print(uos.listdir('/sd'))

有挂载的案例么？

**Comment by rualdeng** [comment]
> m5stack已经支持sd卡了，你在sd卡这里有特别的需求吗？

麻烦提供一下python轻应用SD卡挂载案例。没有特别的要求，需要挂载SD和文件系统，写入文件。SDIO的协议版本来支持SD卡的容量，这个SPI以什么方式来支持SD的最大容量，这个板子最大能支持多大容量的卡，能否自行调节支持128G？

**Comment by zy20220224** [comment]
暂时没有提供sd卡挂在的接口，后续版本中会支持起来

**Comment by rualdeng** [comment]
> 

能否指导怎么弄，我可以自行修改C程序，自己编译。你们的后续版本比较慢，时间上来不急。

**Comment by yong171966** [comment]
Recorder已经支持并开源。

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
