### ISSUE TITLE
[Feature Request]: M5stack core2 SD卡挂载

### ISSUE THREAD

**Issue by rualdeng** [alibaba/AliOS-Things#1465]
### Contact Details

rualdeng@163.com

### What do you want?

M5Stack core2没有开放挂载SD卡接口，我们产品上必须要用，只有自己查资料去写。但还是遇到很多问题。
sdcard = SDCard(slot=2, sck=Pin(18), miso=Pin(38), mosi=Pin(23),  cs=Pin(4), freq=40000000)
uos.mount(sdcard, '/sd')
print(uos.listdir('/sd'))

也查了很多资料和试了很多方式，都是报OSError: [Errno 19] ENODEV。没有识别到卡。麻烦这边帮看下参数设置还有其它什么弄错的。

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by yong171966** [comment]
目前M5Stack Core2上SD卡的功能没有调试，你遇到的问题我们会紧急处理一下。
建议你先用文件系统的方式操作，直接将数据放到/data分区下，等SD卡功能完成后再切换到SD卡上。

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
