### ISSUE TITLE
首届AliOS Things灭虫活动圆满结束！

### ISSUE THREAD

**Issue by yong171966** [alibaba/AliOS-Things#1468]
@all

感谢各位同学们的支持与参与，我们首届AliOS Things灭虫活动圆满结束！
接下来就是激动人心的颁奖环节！根据本次活动的积分规则，我们统计出了所有参赛同学的积分并予以公示。
快来看看名单上是否有自己的名字吧！

![image](https://user-images.githubusercontent.com/100329317/161370650-5225785e-b95f-403f-a016-eddd701cd5b4.png)

【**注意**：我们的公示期为4月2日-4月5日，在此期间如果您有任何积分排名的问题都可以@管理员为您解答哦~】

公示期后，我们将按照积分排名发送奖品，再次感谢大家支持！[爱心]

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。
