### ISSUE TITLE
[Feature Request]: 麻烦能否加快集成PR

### ISSUE THREAD

**Issue by rualdeng** [alibaba/AliOS-Things#1474]
### Contact Details

rualdeng@163.com

### What do you want?

[feature request](https://github.com/alibaba/AliOS-Things/pull/1467)  能否加快审核这个PR进行集成，有这个业务需求，需要集成到项目中。谢谢！

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
我们尽快处理

**Comment by skylarCai** [comment]
已合入
