### ISSUE TITLE
[Feature Request]: Haas600 对步进电机驱动器控制步进电机的程序如何写？

### ISSUE THREAD

**Issue by xiaobaiyetianhao** [alibaba/AliOS-Things#1482]
### Contact Details

1060439317@qq.com

### What do you want?

haas600开发板对步进电机驱动器的js脚本程序应该如何写？比如用600来控制dm542从而驱动57电机。

### Version

rel_3.3.0 (Main)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by xiaobaiyetianhao** [comment]
人工支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 晚上7:30
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/AliOS-Things] [Feature Request]: Haas600 对步进电机驱动器控制步进电机的程序如何写？ (Issue #1482)





 感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统， 您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&amp;f=a2cre.b82925042) 如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by wstong999** [comment]
您好，步进电机请您参考https://haas.iot.aliyun.com/solution/detail/hardware?versionId=800C4A7B94BEA8CA00000001&dataId=800C4A7B94BEA8CA
另外咨询一下 您这个是什么项目，为啥选择dm542来驱动57电机

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
