### ISSUE TITLE
[Bug Report]: HaaS Studio v2.0.0 使用串口报错

### ISSUE THREAD

**Issue by ElliottSeer** [alibaba/AliOS-Things#1491]
### Contact Details

钉钉 92m_9lis6vzqt

### What happened?

A bug happened!
运行环境: windows
固件版本: HaaS Studio v2.0.0

![image](https://user-images.githubusercontent.com/40886115/163704683-86b1df84-2aac-4117-894f-2d80d1a7c9a9.png)

### Version

rel_3.3.0 (Main)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by senwangal** [comment]
从log来看是conda active失败，请提供下你的系统版本信息，

**Comment by senwangal** [comment]
这个操作是在什么情况下触发，部署运行还是点击串口？能否提供下相关的log

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
