### ISSUE TITLE
[Bug Report]: 在components/amp_adapter/platform/aos/network/aos_udp.c中调用inet_ntop没有返回值检查

### ISSUE THREAD

**Issue by YiluMao** [alibaba/AliOS-Things#1500]
### What happened?

A bug happened!

在components/amp_adapter/platform/aos/network/aos_udp.c中调用inet_ntop没有返回值检查

### Version

master (Default)

### What soultions are you seeing the problem on?

py_engine_demo

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by PiaoLingAl** [comment]
感谢您提出的宝贵问题,我们会评估后并解决！

**Comment by YiluMao** [comment]
相关patch已合入

**Comment by skylarCai** [comment]
Hi from GitHub CLI
