### ISSUE TITLE
[Bug Report]: 烧录python程序失败

### ISSUE THREAD

**Issue by Lingakg** [alibaba/AliOS-Things#1510]
### Contact Details

cwl_web@163.com

### What happened?

烧录时失败

运行环境:  nodemcu esp32 安信可板子，python程序
固件版本: v2.0.0
表现：不断打印以下两行错误日志

### Version

master (Default)

### What soultions are you seeing the problem on?

重新烧录固件，需多次尝试

### Relevant log output

```shell
=== system execute boot.py file, wait interrupt!! ==
== wait 1s send interrupt cmd!! ==
```

**Comment by senwangal** [comment]
应该是软件系统坏掉了，可以试下重新烧录固件能否解决

**Comment by YiluMao** [comment]
@Lingakg 
请问您还有问题吗？

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
