### ISSUE TITLE
[Bug Report]: esp32上注册串口回调函数失败，并且向串口发送数据会使单片机重启

### ISSUE THREAD

**Issue by zeng2008** [alibaba/AliOS-Things#1514]
### Contact Details

2768724163@qq.com

### What happened?

A bug happened!
运行环境:Windows10
固件版本:HaaSPython-ESP32-v2.0.0

### Version

rel_3.3.0 (Main)

### What soultions are you seeing the problem on?

helloworld_demo

### Relevant log output

```shell
==== python execute bootpy ====
enable OneMinuteOnCloud
 ==== python file check /data/pyamp/main.py ====
 ==== python execute from /data/pyamp/main.py ====
ret of UART_Open : 0
[   0.730]<E>DRIVER_UART uart_add_recv failed
```

**Comment by wuxn9999** [comment]
我们正在排查中

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
