### ISSUE TITLE
[Bug Report]: ADS1115传感器驱动文档描述问题

### ISSUE THREAD

**Issue by ethanlcz** [alibaba/AliOS-Things#1557]
### Contact Details

ethan.lcz@alibaba-inc.com

### What happened?

下面这段代码不能正常运行。
![image](https://user-images.githubusercontent.com/78590662/166892849-7eb752c0-186f-4078-8489-88351da4c437.png)

### Version

rel_3.3.0 (Main)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by ethanlcz** [comment]
已经解决掉并上线
