### ISSUE TITLE
[Feature Request]: “MPU6050” is not accessed.

### ISSUE THREAD

**Issue by krisaaaaa** [alibaba/AliOS-Things#1596]
### What do you want?

请问这个mpu6050是什么原因，导入不进来吗，怎么解决呢

![2022-05-11_192433](https://user-images.githubusercontent.com/102223609/167841666-6f3c549e-489e-4815-a5c9-894d4fbdd4ac.png)

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by ethanlcz** [comment]
> ### Contact Details
> _No response_
> 
> ### What do you want?
> 请问这个mpu6050是什么原因，导入不进来吗，怎么解决呢
> 
> ![2022-05-11_192433](https://user-images.githubusercontent.com/102223609/167841666-6f3c549e-489e-4815-a5c9-894d4fbdd4ac.png)
> 
> ### Version
> master (Default)

是怎么确认MPU6050没办法导入的呢？

**Comment by ethanlcz** [comment]
> > > ### Contact Details
> > > _No response_
> > > ### What do you want?
> > > 请问这个mpu6050是什么原因，导入不进来吗，怎么解决呢
> > > ![2022-05-11_192433](https://user-images.githubusercontent.com/102223609/167841666-6f3c549e-489e-4815-a5c9-894d4fbdd4ac.png)
> > > ### Version
> > > master (Default)
> > 
> > 
> > 是怎么确认MPU6050没办法导入的呢？
> 
> import后边的MPU6050是灰色的： ![QQ图片20220511201854](https://user-images.githubusercontent.com/102223609/167848138-dd15f8db-9b99-4810-b5cd-22e95c81873f.jpg) 请问这要怎么解决呢

from mpu6050 import MPU6050
MPU6050显示为灰色是VS Code检查到MPU6050这个类/函数你在代码中没有引用到，它可能认为对于你这个工程这句话是多余的。
你代码中有创建MPU6050的类对象并呼叫这个类提供的函数吗？
