### ISSUE TITLE
Haas Python 设备获取的视频流如何上云，并实时观看？

### ISSUE THREAD

**Issue by hanfengsir** [alibaba/AliOS-Things#1675]
查看了ucamera文档与社区案例，并没有相关记录

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
目前我们还没有提供视频采集类的HaaS轻应用接口
您可以考虑自己增加一个这样的接口，我们找下有没有相关文档

**Comment by YiluMao** [comment]
请问您还有进一步问题不？
@hanfengsir 
如果没有，帮忙close问题
