### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by xedge2018** [alibaba/AliOS-Things#169]
在ubuntu14.04下配置环境，通过一键安装脚本完成后，在默认目录~/aos下执行aos make helloworld@linuxhost，提示no command "aos" found，请问是系统环境哪里没有配置好吗？

**Comment by xedge2018** [comment]
原因找到了，应该用sudo pip install aos-cube来配置

**Comment by librae8226** [comment]
只要保证 aos-cube 安装以后 PATH 中可以引用到它就行，这里先close了，有问题请再提出。
