### ISSUE TITLE
SDK path setting的路径如何设置？

### ISSUE THREAD

**Issue by zhanlej** [alibaba/AliOS-Things#17]
这个SDK是用pip install aos-cube安装的么？

**Comment by chunshanzhu** [comment]
是

**Comment by zhanlej** [comment]
@chunshanzhu 但是我引用那个安装目录依旧不好使。
我使用的是Anaconda安装的Python，安装的目录如下：H:\Anaconda2\Lib\site-packages\aos。
在该目录下一共就4个文件__init__.py，__init__.pyc，aos.py，aos.pyc。
不知道我找的目录对不对？

**Comment by chunshanzhu** [comment]
win下没有弄过，请参见官方文档 https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Environment-Setup#21-aos-cube%E5%AE%89%E8%A3%85

**Comment by chunshanzhu** [comment]
win下没有弄过，请参见官方文档 https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Environment-Setup#21-aos-cube%E5%AE%89%E8%A3%85

**Comment by zhanlej** [comment]
你是在linux平台下操作的啊？

**Comment by woksdl** [comment]
在命令面板中执行 alios-studio: Technical Support 命令，会自动打开 AliOS Things Studio 用户支持钉钉账号的对话窗口，有任何问题，意见及建议可以直接通过这一渠道反馈

**Comment by zhanlej** [comment]
@wbgbg 非常感谢~~看官方wiki上面显示的路径是aos，所以我一直以为是用python下载的那个aos呢。昨天找了一晚上aos文件夹。

**Comment by wbgbg** [comment]
@zhanlej 多谢，我们已经在文档中更新了sdk path如何设置的说明。
