### ISSUE TITLE
[Feature Request]: 新增（宠物）自动投食器案例

### ISSUE THREAD

**Issue by wzhiyuan-nit** [alibaba/AliOS-Things#1704]
### 联系方式

wuming.wzy@alibaba-inc.com

### 新功能描述

当主人出门在外时，可通过手机远程操作自动投食器给家中宠物投放粮食，避免可爱的宠物们挨饿。

### 分支

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。
