### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by wowqaqtat** [alibaba/AliOS-Things#1746]
### What happened?

A bug happened!
点击部署运行或者串口时，无法继续，提示“pyserial-ports执行错误，请确保该文件存在”

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by wowqaqtat** [comment]
谢谢！我已经收到你的邮件

**Comment by YiluMao** [comment]
请帮忙提供更详细的信息
