### ISSUE TITLE
[Bug Report]: 安装aos，安装Make出现无限等待。。。

### ISSUE THREAD

**Issue by osachimd** [alibaba/AliOS-Things#1749]
### 联系方式

osachi@kenki-jp.com

### 您发现了什么问题

A bug happened!
运行环境:win10
固件版本:VScode1.67.2 | Haas-studio v2.1.0
现象：
1，打开VScode后，提示要我安装Make工具，点击【是】后，VScode的画面一直显示【正在安装 aos, 请等待...[1/5] 安装 Make】等了1晚上也没有变化。也重启过几次，仍然没有变化。

### 分支

rel_3.3.0 (Main)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by osachimd** [comment]
已经解决。选择【以管理员】打开vscode就可以了。

**Comment by senwangal** [comment]
感谢反馈
