### ISSUE TITLE
ble：是否有计划支持原厂协议栈？

### ISSUE THREAD

**Issue by woodsking2** [alibaba/AliOS-Things#178]
目前AliOS-Things用的是自己的协议栈，使用hci。
是否有计划使用原厂自己的协议栈呢？

**Comment by junjiec** [comment]
https://yq.aliyun.com/articles/337195?spm=a2c4e.11153959.teamhomeleft.82.443d41f3wu705f
可以看一下这个博客

**Comment by woodsking2** [comment]
博客里，描述的是基于hci接口适配。这个适配的代码我看了，大概了解了。部分蓝牙芯片没有提供hci接口，AliOS-Things是否有对接原厂协议栈的计划呢？
