### ISSUE TITLE
[Bug Report]: HaaS官网GPS传感器示例代码使用时提示AttributeError: 'UART' object has no attribute 'init'

### ISSUE THREAD

**Issue by ZH-21000301** [alibaba/AliOS-Things#1821]
### What happened?

A bug happened!
运行环境:
m5stackcore2
固件版本:
HaaSPython-ESP32-8M-v2.2.0.bin

### Version

master (Default)

### Relevant log output

```shell
AttributeError: 'UART' object has no attribute 'init'
```

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by ethanlcz** [comment]
> ### Contact Details
> _No response_
> 
> ### What happened?
> A bug happened! 运行环境: m5stackcore2 固件版本: HaaSPython-ESP32-8M-v2.2.0.bin
> 
> ### Version
> master (Default)
> 
> ### What soultions are you seeing the problem on?
> _No response_
> 
> ### Relevant log output
> ```shell
> AttributeError: 'UART' object has no attribute 'init'
> ```

请问下你的代码是怎样写的？
咱们的UART驱动本身就没有init的API的。
UART 的API文档请参考 https://haas.iot.aliyun.com/haasapi/index.html?spm=a2cpu.b16145223.0.0.595660b1jgQ20M#/Python/docs/zh-CN/haas_extended_api/driver/uart

**Comment by YiluMao** [comment]
请问还有问题不？

**Comment by ZH-21000301** [comment]
没问题了

**Comment by YiluMao** [comment]
好的，多谢
