### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by 123123ly** [alibaba/AliOS-Things#1827]
### Contact Details

1764745743@qq.com

### What do you want?

用的Haas506做的那个久坐提醒系统案例，代码串烧成功之后，网络也注册成功了，但是阿里云平台上的设备还是离线的

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
有另一个issue跟踪了，这个帮忙close下
@123123ly
