### ISSUE TITLE
[Bug Report]: HaaS EDU K1 UART.read 返回值错误

### ISSUE THREAD

**Issue by wuxn9999** [alibaba/AliOS-Things#1832]
### What happened?

UART缓冲区内没有数据的情况下UART.read函数返回5，按照API说明文档的说明，此时应该是要返回0。

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by wuxn9999** [comment]
Fixed.
