### ISSUE TITLE
[Bug Report]: 固件刷写报错

### ISSUE THREAD

**Issue by 275876610** [alibaba/AliOS-Things#1862]
### 您发现了什么问题

A bug happened!
运行环境:windows10
固件版本:HaaSEDUK1-v1.1.0
固件刷错无法开机，刷入HaaSEDUK1-v1.1.0报错。不知如何解决。
![image](https://user-images.githubusercontent.com/53804216/174918984-86cec98d-3984-4921-871e-c24f79cde50f.png)

### 分支

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by 275876610** [comment]
人工支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月22日(星期三) 上午8:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/AliOS-Things] [Bug Report]: 固件刷写报错 (Issue #1862)





 感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统， 您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&amp;f=a2cre.b82925042) 如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by 275876610** [comment]
人工支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/AliOS-Things"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 上午8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/AliOS-Things] [Bug Report]: 固件刷写报错 (Issue #1862)





 感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统， 您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&amp;f=a2cre.b82925042) 如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
请更新到最新的HaaS Studio
并使用最新的固件烧录试试

**Comment by YiluMao** [comment]
问题先关闭，如果有进一步问题，请reopen或者新开issue
多谢
