### ISSUE TITLE
《projects\Keil\lorawanapp\lorawanapp.uvprojx》休眠电流

### ISSUE THREAD

**Issue by lioneieChen** [alibaba/AliOS-Things#187]
我用stm32l073rz nucleo板子加sx1276模块跑《projects\Keil\lorawanapp\lorawanapp.uvprojx》应用，休眠电流0.77mA（没进入休眠模式），请问用EML3047模块跑《projects\Keil\lorawanapp\lorawanapp.uvprojx》，休眠电流是多少？

**Comment by shengpingdai** [comment]
目前基于eml3047实测在stop模式的待机电流为11uA
