### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Haitangone** [alibaba/AliOS-Things#1881]
### 联系方式

1079232460@QQ.COM

### 您发现了什么问题

A bug happened!
运行环境:WIN11
固件版本:2.2.0
我用合宙ESP32C3开发板，固件烧录进去了，串口显示信息也不对，程序也写不进去

### 分支

master (Default)

### 请选择您发现此问题的解决方案名称

py_engine_esp32_demo

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
不同的板子的串口配置可能是不一样的
我们的固件只能支持我们验证过的板子
建议换成我们支持的板子，或者您可以试着把相关串口代码修改后使用自己的固件

**Comment by YiluMao** [comment]
问题先关闭，如果有进一步问题，请reopen或者新开issue
多谢
