### ISSUE TITLE
可能会导致死锁问题发生

### ISSUE THREAD

**Issue by jiaotilizi** [alibaba/AliOS-Things#1896]
https://github.com/alibaba/AliOS-Things/blob/6a02872ea0231394eeb6be03fe082dd6f1e33b5e/components/uservice/src/event_svr.c#L250

该lock片段时，再执行event_publish，会分别执行到event_call，rpc_deinit内，执行了TASK_LOCK导致再次lock而出现死锁。

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
您可以帮忙提供修复的PR，我们可以结合代码讨论

**Comment by YiluMao** [comment]
问题先关闭，如果有进一步问题，请reopen或者新开issue
多谢
