### ISSUE TITLE
[Feature Request]: m5core2 的axp192芯片停产，是否有其它芯片推荐

### ISSUE THREAD

**Issue by rualdeng** [alibaba/AliOS-Things#1899]
### Contact Details

钉钉:rualxiao

### What do you want?

m5stack core2的电源管理芯片axp192已经停产了，我们在找代替芯片。你们这边有硬件相关同事可以有其它芯片给推荐不，这样可以缩短时间，谢谢！或者这块我应该找谁咨询？

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by rualdeng** [comment]
> ```
> 感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
> 您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)
> 
> 如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。
> ```

人工支持
