### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by ygxu** [alibaba/AliOS-Things#1900]
### 您发现了什么问题

A bug happened!
运行环境:Haas Python
固件版本:3.0
HaaS EDU K1 本地语音播报温湿度系统
ERROR unknow ali-odm-name
请问这个报错是什么原因，如何解决？

### 分支

master (Default)

**Comment by ygxu** [comment]
联系方式：pc3521@163.com

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
请问您发现了什么问题？

**Comment by YiluMao** [comment]
问题先关闭，如果有进一步问题，请reopen或者新开issue
多谢
