### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Arthurzxy** [alibaba/AliOS-Things#1921]
### 联系方式

arthurzxy@foxmail.com

### 您发现了什么问题

A bug happened!
运行环境: HaaS100
固件版本: 
无法利用这个命令行获取开发软件包’git clone https://github.com/alibaba/AliOS-Things.git -b dev_3.1.0_haas‘
报错：Remote branch dev_3.1.0_haas not found in upstream origin

### 分支

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by Arthurzxy** [comment]
没有解决我的问题

**Comment by YiluMao** [comment]
正在给您处理

**Comment by YiluMao** [comment]
已经可以了，请试下

**Comment by YiluMao** [comment]
请问还有问题不？

**Comment by YiluMao** [comment]
问题先关闭，有问题请再提交issue
