### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by xiamichen** [alibaba/AliOS-Things#1928]
### 联系方式

1757789374@qq.com

### 新功能描述

[明栈 M5StackCore2和M5stack Core使用相同的ESP32芯片、flash和LCD屏幕，那Core2的HAAS python固件能否直接烧录至M5stack core中使用
![M5Stack core](https://user-images.githubusercontent.com/29318137/182341874-4fb13c76-a479-473b-82f6-d3b7e8862eb4.png)
![M5Stack core2](https://user-images.githubusercontent.com/29318137/182341927-efacb059-0761-4245-b066-f70331c93774.png)

### 分支

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
我们没有验证过，可以尝试烧录下看看效果

**Comment by YiluMao** [comment]
请问还有问题不？

**Comment by YiluMao** [comment]
先关闭，有问题再开

**Comment by xiamichen** [comment]
没有了，我购买的相关硬件在路上，我到时候烧录一下看看情况



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月4日(星期四) 上午10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/AliOS-Things] [Feature Request]:  (Issue #1928)





 
请问还有问题不？

**Comment by YiluMao** [comment]
ok
