### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by whx1126** [alibaba/AliOS-Things#1931]
### 新功能描述

希望退出应用于配电房检测的功能和后台。比如可以接电流互感器采集配电柜的电流负荷信息，过高或者为零异常值时候短信和手机端提醒客户 过负荷或者停电达到提醒效果。希望做出这样的案例

### 分支

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
收到，已记录到我们案例库中，多谢贡献
也欢迎您开发出这个案例，通过Github提交到我们案例库中
