### ISSUE TITLE
如何升级已烧录旧版haas python固件的开发板？

### ISSUE THREAD

**Issue by mc8602** [alibaba/AliOS-Things#1946]
现使用esp32-cam，原来已烧录了HaaS python固件的1.0.0版本，后发现有2.2.0的新版本，想重新烧录时出现“powershell.exe detected, set miniconda env finished.”提示，请教如何烧录新的固件版本？

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by mc8602** [comment]
人工支持

**Comment by YiluMao** [comment]
请问您手里有没有别的非windows的电脑？如果有，可以试着用下

**Comment by YiluMao** [comment]
这个问题先关闭了，有问题请reopen或者再提新的issue
