### ISSUE TITLE
[Feature Request]: 看到alios过了ASIL-D认证，是这个系统的内核吗？

### ISSUE THREAD

**Issue by haishenming** [alibaba/AliOS-Things#1952]
### What do you want?

feature request
看到有报道说alios通过了ASIL-D功能安全认证，并提供免费的内核。
http://www.autor.com.cn/index/technology/vehicle/14377.html
请问是这个系统的内核吗？

### Version

master (Default)

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by YiluMao** [comment]
是这个内核

**Comment by YiluMao** [comment]
如果没有进一步问题，我先关闭，有问题请再打开或再提交新issue
