### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by AmosWang0626** [alibaba/AliOS-Things#1953]
### What happened?

A bug happened!
运行环境: MAC M1，HaaS EDU K1
固件版本: HaaSPython-EDUk1-v2.1.0-2022-04-29T12:27:21

无法烧录最简单的 helloworld

### Version

master (Default)

### Relevant log output

```shell
b'Z'
b'Z'
b'Z'
b'Z'
Please reboot the board manually.
Please reboot the board manually, and try it again.
```

**Comment by YiluMao** [comment]
应该是M1的MAC的兼容性问题，我们没有这个电脑，所以无法支持
抱歉，可以考虑找个别的电脑试试

**Comment by AmosWang0626** [comment]
已解决，操作方式不对。
打印完 Please reboot the board manually. 之后要按 reset 键、或者重启下机器。

详细参考文章：https://my.oschina.net/AmosWang/blog/5603640

**Comment by YiluMao** [comment]
为您点赞
