### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by zjh-nuc-AIOT** [alibaba/AliOS-Things#1954]
### Contact Details

2633716446@qq.com

### What happened?

A bug happened!
运行环境: Haas EDU k1
固件版本: 最新的

### Version

master (Default)

### Relevant log output

```shell
<E><0> [aos_i2c_master_send:479]i2c1 master send failed, ret:0
<E><0> [i2c_device_ioctl:205]i2c1 tx failed, tx_buffer:0x34099ce0, d->length:1, d->timeout:16777215, ret:0
[ 300.947]<E>DRIVER_I2C aos_hal_i2c_master_send failed
```

**Comment by zjh-nuc-AIOT** [comment]
没人吗

**Comment by iotmoe** [comment]
i want to unsubscribe

**Comment by iotmoe** [comment]
I want to unsubscribe

**Comment by YiluMao** [comment]
> i want to unsubscribe

You can unsubscribe by configuring your github.
