### ISSUE TITLE
能否保持一个小内核?

### ISSUE THREAD

**Issue by jcqi2004** [alibaba/AliOS-Things#206]
现在这个代码量下载有200多M.能不能像UCOS那样维持一个精练稳定的核.外围就管外围啊.这代码量的彭胀,每一版的兼容验证..........

**Comment by junjiec** [comment]
AliOS Things是一个广义的OS，并不只是一个内核。我们认为一个仅是一个RTOS内核无法改变目前物联网碎片化的现状。随着特性的迭代，支持的硬件越来越多，代码量确实会越来越大，AliOS Things有比较完善的自动化测试系统来支撑高速迭代，这也是AliOS Things相较于市面上其他物联网系统的一个优势。
