### ISSUE TITLE
VS-code中创建项目的时候，进不去选择模板的界面

### ISSUE THREAD

**Issue by LShaoPeng** [alibaba/AliOS-Things#208]
之前在ALIOS1.2版本的时候，创建项目的时候还是可以的，今天更新到1.3之后就不行了。现在的情况是直接添加一个路径，然后创建一个默认的项目。

请问这个是在哪里出现的问题？  如何解决

**Comment by neilneil0** [comment]
me too.

**Comment by librae8226** [comment]
Duplicate of #191
