### ISSUE TITLE
I got this quetion--build fail!

### ISSUE THREAD

**Issue by Neyzoter** [alibaba/AliOS-Things#211]
I got this quetion--build fail!

![question](https://user-images.githubusercontent.com/16913995/39125570-f56e954e-4731-11e8-85f1-90f36307da42.png)

**Comment by Neyzoter** [comment]
Who can tell me tow to tackle it.

**Comment by Neyzoter** [comment]
发现未选择helloworld@developement

**Comment by neilneil0** [comment]
@Neyzoter  请问解决了吗？ 我也是一样的问题，但我是选择了“helloworld@mk3060”的

**Comment by librae8226** [comment]
Close according to comments above.
