### ISSUE TITLE
编译atapp@stm32l476rg-nucleo，报错！

### ISSUE THREAD

**Issue by yuanfeng5721** [alibaba/AliOS-Things#225]
提示没有sys/prctl.h 文件。
H:\work\AliOS-Things\AliOS-Things>aos make atapp@stm32l476rg-nucleo
Build AOS Now
TOOLCHAIN_PATH=H:/work/AliOS-Things/AliOS-Things/build/compiler/gcc-arm-none-eabi/Win32/bin/
Compiling auto_component
Making out/atapp@stm32l476rg-nucleo/libraries/stm32l4xx_cube.a
Making out/atapp@stm32l476rg-nucleo/libraries/sal.a
Making out/atapp@stm32l476rg-nucleo/libraries/device_sal_mk3060.a
Making out/atapp@stm32l476rg-nucleo/libraries/stm32l476rg-nucleo.a
Compiling vcall
kernel/vcall/aos/aos_posix.c:10:23: fatal error: sys/prctl.h: No such file or directory
compilation terminated.
make.exe[1]: *** [build/aos_target_build.mk:248: out/atapp@stm32l476rg-nucleo/Modules/kernel/vcall/a
os/aos_posix.o] Error 1
make.exe[1]: *** Waiting for unfinished jobs....
make.exe: *** [build/Makefile:265: main_app] Error 2
[AliOS-Things] ERROR: "H" returned error code 2.
[AliOS-Things] ERROR: Command "H : / w o r k / A l i O S - T h i n g s / A l i O S - T h i n g s / b
 u i l d \ c m d / w i n 3 2 / m a k e . e x e   H O S T _ O S = W i n 3 2   T O O L S _ R O O T = H
 : / w o r k / A l i O S - T h i n g s / A l i O S - T h i n g s / b u i l d   - e   - f   b u i l d
 / M a k e f i l e   a t a p p @ s t m 3 2 l 4 7 6 r g - n u c l e o" in "H:\work\AliOS-Things\AliOS
-Things"
---

**Comment by librae8226** [comment]
atapp主要在linuxhost上用来验证wifi模组用，您时在什么场景下需要在 stm32l476rg 上用到呢？建议参考 [SAL 组件](https://github.com/alibaba/AliOS-Things/blob/master/device/sal/README.md)，也许可以解决你的问题
