### ISSUE TITLE
编译mqtt@stm32l476rg-nucleo报错

### ISSUE THREAD

**Issue by yuanfeng5721** [alibaba/AliOS-Things#226]
H:\work\AliOS-Things\AliOS-Things>aos make mqttapp@stm32l476rg-nucleo
Build AOS Now
TOOLCHAIN_PATH=H:/work/AliOS-Things/AliOS-Things/build/compiler/gcc-arm-none-eabi/Win32/bin/
Compiling auto_component
Making out/mqttapp@stm32l476rg-nucleo/libraries/auto_component.a
Making mqttapp@stm32l476rg-nucleo.elf
h:/work/alios-things/alios-things/build/compiler/gcc-arm-none-eabi/win32/bin/../lib/gcc/arm-none-eabi/5.4.1/../../..
/../arm-none-eabi/bin/ld.exe: error: out/mqttapp@stm32l476rg-nucleo/binary/mqttapp@stm32l476rg-nucleo.elf uses VFP r
egister arguments, ./framework/activation/./Cortex-M4/activation.a(alios_activation.o) does not
h:/work/alios-things/alios-things/build/compiler/gcc-arm-none-eabi/win32/bin/../lib/gcc/arm-none-eabi/5.4.1/../../..
/../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file ./framework/activation/./Cortex-M4/activa
tion.a(alios_activation.o)
h:/work/alios-things/alios-things/build/compiler/gcc-arm-none-eabi/win32/bin/../lib/gcc/arm-none-eabi/5.4.1/../../..
/../arm-none-eabi/bin/ld.exe: error: out/mqttapp@stm32l476rg-nucleo/binary/mqttapp@stm32l476rg-nucleo.elf uses VFP r
egister arguments, ./framework/activation/./Cortex-M4/activation.a(alios_activate_task_create.o) does not
h:/work/alios-things/alios-things/build/compiler/gcc-arm-none-eabi/win32/bin/../lib/gcc/arm-none-eabi/5.4.1/../../..
/../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file ./framework/activation/./Cortex-M4/activa
tion.a(alios_activate_task_create.o)
h:/work/alios-things/alios-things/build/compiler/gcc-arm-none-eabi/win32/bin/../lib/gcc/arm-none-eabi/5.4.1/../../..
/../arm-none-eabi/bin/ld.exe: error: out/mqttapp@stm32l476rg-nucleo/binary/mqttapp@stm32l476rg-nucleo.elf uses VFP r
egister arguments, ./framework/activation/./Cortex-M4/activation.a(info_encrypt.o) does not
h:/work/alios-things/alios-things/build/compiler/gcc-arm-none-eabi/win32/bin/../lib/gcc/arm-none-eabi/5.4.1/../../..
/../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file ./framework/activation/./Cortex-M4/activa
tion.a(info_encrypt.o)
collect2.exe: error: ld returned 1 exit status
make.exe[1]: *** [build/aos_target_build.mk:303: out/mqttapp@stm32l476rg-nucleo/binary/mqttapp@stm32l476rg-nucleo.el
f] Error 1
make.exe: *** [build/Makefile:265: main_app] Error 2
[AliOS-Things] ERROR: "H" returned error code 2.
[AliOS-Things] ERROR: Command "H : / w o r k / A l i O S - T h i n g s / A l i O S - T h i n g s / b u i l d \ c m d
 / w i n 3 2 / m a k e . e x e   H O S T _ O S = W i n 3 2   T O O L S _ R O O T = H : / w o r k / A l i O S - T h i
 n g s / A l i O S - T h i n g s / b u i l d   - e   - f   b u i l d / M a k e f i l e   m q t t a p p @ s t m 3 2 l
 4 7 6 r g - n u c l e o" in "H:\work\AliOS-Things\AliOS-Things"
---

**Comment by junjiec** [comment]
master上已修复
