### ISSUE TITLE
ESP32 使用tasklist崩溃

### ISSUE THREAD

**Issue by leoadvance** [alibaba/AliOS-Things#254]
如题，崩溃时有如下打印信息。

> kernel panic,err 1200!
> assertion "0" failed: file "platform/mcu/esp32/aos/soc_impl.c", line 35, function: soc_err_proc
> abort() was called at PC 0x40104f27 on core 0
> 
> Backtrace:
> 
>  0x40088ad8:0x3fffab90 0x40088bd7:0x3fffabb0 0x40104f27:0x3fffabd0 0x4008b22d:0x3fffac00 0x400859b9:0x3fffac20 0x400846e6:0x3fffac40 0x4008b895:0x3fffac60 0x4008b872:0x3fffac80 0x400862c8:0x3fffaca0 0x4008675b:0x3fffacc0 0x40086bc4:0x3ffface0 0x400d215b:0x3fffad00 0x400d2419:0x3fffad40 0x40089f1d:0x3fffad70 0x4010430f:0x3fffad90 0x40101c8d:0x3fffadb0 0x40101cfd:0x3fffadd0 0x4010252e:0x3fffaf20 0x40084ec1:0x3fffaf80

**Comment by Devilliv** [comment]
@leoadvance hello，was that problem solved?
