### ISSUE TITLE
开放平台厂测包-链接无法打开，去掉“。”后APP无法下载

### ISSUE THREAD

**Issue by LeoZhang-ATMEL** [alibaba/AliOS-Things#259]
https://github.com/alibaba/AliOS-Things/wiki/WiFi-Provisioning-and-Alink-Certification

![image](https://user-images.githubusercontent.com/20182981/40031188-18131408-5821-11e8-85c8-1882b2e75f92.png)

**Comment by Shaofa** [comment]
文档里链接错误会尽快修复，经测试，删除"。"之后的链接是有效的，APP可以下载并使用，链接如下：
[https://open.aliplus.com/download](https://open.aliplus.com/download)
（测试时使用4G网络访问该地址）

**Comment by librae8226** [comment]
close according to above comments
