### ISSUE TITLE
example/wifimonitor 的用途

### ISSUE THREAD

**Issue by tidyjiang8** [alibaba/AliOS-Things#26]
1. wifimonitor 的具体作用是啥？ 它的README只有简单的一句话
2. 这个 demo 目前编译(`aos make wifimonitor@mk3060`)无法通过， 提示 umesh_get_mac_address() 缺少参数
3. 如何让这个 demo 跑起来？除了MK3060和PC外，还需要其它设备吗，如何操作？

**Comment by lluwang** [comment]
1 WiFi monitor 主要的作用是通过接收probe 数据，这个数据可以来源于手机，也可以来源于其它WiFi设备。接收到数据后，WiFi monitor会控制灯的on/off， 同时会解析出数据的mac address。并将这些信息通过uMesh发送到连接热点AP的节点。
2 编译不过的问题会有patch处理。
3 如果想让demo跑起来，需要有至少两块mk3060，以及连接mk3060的灯具。

**Comment by lluwang** [comment]
1 WiFi monitor 主要的作用是通过接收probe 数据，这个数据可以来源于手机，也可以来源于其它WiFi设备。接收到数据后，WiFi monitor会控制灯的on/off， 同时会解析出数据的mac address。并将这些信息通过uMesh发送到连接热点AP的节点。
2 编译不过的问题会有patch处理。
3 如果想让demo跑起来，需要有至少两块mk3060，以及连接mk3060的灯具。

**Comment by tidyjiang8** [comment]
Thx
