### ISSUE TITLE
libywss.a问题

### ISSUE THREAD

**Issue by maggie17** [alibaba/AliOS-Things#263]
alios version: v1.3.0
example: linkkitapp
HOST_ARCH: xtensa
issues：
1）编译时会报如下warning:
    
![default](https://user-images.githubusercontent.com/36881753/40221026-c9291114-5aad-11e8-9749-f2236eab0acc.png)

2) 程序运行到该库就会crash （如awss_start）.

请问如何解决？谢谢！

**Comment by junjiec** [comment]
你们使用的是什么芯片平台？

**Comment by maggie17** [comment]
是我们自己的芯片，CPU是xtensa的

**Comment by junjiec** [comment]
你们提供一下工具链，这样我们可以编译一个给你
你们可以先提交代码？只要helloworld可以跑通
