### ISSUE TITLE
AliOs-Things最小资源要求是多少， 需要多少ram， 多少rom， 以及是否有特殊外设需求

### ISSUE THREAD

**Issue by yihenf** [alibaba/AliOS-Things#27]
# AliOs-Things资源要求：
- Ram最少要求多少kBytes
- Rom最小要求多少kBytes
- 运行频率建议

最后， stm32l0系列可以支持吗？

**Comment by hanfengcan** [comment]
最小值不代表能跑你的应用吧。

**Comment by junjiec** [comment]
和应用场景相关,比如LoRaWAN,RAM 8KB~,ROM 64KB~
