### ISSUE TITLE
alinkapp issue

### ISSUE THREAD

**Issue by maggie17** [alibaba/AliOS-Things#272]
alios version: 1.2.1
examples: alinkapp

![default](https://user-images.githubusercontent.com/36881753/40303618-0d22a216-5d26-11e8-9ff7-59c759fdf111.png)

如上图，串口已显示"alink cloud connected!"，但是我在cloud端看到的设备状态依然是“开发中”，而不是“在线”，如下图。
![default](https://user-images.githubusercontent.com/36881753/40303707-761c713e-5d26-11e8-93d4-55e2636d5d09.png)

请问还需要别的什么操作吗？上面打印是否表示我们的设备已经连接到ali cloud了呢？
谢谢！

**Comment by librae8226** [comment]
@maggie17 方便尝试用 linkkitapp 替代现在的 alinkapp 么？这样 AliOS Things 也得一起升级才能支持。
可以确认的是目前云端 alink 部分正在业务调整中，所以确实可能遇到问题。
