### ISSUE TITLE
hal层外设初始化时建议增加管脚参数

### ISSUE THREAD

**Issue by leoadvance** [alibaba/AliOS-Things#273]
目前很多MCU的外设（UART，IIC等）已经不是固定管脚了。比如ESP32的UART，几乎能配置成所有管脚。 所以在hal_xxx_init里是否考虑加入管脚这个参数。 ESP32的I2C也有同样问题。只有一些老MCU（如STM32）外设是固定管脚的。

**Comment by jason-sophia** [comment]
1、hal_xxx_init的调用对象是上层用户，以uart为例用户需要关心的是波特率、奇偶校验位等通讯配置相关的参数，管脚配置用户是不关心的，这是驱动工程师需要去实现的。管脚配置对于一个具体的项目来讲是固定的，不需要频繁配置的，暴露给上层是没有必要的。
2、我们的hal_xxx_init接口是要对接所有芯片的，管脚定义这种与具体硬件强相关的参数是无法抽象到hal这一层的。
3、我们的管脚没有固定，是可以进行配置的，可以好好阅读下AliOS Things HAL Porting Guide，里面说明了该如何对管脚进行配置。

**Comment by librae8226** [comment]
根据之前钉钉的沟通和 @jason-sophia 的建议，先关掉了。如果还有后续问题可以再次打开。
@leoadvance 如果有好的提议也欢迎提交 pull request 一起讨论 🤝
