### ISSUE TITLE
GD32F4xx Project build fail

### ISSUE THREAD

**Issue by hptsf** [alibaba/AliOS-Things#277]
The project AliOS-Things\projects\Keil\GD32F4xx\alink_sample\GD32450Z_EVAL.uvprojx build fail:
    I found, in this project, there are many included files is too old. Even those files didn't exist.

**Comment by librae8226** [comment]
@leek3 Would you please help to comment in case any code or files missing or out-dated?

**Comment by hptsf** [comment]
![missing_files](https://user-images.githubusercontent.com/6884036/40478699-5a976380-5f7c-11e8-895e-0f4f4f92948e.png)
Please refer to pic as above, and those just only a part of.

**Comment by hptsf** [comment]
Maybe you can open the project and have a re-build to confirm it. Thx.
