### ISSUE TITLE
基础内核移植教程太含糊了，比如要移植到M0 M3 M7，具体的移植流程是怎么样的？

### ISSUE THREAD

**Issue by Supowang** [alibaba/AliOS-Things#28]

**Comment by junjiec** [comment]
请参考
https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Rhino-Porting-Guide
的cpu移植部分,文档具体哪部分不清楚麻烦具体一点,我们逐步改进

**Comment by NEXTLEO** [comment]
可以搞一个跟CMSIS-RTOS相似的API

**Comment by Supowang** [comment]
@junjiec  比如cpu_task_switch函数为上下文切换时，压栈弹栈处理，你们就讲个适配？怎么适配？M0和M4的弹栈压栈就有很大差别，指令也不一样的，不同的OS的弹栈压栈逻辑可能也有细微差别，那这部分是不是应该详细点，这个只是一个小的建议，AliOS开源出来的代码确实有技术含量，希望AliOS的文档也能做得更好。。。

**Comment by junjiec** [comment]
多谢反馈，我们后面补全

**Comment by loglong007** [comment]
请参考下列网址章节4 kernel移植样例，https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Rhino-Porting-Guide#4%E5%9F%BA%E4%BA%8Ekeil%E6%9C%80%E5%B0%8F%E5%86%85%E6%A0%B8%E7%A7%BB%E6%A4%8D%E7%A4%BA%E4%BE%8B。文档会持续补充和优化，如有问题，多谢反馈！
