### ISSUE TITLE
aliOS-things 物联网案例中的阿里云SDS是什么？

### ISSUE THREAD

**Issue by taoliqing** [alibaba/AliOS-Things#282]
aliOS-things 物联网案例中的阿里云SDS是什么？，小白求解

**Comment by librae8226** [comment]
这个是之前云端一个内测版产品的名字，全称 Smart Device Service，对设备端来说理解成一个连接通道即可。
现在发布的云端平台都是以`阿里云Link`为前缀的名字，详见 [iot.aliyun.com](https://iot.aliyun.com/)
