### ISSUE TITLE
IOT调试测试工具，连上串口后按照提示重启设备，无反应

### ISSUE THREAD

**Issue by LeoZhang-ATMEL** [alibaba/AliOS-Things#288]
打开"IOT调试测试工具.exe"，连接串口后，提示重启设备，操作MCU重启后无任何反应。
用其他第三方串口工具，在输入yts_run后可以正常运行测试案例。
[Ali Certification Test Result.txt](https://github.com/alibaba/AliOS-Things/files/2035153/Ali.Certification.Test.Result.txt)

![image](https://user-images.githubusercontent.com/20182981/40483635-43baab9a-5f8b-11e8-87a6-8067efcea946.png)

**Comment by Shaofa** [comment]
工具没有响应的问题是因为测试代码跟工具没有匹配，没有很好兼容发送或者不发送yts_run命令，这个问题会在下一个版本里fixed，在提交认证时附上打印日志就可以了

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.

本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
