### ISSUE TITLE
认证信息页面，套餐类型始终无法显示

### ISSUE THREAD

**Issue by LeoZhang-ATMEL** [alibaba/AliOS-Things#289]
通过certification.aliyun.com创建测试申请，套餐类型始终无法显示
![bbc5e8fc-a087-41da-acc2-3b6018aa7025](https://user-images.githubusercontent.com/20182981/40491239-1c9510fe-5fa0-11e8-9d01-07e28c3995ea.png)

**Comment by Shaofa** [comment]
这是已知bug，会在6月初发布版本中修复，主要原因是目前系统还没有录入您需要的套餐
钉钉沟通了解您的详细需求

**Comment by LeoZhang-ATMEL** [comment]
当产品类型是“芯片”时，通信类型选“MCU”会无法选择套餐。
![image](https://user-images.githubusercontent.com/20182981/40528021-d6b2a06a-6021-11e8-97c5-24d9c11ba1c9.png)

**Comment by Shaofa** [comment]
“MCU”字段会在下一个版本去掉，请选择“通用”标签

**Comment by librae8226** [comment]
close per above comments
