### ISSUE TITLE
MQTT通道压测的源码补丁mqtttest.patch无法patch到mqtt-example.c

### ISSUE THREAD

**Issue by LeoZhang-ATMEL** [alibaba/AliOS-Things#290]
按照文档所示无法将patch文件应用于最新代码
![image](https://user-images.githubusercontent.com/20182981/40490295-c7aca932-5f9d-11e8-9206-b98036a6f0c1.png)

> AliOS-Things$ patch ./example/mqttapp/mqtt-example.c ../mqtttest.patch
patching file ./example/mqttapp/mqtt-example.c
Hunk #1 succeeded at 44 (offset -2 lines).
Hunk #2 succeeded at 54 (offset -2 lines).
Hunk #3 succeeded at 63 (offset -2 lines).
Hunk #4 succeeded at 98 (offset -2 lines).
Hunk #5 succeeded at 112 (offset -2 lines).
Hunk #6 FAILED at 151.
Hunk #7 FAILED at 159.
Hunk #8 succeeded at 293 (offset -2 lines).
Hunk #9 FAILED at 326.
Hunk #10 FAILED at 344.
Hunk #11 FAILED at 349.
5 out of 11 hunks FAILED -- saving rejects to file ./example/mqttapp/mqtt-example.c.rej

**Comment by Shaofa** [comment]
github上最新版本已经不需要打该补丁，很抱歉文档没有及时更新

**Comment by skylarCai** [comment]
This issue has not been updated for a while, so we close this issue.  If you have further request, please reopen it or add it.  We will response as soon as possible.
本issue因太久未更新而关闭，如果您还有进一步的问题，请reopen本issue，或者新开一个issue，我们会尽快回复您。
