### ISSUE TITLE
vs code 中安装alios-studio缺少build窗口

### ISSUE THREAD

**Issue by LShaoPeng** [alibaba/AliOS-Things#299]
安装alios-studio后刚开始是正常的，使用一段时间之后打开发现build窗口没有了，重新安装扩展也没有解决。请协助解决一下，谢谢。

**Comment by librae8226** [comment]
![image](https://user-images.githubusercontent.com/357679/40641009-cf28ad2c-634a-11e8-9ba3-34fcd24a89ed.png)
`Ctrl + J` or `Cmd + J`
是否解决你的问题呢？

**Comment by librae8226** [comment]
好的，新版本可以参考这篇文档 https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Studio
那么还有问题吗？
