### ISSUE TITLE
redefined functions/structures

### ISSUE THREAD

**Issue by maggie17** [alibaba/AliOS-Things#303]
In aos1.3.0, the below functions/structures are redefined when compiling linkkitapp. Any config file to avoid compile errors? Thanks!
```
awss_recv_80211_frame_cb_t
awss_wifi_mgmt_frame_cb_t
awss_wifi_scan_result_cb_t
platform_wifi_mgnt_frame_cb_t
mbedtls_time_t
```

**Comment by junjiec** [comment]
which platform？

**Comment by maggie17** [comment]
our own platform, using xtensa cpu
