### ISSUE TITLE
studio没有开源吗

### ISSUE THREAD

**Issue by hanfengcan** [alibaba/AliOS-Things#33]
打算自己写个nodemcu的vscode插件。想知道vscode插件上的串口功能是如何实现的，以为可以找到源码。结果发现没有公布插件源码。

开发组可以告诉一下studio串口部分实现的思路吗，或者提供一下相关参考文档也可以

谢谢😁

**Comment by wbgbg** [comment]
AliOS-Things的VS Code插件目前是通过 https://github.com/Microsoft/vscode-arduino/tree/master/vendor/node-usb-native 这个库进行串口通信的，可以参考下。

**Comment by hanfengcan** [comment]
好的，谢谢哈
