### ISSUE TITLE
blink@esp32devkitc不能进入中断函数

### ISSUE THREAD

**Issue by linrx1511** [alibaba/AliOS-Things#348]
windows 下用vs code正常编译后，烧录到板子上，能正常运行，但不能进入中断函数gpio_isr_handler。

**Comment by librae8226** [comment]
@shaoguoji

**Comment by lss6378** [comment]
**environment**
    1. branch(version): developer
    2. Desktop OS(windows linux or macOS): Win10
    3. example: blink@esp32devkitc
遇到同样的问题，windows 下用vs code正常编译后，烧录到板子上，能正常运行，但不能进入中断函数gpio_isr_handler。

**Comment by lss6378** [comment]
> 
> 
> **environment**
> 1. branch(version): developer
> 2. Desktop OS(windows linux or macOS): Win10
> 3. example: blink@esp32devkitc
> 遇到同样的问题，windows 下用vs code正常编译后，烧录到板子上，能正常运行，但不能进入中断函数gpio_isr_handler。

使用 *aos make clean* 后重新编译，依旧按按键依旧不能进入中断

**Comment by lss6378** [comment]
@shaoguoji @librae8226
