### ISSUE TITLE
atapp@linuxhost 运行会 crash

### ISSUE THREAD

**Issue by tidyjiang8** [alibaba/AliOS-Things#35]
1. 如题，在Linux平台上运行 atapp就会 crash.
2. 文件`platform/mcu/linux/soc/uart.c`中的函数 `hal_uart_init()`的 pdrv 指针直接 hard-code 指向 uart0，这应该也不合理

**Comment by junjiec** [comment]
收到，我们尽快解决

**Comment by junjiec** [comment]
已修复
