### ISSUE TITLE
yloop的野指针

### ISSUE THREAD

**Issue by LeoZhang-ATMEL** [alibaba/AliOS-Things#374]
yloop函数的两个问题。

1. aos_poll_read_fd(Line 126, new_sock += cnt - 1;) 当第二次调用aos_poll_read_fd()函数时，Line126会使new_sock变成野指针。
https://github.com/alibaba/AliOS-Things/blob/844e71348f089bbbec41daa7cbb391359c2a730f/kernel/yloop/yloop.c#L120-L140
2. aos_poll_read_fd(Line 123, aos_free(ctx->pollfds);)当第二次调用aos_poll_read_fd()函数时，会free掉ctx->pollfds，但此时如果aos_loop_run()仍在运行的话，会导致ctx->pollfds指针变成野指针，最终导致程序崩溃。
https://github.com/alibaba/AliOS-Things/blob/844e71348f089bbbec41daa7cbb391359c2a730f/kernel/yloop/yloop.c#L244-L248

上面的2个问题都是由于aos_poll_read_fd()被两次调用后产生的，该情况会发生在mqttapp的demo中，
第一次：
https://github.com/alibaba/AliOS-Things/blob/844e71348f089bbbec41daa7cbb391359c2a730f/kernel/init/aos_init.c#L264
第二次
https://github.com/alibaba/AliOS-Things/blob/844e71348f089bbbec41daa7cbb391359c2a730f/framework/connectivity/mqtt/mqtt_client.c#L2071

**Comment by librae8226** [comment]
可以把实际应用和出问题的场景描述一下吗？
目前按设计来说都是只需要跑起来一个 yloop 的，这个问题出现在超过一个 yloop 运行的情况下？

**Comment by LeoZhang-ATMEL** [comment]
实际应用场景就是跑mqttapp的demo，默认demo的代码就会先后调用aos_loop_init()和aos_poll_read_red()两个函数，导致最终产生野指针。
` -e -D_TIMESPEC_DEFINED --silent --only_stdout --no_warnings --diag_warning=Pe167,Pe144,Pe513 -DSYSINFO_OS_VERSION="\"\"" -DSYSINFO_PRODUCT_MODEL="\"ALI_AOS_ATSAME54-XPRO\"" -DSYSINFO_DEVICE_NAME="\"ATSAME54\"" -DSYSINFO_APP_VERSION="\"app-1.0.0-20180623.2356\"" -D__SAME54P20A__ --cpu_mode=thumb -DSYSINFO_KERNEL_VERSION="\"AOS-R-1.3.1\"" -DAOS_SDK_VERSION_MAJOR=3 -DAOS_SDK_VERSION_MINOR=2 -DAOS_SDK_VERSION_REVISION=3 -DPLATFORM="\"atsame54-xpro\"" -DBUILD_BIN -DCONFIG_ALICRYPTO -DAOS_ATCMD -DSTDIO_UART=2 -DHAVE_NOT_ADVANCED_FORMATE -DCONFIG_AOS_CLI -DMQTT_COMM_ENABLED -DCMP_VIA_MQTT_DIRECT -DMQTT_DIRECT -DAOS_FOTA -DVCALL_RHINO -DAOS_FRAMEWORK_COMMON -DAOS_HAL -DAOS_KV -DMQTT_TEST -DALIOT_DEBUG -DIOTX_DEBUG -DUSE_LPTHREAD -DAOS_NETMGR -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -DCONFIG_IOT_KIT -DWITH_SAL -DDEV_SAL_MK3060 -DAOS_VFS -DAOS_LOOP  
`

**Comment by librae8226** [comment]
@LeoZhang-ATMEL 多谢反馈，我们重新看看这部分内容

**Comment by caveguy** [comment]
这里不存在野指针问题。第n次调用aos_poll_read_fd()函数时，会free掉ctx->pollfds和ctx->readers，然后重新申请一片目前所有已read的fd的pollfds和readers的空间（不包含已aos_cancel_poll_read_fd的应该释放的）。也就是每次aos_cancel_poll_read_fd时，释放的内存并不立即回收，而是等下一层aos_poll_read_fd或aos_loop_destroy时回收。

**Comment by LeoZhang-ATMEL** [comment]
hi @caveguy，谢谢。
我做了一个测试，用master的代码和mqttapp@developerkit的demo在developerkit上跑，在framework/connectivity/mqtt/mqtt_client.c的iotx_mc_connect()的函数代码里加了一句while (1)一直跑aos_poll_read_fd，然后命令行输入netmgr connect命令连接云，基本跑到100多次的时候就会内存越界了。在我们的MCU上跑，只需要跑一次aos_poll_read_fd()函数就会内存越界，我想这可能跟不同的开发板内存分配有关系，但结果基本是一样的。能帮忙看看吗？

> diff --git a/framework/connectivity/mqtt/mqtt_client.c b/framework/connectivity/                           mqtt/mqtt_client.c
index 42fc86ca..728a70c3 100644
--- a/framework/connectivity/mqtt/mqtt_client.c
+++ b/framework/connectivity/mqtt/mqtt_client.c
@@ -2068,7 +2068,9 @@ static int iotx_mc_connect(iotx_mc_client_t *pClient)
>     utils_time_countdown_ms(&pClient->next_ping_time, pClient->connect_data.kee                           pAliveInterval * 1000);
> \-    aos_poll_read_fd(get_iotx_fd(), cb_recv, pClient);
\+    while (1) {
\+        aos_poll_read_fd(get_iotx_fd(), cb_recv, pClient);
\+    }
     aos_post_delayed_action( pClient->connect_data.keepAliveInterval * 1000, cb                           _recv_timeout, pClient);
     aos_post_event(EV_SYS, CODE_SYS_ON_MQTT_READ, 0u);
     log_info("mqtt connect success!");

**Comment by lluwang** [comment]
Hi Leo,关于这段代码：

    memcpy(new_sock, ctx->readers, (cnt - 1) * sizeof(yloop_sock_t));
    aos_free(ctx->readers);
    ctx->readers = new_sock;

每次我们会把ctx->readers里面的内容copy 到new_sock，然后把ctx->readers (上一次的new_sock)的空间释放掉，所以应该不会出现内存泄漏的情况。

new_loop_pollfds也是同样的道理。

另外，你这里越界，我理解是用法的问题，get_iotx_fd()最后是创建socket fd，应该没有办法创建这么多。
