### ISSUE TITLE
a bug for AliOS-Things with ESP32 on Ubuntu 16.04.4

### ISSUE THREAD

**Issue by zhuang1125** [alibaba/AliOS-Things#376]
with rel_1.3.1  build esp32 has a bug. rel_1.3.1 is ok.

my script is:
1:
git clone --recursive -b rel_1.3.1 https://github.com/alibaba/AliOS-Things.git
cd AliOS-Things
aos make helloworld@esp32devkitc   //  Error   not find esptool.py

2:

git clone --recursive -b rel_1.3.0 https://github.com/alibaba/AliOS-Things.git
cd AliOS-Things
aos make helloworld@esp32devkitc  //Ok

**Comment by librae8226** [comment]
Please attach corresponding error log. `esptool.py` should be able to download automatically.
