### ISSUE TITLE
AliOS所支持的硬件平台（MK3060）相关硬件接口开发（GPIO，ADC，UART，I2C等）

### ISSUE THREAD

**Issue by KaiboFu** [alibaba/AliOS-Things#39]
AliOS是否提供所支持的平台（例如MK3060）的一些硬件接口开发的API（例如GPIO，ADC，UART，I2C等）？
如果提供的话，可以指出相关代码文件与文档介绍位置吗？
如果没有提供，不知道是否可以提供一些相关资料的链接？
感谢回答！

**Comment by junjiec** [comment]
mk3060上，gpio和uart已经支持，参考
https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-API-HAL-SOC-GPIO-Guide

其他的需要和厂商反馈一下

**Comment by KaiboFu** [comment]
@junjiec 感谢！
关于gpio的具体使用方法（例如管脚的具体赋值），我在example/wifimonitor中能够了解到。关于uart的用法，我能够在paltform/mcu/linux/main/hw.c与tools/cli/cli.c中了解一些。
不知关于gpio和uart的使用是否提供一些例子或者在文档介绍这些api中提供一些示例，例如Arduino的api介绍，如：https://www.arduino.cc/reference/en/language/functions/digital-io/pinmode/。
期待回复！

**Comment by junjiec** [comment]
@KaiboFu API的用法参考我上面的链接，示例代码我们在规划，请再耐心等待。如果API使用过程中碰到什么具体问题可以提出来。
