### ISSUE TITLE
感觉要放弃了

### ISSUE THREAD

**Issue by crazyskady** [alibaba/AliOS-Things#405]
看了一周，看的脑瓜子疼。。。感觉东西太多了。不如freeRTOS看起来那么清楚。。。想移植个新板子好费劲。。。o(╯□╰)o

**Comment by librae8226** [comment]
@crazyskady 
可以聊聊看移植过程具体遇到什么问题呢？
和 FreeRTOS 不是一个维度的哈，因为不仅是一个 kernel，还有大量系统性的组件，以支撑复杂多变的 IoT 场景。

**Comment by librae8226** [comment]
这里先关掉了哈，如果还有更多问题可以再次打开此 issue
