### ISSUE TITLE
请问 usyscall syscall 在MCU ARCH/MCU上是怎么实现的

### ISSUE THREAD

**Issue by zhouyuanjouzhou2013** [alibaba/AliOS-Things#44]
linxhost上面的例子没有编译usyscall syscall, 
mk3060上面的例子也没有编译usyscall syscall, 
怎么让usyscall syscall 在MCU ARCH/MCU上 编译进去；
usyscall syscall 系统调用 在MCU ARCH/MCU上是怎么实现的，怎么实现进入MCU核心态的

**Comment by atmfjg** [comment]
linxhost不支持多bin编译；
现在支持mk3060 多bin编译方式：
比如：aos make helloworld@mk3060 BINS=kernel/framewor/app 
针对mcu特性，现在syscall实现的是单地址空间中的函数调用方式，用脚本实现。同时现有syscall方式支持扩展成svc的系统调用方式；
多bin卖点：主要服务于fota升级情况下减少ota分区（只占最大bin空间kernel/framework/app），降低硬件成本。开发者可以只关心app开发。
