### ISSUE TITLE
AliOS Things Studio 编译esp8266 卡在 Making config file for first time 

### ISSUE THREAD

**Issue by a710450641** [alibaba/AliOS-Things#440]

**Comment by shuaibixi** [comment]
在工程目录下执行 aos make helloworld@esp8266也会卡

**Comment by a710450641** [comment]
@shuaibixi 那你是怎么解决这个问题的呢？

**Comment by walker2048** [comment]
windows下不能直接编译esp8266哦，建议切换到Linux平台，或者通过虚拟机编译

**Comment by siberianfox** [comment]
也遇到了这个问题，还没解决

**Comment by mmabluesky** [comment]
@siberianfox 
你现在解决了吗 ，我今天也是卡在这里

**Comment by xiaowenxia** [comment]
@mmabluesky  @siberianfox  windows下不支持编译esp8266 哈，需要切换到linux或者macOS下才能够正常编译esp8266。

**Comment by mmabluesky** [comment]
@xiaowenxia 
我是xr871
![image](https://user-images.githubusercontent.com/17948377/49139738-8679b080-f32d-11e8-860a-092b5299ff2d.png)

**Comment by walker2048** [comment]
win下编译esp8266等开发板，可以使用此[docker镜像](https://hub.docker.com/r/walker2048/easy-aos/)
