### ISSUE TITLE
coapapp@developerkit Example示例联网接入异常

### ISSUE THREAD

**Issue by iwanthaha** [alibaba/AliOS-Things#445]
**Describe the bug**
coapapp@developerkit Example示例联网接入异常，提示<E>  Create coap context failed及<V> IoTx CoAP init failed。

**environment**
1. branch(version): 957bf3d
2. Desktop OS(windows linux or macOS):win7 64bit
3. example: coapapp@developerkit

**Expected behavior**
期望Iot控制台中可观察到developerkit设备上线的行为消息；

**Screenshots**
开机连接错误，截图如下：
![err01](https://user-images.githubusercontent.com/35119986/43251152-c4807fe2-90f1-11e8-8a55-cfc171992590.jpg)

调试错误定位于sal_sockets.c文件的第806行，截图如下：
![err02](https://user-images.githubusercontent.com/35119986/43251246-01201656-90f2-11e8-92c5-394d431caee6.JPG)

控制台无设备行为记录，截图如下：
![err03](https://user-images.githubusercontent.com/35119986/43251640-0978c9a0-90f3-11e8-9d63-a73ff4991e70.JPG)

**Additional context**
编译信息如下：
> Executing task: aos make coapapp@developerkit <

aos-cube version: 0.2.46
Check if required tools for developerkit exist
Making config file for first time
processing components: coapapp developerkit platform/mcu/stm32l4xx_cube vcall init auto_component
app_version:app-1.0.0-20180726.1520
kernel_version:AOS-R-1.3.1
app_version:app-1.0.0-20180726.1520
kernel_version:AOS-R-1.3.1

**Comment by Jianlong0430** [comment]
Hi @iwanthaha , we confirmed currently we don't have this coapapp to support developerkit board, it is new feature for us and will be evaluated by AliOS Things team soon.
