### ISSUE TITLE
js生成的bin怎么上传到设备呢

### ISSUE THREAD

**Issue by boneq** [alibaba/AliOS-Things#446]
js生成的bin文件有其他方式上传到设备呢？我用的docker环境  docker下不能共享串口到容器内无法使用be push

**Comment by librae8226** [comment]
用 docker 想要映射串口确实有点麻烦，可以考虑在docker中生成bin，在主机中be push（docker和主机共享一部分文件）

**Comment by boneq** [comment]
be这个要依赖node比较麻烦的，我就是想看你有没有好的方法来映射进来在容器内直接设备下发数据，软连接也不行，容器内识别不到

Librae <notifications@github.com> 于2018年8月2日周四 下午12:43写道：

**Comment by librae8226** [comment]
那这种情况估计从云端推送bin更新会比较舒服，@wuzhun1001 有什么好建议吗？

**Comment by wuzhun1001** [comment]
从云端推动bin的方式还不支持，暂时可以采用将js文件打包成spiffs.bin的方法，参考https://github.com/alibaba/AliOS-Things/blob/master/framework/tinyengine/README.md

**Comment by boneq** [comment]
我也是试了，不行的，他的spiffs.bin上去后有问题运行不了，说是index.js有问题

wuzhun <notifications@github.com> 于2018年8月6日周一 下午2:32写道：

**Comment by wuzhun1001** [comment]
请使用github上最新的固件和参考https://github.com/alibaba/AliOS-Things/blob/master/framework/tinyengine/README.md。
已经Fix了spiffs.bin在developerkit上找不到index.js的问题。

**Comment by boneq** [comment]
恩  行的，谢谢了，我看下

wuzhun <notifications@github.com> 于2018年8月9日周四 上午9:25写道：
