### ISSUE TITLE
AliOS Things移植硬件平台要求

### ISSUE THREAD

**Issue by zhangjuxtu** [alibaba/AliOS-Things#46]
你好，我想学习下移植AliOS，请问对硬件平台有什么要求？如果我用FPGA开发板烧一个MIPS的系统，可以移植嘛？

**Comment by atmfjg** [comment]
有版本计划的。你是否想尝试一把，我们可以技术支持哈。

**Comment by zhangjuxtu** [comment]
我很想试试，前几天买了个MXCHIP IoT DevKit，但这个开发板资料较小，这款可以用来移植AliOS嘛？

**Comment by zhangjuxtu** [comment]
手头上还有一个LEON3的环境，可以直接烧到FPGA上，可以基本这个平台尝试嘛？

**Comment by junjiec** [comment]
@zhangjuxtu 欢迎入群交流
![微信群](http://o7spigzvd.bkt.clouddn.com/qr_wechat_github.jpeg)

**Comment by zhangjuxtu** [comment]
谢谢邀请。我给自己定了个目标，1. 先用把LEON3上的linux用起来；2. 尝试把AliOS在LEON3上用起来

**Comment by wanghaichuan941221** [comment]
二维码过期了怎么弄？

**Comment by librae8226** [comment]
@wanghaichuan941221 请联系管理员微信号 librae8226 手动拉入，见[上图](https://github.com/alibaba/AliOS-Things/issues/46#issuecomment-353371474)
