### ISSUE TITLE
esp8266配网的时间太短了？ 现在扫描才5 6秒

### ISSUE THREAD

**Issue by sofwu** [alibaba/AliOS-Things#467]
8266能配网的只会出现几秒，然后一直都不能配网了，这是什么问题？
![image](https://user-images.githubusercontent.com/20674516/43764772-f142aa64-9a60-11e8-997a-d046cf3edfd4.png)

**Comment by librae8226** [comment]
请确认按键以后 do_awss_active 是否有生效？方便的话请贴出完整日志。

**Comment by sofwu** [comment]
我要做灯具的闪烁配网没有按键的，上电后触发do_awss_active配网时间只有4~5s。

**Comment by sofwu** [comment]
[Receive_20180807211705.txt](https://github.com/alibaba/AliOS-Things/files/2266497/Receive_20180807211705.txt)

**Comment by sofwu** [comment]
我用的是rel1.3.2版本的，运行demo是linkkitapp。硬件是esp8266-12F，配网流程：我先给设备上电，然后操作app确认在闪烁再进行下一步，结果到了100%都没有配网成功。操作app时间大概10秒左右。

**Comment by sofwu** [comment]
ps：我先操作app到确认闪烁那一步，然后给设备上电同时点下一步，这样是可以配网成功的。

**Comment by librae8226** [comment]
请尝试如下步骤深入追查一下，看是否有帮助找到线索：
> 抓个空口包看一下手机有没有发出来，如果手机发出来了，设备上tcpdump一下，看看设备有没有收到包，如果设备也收到了，在sniffer_cb里面加个log，看看数据包有没有发给配网库

**Comment by braveheart007** [comment]
@sifwu 请问用AliOS给ESP8266配网需要做适配吗？还是直接配网就可以？

**Comment by librae8226** [comment]
@braveheart007 可以直接配网的

**Comment by yunyinkeji** [comment]
@librae8226 esp8266上确实有这样的配网问题，我也碰到的，未解决。

**Comment by librae8226** [comment]
尝试一下刚发布的2.0版，看是否还存在这个问题

**Comment by Torchwoods** [comment]
ESP8266烧录alios 2.0.0 ,只有在复位后的几秒钟事件内按配网按键，才能够正常接收到WIFI的SSID和密码，如果是运行一段时间后，在按配网按键，模块无法接收到SSID和密码，这是什么原因？我用EMW3060测试是没有这种情况发生的。

**Comment by xfdr0805** [comment]
> ESP8266烧录alios 2.0.0 ,只有在复位后的几秒钟事件内按配网按键，才能够正常接收到WIFI的SSID和密码，如果是运行一段时间后，在按配网按键，模块无法接收到SSID和密码，这是什么原因？我用EMW3060测试是没有这种情况发生的。

我也碰到了这个问题，你解决了吗

**Comment by sofwu** [comment]
@xfdr0805 没有解决
