### ISSUE TITLE
example里sensorapp无法运行

### ISSUE THREAD

**Issue by dupig** [alibaba/AliOS-Things#475]
直接把sensorapp工程编译的时候报错；
报错为缺少BUTTON_USER变量。自己定义了一个之后又报错BSP_LED_on(LED2)未定义，推测是引用文件有问题。

MAC，版本为8月9号的最新版

![image](https://user-images.githubusercontent.com/8230103/43988752-9c8bf46a-9d6e-11e8-9a2d-fe8acb58df18.png)

**Comment by Jianlong0430** [comment]
Hi @dupig , please give us more info for this question,

**Comment by Jianlong0430** [comment]
Hi @dupig ,
Please give more details for this question,
1, which code base you used, can you help give us the commit id and branch name to us?

**Comment by Jianlong0430** [comment]
Hi @dupig ,
Please give more details for this question, which code base you used, can you help give us the commit id and branch name to us? After confirmed, we will fix this issue asap.
