### ISSUE TITLE
developerkit板子获取不到ip？怎么解决

### ISSUE THREAD

**Issue by Zhou-JiaJun** [alibaba/AliOS-Things#492]
**Describe the bug**
我用be wifi 设置了WiFissid和密码，但是获取不到ip如何解决,是需要单独再烧一个WiFi的程序进去吗?

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by librae8226** [comment]
在串口 cli 里试试 `netmgr connect ssid password` 看能否获取到。
另外建议升级 developerkit 的 wifi 模组固件 https://github.com/alibaba/AliOS-Things/wiki/MW31_Upgrade_Guide
