### ISSUE TITLE
Github 速度慢

### ISSUE THREAD

**Issue by wming126** [alibaba/AliOS-Things#5]
github的速度真的很慢。每次clone代码都很长时间。请问有没有什么好的解决办法。

**Comment by tidyjiang8** [comment]
我clone下来速度还可以啊，也没翻墙啥的，1分钟就完成了

**Comment by wming126** [comment]
好的，可能是我网络的问题。非常谢谢。相信AliOS能够普及，我会一直关注并参与其中。
