### ISSUE TITLE
下载 AliOS Things 代码到哪里

### ISSUE THREAD

**Issue by huogewozidedandan** [alibaba/AliOS-Things#509]
问一个较弱智的问题，wiki中有一步要下载Alios Things 代码，这步是用什么下载，是用git吗？下载到哪里？怎样打开运行？
我用git下载成功后打开visual code完全找不到，求助~

**Comment by librae8226** [comment]
随意下载到哪里，vscode 打开代码的文件夹就好了

**Comment by huogewozidedandan** [comment]
thank you 搞定了
