### ISSUE TITLE
linkkitapp@esp8266

### ISSUE THREAD

**Issue by wangjiangck** [alibaba/AliOS-Things#510]
**Describe the bug**
我基于例子linkkitapp，修改物的三要素与tsl，添加了一点测试代码：设置了几个属性值并上报到云端。手机APP使用公版，用APP扫描产品发布-->设备配网二维码进行配网。发现有时候配网成功，但有时候配网不成功，配网成功时点击“开始使用”按钮后，界面显示“加载中”并一直卡在这个界面。观察log也发现一些错误

**environment**
1. branch(version): v1.3.3
2. Desktop OS(windows linux or macOS):linux 
3. example: linkkitapp

**Expected behavior**
期望可以正确配网并连接到阿里云，并能在公版APP上看到上传的属性值

**Screenshots**
![187692330290351784](https://user-images.githubusercontent.com/7702353/44627031-a4fc9400-a959-11e8-9853-4e892ce0155a.jpg)
![80573061178023936](https://user-images.githubusercontent.com/7702353/44627032-a8901b00-a959-11e8-847f-38fb96e456aa.jpg)
![108041382303836225](https://user-images.githubusercontent.com/7702353/44627034-af1e9280-a959-11e8-9330-0e84ac3ddb42.jpg)
[test.txt](https://github.com/alibaba/AliOS-Things/files/2321419/test.txt)

**Additional context**

**Comment by realonlyme** [comment]
这个是2个问题么?一个是配网时APP的问题，注意的是APP扫的码一定要和烧录至设备端的ProductID一致；

另外一个上传属性值是你设备端上行？还是云端下行？

**Comment by wangjiangck** [comment]
是设备端上行啊，APP扫描的码和烧录至设备端的ProductID是一致的

**Comment by braveheart007** [comment]
请问aos make linkkitapp@esp8266是不是得做适配之后才能用呢？ @wangjiangck

**Comment by mq9494** [comment]
问题解决了吗。我这里配网成功，但是绑定失败。不知道怎么办，求助啊
