### ISSUE TITLE
有大佬用过JS的UART来接收外设吗？

### ISSUE THREAD

**Issue by Zhou-JiaJun** [alibaba/AliOS-Things#513]
**Describe the bug**
我按照文档里给的代码来用JS来操作UART，不过这么测都是只能往外发，而不能接收，按照文档代码也不行，不知道大家是怎么接收的，能教教吗

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by librae8226** [comment]
@David-ZhouJiaJun 
板子是用的 Developer Kit? 你的 board_config.json 和 js 代码能贴出来不。如果有日志的话可以一起。

**Comment by jweihsz** [comment]
@David-ZhouJiaJun 
hello，可以这样试试：
```
var handle=UART.open('uart2');
if(handle>0){
var value = UART.write(handle,'hello\r\n');
UART.on(handle,function(data){     //监听串口数据
    console.log(data);    
});
} else {
	console.log('open uart2 fail!');
}
```

**Comment by David-ZhouJiaJun** [comment]
@jweihsz 这就是和文档里的一模一样呀，我就是这样写的，但是没用，你这样试过吗？可以接收吗？我这样写的时候on的回调方法一直不执行

**Comment by jweihsz** [comment]
@David-ZhouJiaJun 
on方法如果一直没数据，那么需要核查下：hal_uart_recv_II()这个方法是否OK，如果这个这个方法OK，可以再去看module_uart.c中的uart_handle()方法，这个方法中会调用hal_uart_recv_II(),看这里是否正常。这样大致就能定位出你提到的问题。

**Comment by David-ZhouJiaJun** [comment]
@jweihsz 好的，主要是不想用C写，难得可以用js写
