### ISSUE TITLE
移植 蓝牙驱动到alios

### ISSUE THREAD

**Issue by z5036602** [alibaba/AliOS-Things#514]
https://www.st.com/content/st_com/en/products/embedded-software/mcus-embedded-software/stm32-embedded-software/stm32cube-expansion-packages/x-cube-ble1.html

请问我想将这个款蓝牙驱动移植到alios里，请问有没有相关资料

**Comment by librae8226** [comment]
请参考[移植文档](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-BLE-Porting-Guide.zh)
或请直接查看源码 `kernel/protocols/bluetooth/`
如果使用HCI，请对接相应的 hci drvier
目前已支持的蓝牙 controller 是 nrf52xxx 系列，可以参考 `platform/mcu/nrf52xxx/`
