### ISSUE TITLE
BLE Mesh on ESP32

### ISSUE THREAD

**Issue by thanhhaiittalk** [alibaba/AliOS-Things#516]
I'm trying to use BLE mesh on ESP32, but it failed to advertise. Can anyone confirm if AliOS supported BLE mesh for ESP32. 
Thanks for your attention.

**Comment by librae8226** [comment]
For now, bluetooth of ESP32 in AliOS Things cannot work, because of some driver issue on ESP32 side.
However, we have tested BLE mesh with ESP32 as host and NRF51xxx as controller, it works fine.

**Comment by thanhhaiittalk** [comment]
@librae8226 Thanks for your help, can you describe more clearly what does "ESP32 as host" mean.
 I flashed blemesh_srv example to ESP32, but it doesn't advertise at all. Do I have wrong understanding of this example's purpose.
 
This example flashed: https://github.com/alibaba/AliOS-Things/tree/master/example/bluetooth/blemesh_srv

**Comment by xiaom-GitHub** [comment]
@thanhhaiittalk Yes, we observed that BLE mesh packet cannot be sent out with esp32 during testing. Therefore, we leverage the host + external controller model with two separate SoCs (esp32 and nrf51), esp32 as the BLE host and nrf51 as the BLE controller, HCI command request/response would be exchanged between host and controller via UART interface.

For blemesh_srv example, you are correct, however, we still need an external controller to help executing the scan or advertise at the Link Layer. In this case, we only program esp32 with the host side image. It will deliver the HCI cmds (e.g. scan, adv and etc) to the external controller via UART interface.

Please also refer to [this wiki](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-SIG-BLE-mesh-Setup-Guides) for more details.

**Comment by thanhhaiittalk** [comment]
@ALL Thanks so much for your support.
