### ISSUE TITLE
[ESP32] 如何烧写？

### ISSUE THREAD

**Issue by jackon** [alibaba/AliOS-Things#54]
除了直接用 esptool.py 之外，没有找到相关使用 aos 命令来进行烧写的文档。
VS 中用alios-stuido 的 Upload，输出为：
```
[INFO-Build] Run "aos make -e helloworld@esp32devkitc JTAG=jlink download"
```
settings.json 中已把 jlink 相关的删除了。

**Comment by junjiec** [comment]
aos make目前还没支持download，手动用esptool烧写或者alios studio烧写

**Comment by 0x1abin** [comment]
似乎只能用esptool手动烧录了，alios studio也不能直接烧录。

**Comment by junjiec** [comment]
@0x1abin 是的，IDE下次release会增加支持

**Comment by junjiec** [comment]
新版IDE已经支持esp32烧写
