### ISSUE TITLE
提供编译环境需要的镜像文件

### ISSUE THREAD

**Issue by braveheart007** [alibaba/AliOS-Things#541]
**Is your feature request related to a problem? Please describe.**
咱们自己搭建编译环境很浪费开发的时间

**Describe the solution you'd like**
就像乐鑫一样直接把编译环境搞好，下载导入直接用

**Additional context**
速度速度，厉害了我的阿里云！

**Comment by librae8226** [comment]
谢谢建议！
希望使用那种方式呢？
- docker (linux镜像环境)
- 一键安装脚本 (支持多系统，但需要管理员权限)
- IDE (请选择 VSCode, Keil, IAR, 其它请说明)

**Comment by braveheart007** [comment]
谢谢您这么速度就给了回复。
如果能给出多种选择当然可以满足不同开发人员的需求。
我在使用8266的过程中感觉乐鑫在这方面的方法是可取的。乐鑫使用Oracle VM VirtualBox,然后提供了相应的颈项环境，使用者只要下载后立刻就可以使用。当然如果阿里选定了自己的虚拟机环境并提供相应的镜像环境的话，那就太棒了！
从个人角度讲，我很期待阿里的 linux镜像环境。

**Comment by damon-yun** [comment]
我去过是嵌入式单片机开发，特别是这种微处理器，使用window环境的更多，强烈建议能够提供keil和iar的环境工程，使用命令行真的会增加不少开发时间

**Comment by librae8226** [comment]
@damon-yun 了解。我们正在完善这方面支持。
目前可以参考到 `build/scripts/keil.py` 和 `build/scripts/iar.py`，分别用于自动从makefile生成keil和iar的工程。由于这个功能还处于开发阶段，所以虽能使用，但仍有一些待解决的问题。
简单的使用方式如：
```
aos make  helloworld@b_l475e IDE=iar
```
这样会在 `out/helloworld@b_l475e/iar_project` 中生成相应的 iar 工程。

以 iar 为例，具体实现机制是在 `aos_target_config.mk` 中生成 `build/scripts/config_mk.py`, 将编译相关的信息转化成 python 的数据结构，然后调用 `build/scripts/iar.py` 来生成对应的 iar工程文件 .ewp, .eww

感兴趣可以先体验一下。

**Comment by xuhongv** [comment]
搭建了一个下午，还没成功。。。。

**Comment by librae8226** [comment]
@xuhongv 欢迎抛出问题来

**Comment by xuhongv** [comment]
@braveheart007  这里有已经弄好的镜像了！！

Alios-Thins教程连载 ①如何搭建阿里开源系统Alios-Things环境，烧录到乐鑫esp8266，打印 HelloWorld 。（附带镜像） 博客 https://blog.csdn.net/xh870189248/article/details/82562505
