### ISSUE TITLE
ESP8266+AliOS-Things blink example 

### ISSUE THREAD

**Issue by braveheart007** [alibaba/AliOS-Things#550]
**Is your feature request related to a problem? Please describe.**
AliOS-Things+ESP8266 按照https://github.com/alibaba/AliOS-Things/wiki/Quick-Start.zh 快速开始搭建了linux编译环境，编译helloworld通过，继续编译blink, aos [blink@esp8266发现编译没有通过，提示AliOS-Things定义的一系列GPIO接口均没有定义。这官方例程小弟没敢做任何改动，请百忙之中给小弟一点启发和指导！谢谢！

**Describe the solution you'd like**

**Additional context**

**Comment by librae8226** [comment]
@braveheart007 谢谢指出！
很抱歉带来的不便，这是因为目前代码里 esp8266 的 gpio hal 层接口缺失。
