### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by wming126** [alibaba/AliOS-Things#56]
1.自我感觉目前文档这块比较偏向于介绍和使用方法。理论知识要少一些，建议将一些用到的物联网协议标准过参考资料通过外链的形式给出。方便新手系统学习。
2. 自我感觉文档中添加一些典型的应用案例更好，方便大家快速开发。

**Comment by librae8226** [comment]
谢谢建议！

**Comment by wirelessVV** [comment]
跟协议相关的文档没有找到，比方说umesh里面，路由协议怎么实现，每一层的介绍。

**Comment by junjiec** [comment]
@wirelessVV 可以先参考这里：https://github.com/alibaba/AliOS-Things/wiki/AliOS--Things-Networking-Overview，进一步的文档我们还在准备中
