### ISSUE TITLE
基于developerkit的通用网络数据存储例程

### ISSUE THREAD

**Issue by msbtx** [alibaba/AliOS-Things#560]
**Is your feature request related to a problem? Please describe.**
alios-things现在可以连接阿里云使用各种服务，也支持文件系统，但是有一个很常用的功能好像没有。例如终端本地生成了容量较大（相对IOT设备来说）的数据，但是不适用类似link develop这种服务来同步数据。这个时候要一个通用的络数据存储服务，类似于网盘、FTP之类的服务。

**Describe the solution you'd like**
希望平台能够出一个基于developerkit cameraapp的例程，将单板拍照保存下来的图片文件同步到这样的网盘中。这个网盘服务可以是阿里云上的，或者可以由开发者指定任意的ftp服务器

**Additional context**

**Comment by realonlyme** [comment]
很好的建议 我们现在支持http2等上传方式 但是代码还没有完全暴露出来 后期会慢慢放出
