### ISSUE TITLE
建议针对ESP8266等主流硬件提供编译好的接入Link平台的串口透传固件

### ISSUE THREAD

**Issue by iotdev** [alibaba/AliOS-Things#566]
目前AliOS things提供源代码，需要用户基于源代码开发，由于Linux开发环境，加上要熟悉各种硬件平台，工作量挺大，对于开发能力强的团队，源代码定制性好，但是对于应用开发者，缺乏深度开发能力，更希望Alios针对特定的硬件平台，编译好现成的固件，并测试稳定可靠，用户只需要把固件烧写到硬件模块即可，这样用户无需了解AliOS的细节，直接专注于自己的应用即可。
该固件提供串口透传功能，应用开发者自己的MCU通过串口发指令给该模块，就可以自动将数据传输到Link平台，中间环节用户无需关心，这样就可以降低开发门槛，企业就会更愿意接入到Link平台，产品也可以更快落地。

**Comment by iotdev** [comment]
目前物联网使用较多的硬件：
WIFI类： ESP8266
以太网类： W5500
GPRS类：广和通G510，SIMCOM的SIM800/SIM900
NB-IOT类： BC95等

**Comment by braveheart007** [comment]
如果AliOS官方团队和乐鑫官方团队可以把适配给做好，那就太棒了。坐等两家大佬联合出手搞定接口适配。
