### ISSUE TITLE
hellowworld@cb2201编译失败

### ISSUE THREAD

**Issue by huogewozidedandan** [alibaba/AliOS-Things#570]
**Describe the bug**
提示找不到constant模型

![image](https://user-images.githubusercontent.com/42415011/45438470-cf847600-b6e9-11e8-8a44-8c0be6fb9a53.png)

**environment**
   windows

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by walker2048** [comment]
注意下python环境版本，aos需要的是python2，你看下错误提示，现在用的是python3.5了

**Comment by walker2048** [comment]
win10专业版的话，建议[docker镜像](https://gitee.com/walker2048/LearningAOS/blob/master/cases/misc/docker.md),
