### ISSUE TITLE
helloworld@cb2201编译失败问题

### ISSUE THREAD

**Issue by huogewozidedandan** [alibaba/AliOS-Things#582]
**Describe the bug**
win10操作系统，用vscode编译。有python3.5和python2.7两个版本。
为指定python版本，在vscode用户设置中修改了pythonPath为python2.7所在路径。
编译时报错说无法识别“aos”
我是用python2.7的pip安装了aos-cube的，目录里也有aos，不知道为什么会说无法识别。

**Screenshots**
![image](https://user-images.githubusercontent.com/42415011/45581905-5a779300-b8d9-11e8-9c91-7da09b745488.png)
![image](https://user-images.githubusercontent.com/42415011/45581914-8d218b80-b8d9-11e8-9bb2-888696ed3a65.png)

**Additional context**

**Comment by librae8226** [comment]
> 为指定python版本，在vscode用户设置中修改了pythonPath为python2.7所在路径。
编译时报错说无法识别“aos”
这个根本原因是 vscode 的 pythonPath 环境设置并不会对 integrated terminal 生效，只会对 python terminal 生效，而默认的编译构建烧录等行为都是依赖 integrated terminal 的。

**Comment by librae8226** [comment]
> 可是我让vscode自动安装aos-cube时，自动安装的是python3.5版本
可能确实还会有问题，尝试下把默认的 python 定向到 python 2.x，再让 vscode 自动安装

**Comment by huogewozidedandan** [comment]
谢谢，可是我不会定向python 2.x
![image](https://user-images.githubusercontent.com/42415011/45582596-649f8e80-b8e5-11e8-906d-4a8efe7d7726.png)
是改这里吗

**Comment by librae8226** [comment]
方法一：卸载 python 3.5
方法二：修改系统环境变量，使得命令行中执行 python 的时候默认找到 python 2

**Comment by librae8226** [comment]
如果以上方法都不喜欢，当然还有方法三，可以使用虚拟环境来管理版本，比如 conda，@walker2048 写过一篇教程 https://gitee.com/walker2048/LearningAOS/blob/master/cases/misc/install_miniconda.md

**Comment by walker2048** [comment]
ruby，python，node.js等等语言，多版本并存会存在非常多的问题。这个是很多前辈碰得头破血流的，最后不得不开发各种虚拟环境管理软件。建议不要死磕，想要两个python版本直接安装在系统里共存。
