### ISSUE TITLE
钉钉的交流群进不了，可以新建几个群么

### ISSUE THREAD

**Issue by LittleFatHero** [alibaba/AliOS-Things#616]

**Comment by librae8226** [comment]
可以，但现在还没建起来，对开源项目来说IM群多的缺点是不利于知识沉淀。
有问题先提到这里吧。

**Comment by Dean0315** [comment]
> **Describe the bug**
> 
> **environment**
> 
> 1. branch(version):
> 2. Desktop OS(windows linux or macOS):
> 3. example:
> 
> **Expected behavior**
> 
> **Screenshots**
> 
> **Additional context**

AliOS Things技术交流群-Banana：23130352（钉钉搜索群号），新群已经有了

**Comment by BigBigWolf-AI** [comment]
这个新群根本搜不到呀，用钉钉，不行你们试试

**Comment by BigBigWolf-AI** [comment]
> > **Describe the bug**
> > **environment**
> > 
> > 1. branch(version):
> > 2. Desktop OS(windows linux or macOS):
> > 3. example:
> > 
> > **Expected behavior**
> > **Screenshots**
> > **Additional context**
> 
> AliOS Things技术交流群-Banana：23130352（钉钉搜索群号），新群已经有了

这个群用钉钉搜不到呀，搜不到呀，搜不到呀！！！

**Comment by Dean0315** [comment]
> > > **Describe the bug**
> > > **environment**
> > > 
> > > 1. branch(version):
> > > 2. Desktop OS(windows linux or macOS):
> > > 3. example:
> > > 
> > > **Expected behavior**
> > > **Screenshots**
> > > **Additional context**
> > 
> > 
> > AliOS Things技术交流群-Banana：23130352（钉钉搜索群号），新群已经有了
> 
> 这个群用钉钉搜不到呀，搜不到呀，搜不到呀！！！

![image](https://user-images.githubusercontent.com/42260772/46642169-3fcace00-cba8-11e8-878b-c1e784977a31.png)
