### ISSUE TITLE
关于移植hal_uart的串口中断问题，以及LOG输出

### ISSUE THREAD

**Issue by virnop** [alibaba/AliOS-Things#628]
小白提问：（使用版本AliOS 2.0.0 编译环境IAR）

1. STM32L4_Cube中的hal_uart_stm32l4.c，为什么串口中断没有用 krhino_intrpt_enter(); 和 krhino_intrpt_exit(); ？是不需要还是忽视了？什么时候需要使用？什么时候不需要使用？烦请大佬解答 谢谢。

2. Utility中log的使用问题：hal_uart_stm32l4.c中的串口发送使用了Cube HAL库中的阻塞函数 HAL_UART_Transmit(...) ，但是对于RTOS来说 非阻塞 的处理方式岂不更好？于是我改写了下，使用 HAL_UART_Transmit_IT(...) 和 aos_sem_wait(...) 配合。发现LOG输出被打断了。查看发现LOG的实现是三段式的printf宏定义，没有用互斥锁保护，这里是不是不太合适？

**Comment by realonlyme** [comment]
1. 我看了源码，是仍然具有这2个函数的，位于AliOS-Things\platform\mcu\stm32l4xx_cube\hal\hal_uart_stm32l4.c中的USART1_IRQHandler()等函数 如果你是使用了STCubeMX自动生成了这些ISR，请将其注释掉，用stm32l4xx_cube\hal下的代码

2. 我看了下，2.0的代码中hal_uart_send()是信号量和中断方式的发送方式实现的，之前版本可能有没有实现的版本，并且在2.0中的代码用#if 0 ... #endif 关掉了
另外log目前现存的打印方式由于很比较混乱，但是OS本身提供的LOG机制最终会调用到csp_printf，是有保护的。
`#ifndef csp_printf
__attribute__((weak)) int csp_printf(const char *fmt, ...)
{
    va_list args;
    int ret;

    ret = aos_mutex_lock(&log_mutex, AOS_WAIT_FOREVER);
    if (ret == 0) {
        va_start(args, fmt);
        ret = vprintf(fmt, args);
        va_end(args);

        fflush(stdout);
    }

    aos_mutex_unlock(&log_mutex);

    return ret;
}
#endif`

请确认您是否使用了rel_2.0.0分支
