### ISSUE TITLE
VS Code使用alios studio如何进入virtualenv中build项目

### ISSUE THREAD

**Issue by travmygit** [alibaba/AliOS-Things#632]
问题描述：
在MAC环境下使用pip安装依赖包出现了些问题，故在virtualenv安装依赖包，但是在使用alios studio来build项目的使用，使用的还是系统环境，但是我想在virtualenv里使用alios studio，如何修改配置？

本机环境：
OSX 10.13.5 + python 2.7.15

**Comment by walker2048** [comment]
你的意思是不是，要在VScode的GUI环境，点击按钮实现编译功能？
可以考虑用docker搭环境，目前我在做一个node.js的工具来配合docker环境，封装常用命令来实现GUI功能，以及减少命令行的输入。重阳节前后可以完成第一版测试版。

**Comment by librae8226** [comment]
@travmygit 这个功能在vscode 自带的终端里面确实略有限制。
目前的解决办法是通过自动安装aos-cube的方式完成你所说的功能。该步骤会用 virtualenv 创建虚拟环境到 `~/.aos/python-venv/` 下面，alios-studio 加载起来的时候会在全局的 `process.env.PATH` 中带上这个路径，从而使得 vscode 自带的终端可以找到 aos-cube。
另外如果你希望使用手动创建的 virtualenv 环境，把它创建在 `~/.aos/python-venv/` 即可。

**Comment by travmygit** [comment]
@librae8226 已经使用这个方法解决问题了，多谢:)
