### ISSUE TITLE
关于树莓派的问题

### ISSUE THREAD

**Issue by andypengzai** [alibaba/AliOS-Things#640]
今天在群里问了，说是支持，但是这部分代码还没有开源，请问开源吗？我在x86架构 ubuntu系统下编译是可以运行的。现在想让这个系统跑到我的 arm linux核心板上，请问有什么办法吗？

**Comment by walker2048** [comment]
其实树莓派都可以跑Linux了，还跑alios干啥呀。。。
linkkit和各种云平台都有SDK，再折腾个系统多累
