### ISSUE TITLE
F1和F7 H7上面移植好的ALIOS THINGS 有吗，需要用到

### ISSUE THREAD

**Issue by cornrn** [alibaba/AliOS-Things#653]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by librae8226** [comment]
具体需要用到哪一款？

**Comment by cornrn** [comment]
F103RET6 和H743IGT6

**Comment by librae8226** [comment]
目前暂无支持
