### ISSUE TITLE
win10系统下，developerkit开发板连接电脑后，设备管理器中看不到开发板

### ISSUE THREAD

**Issue by yxg820627** [alibaba/AliOS-Things#656]
在win10下，已经安装了st-link驱动，开发板连接电脑后，设备管理器中找不到开发板，通过STM32 ST-LINK Utility也找不到开发板，开发板的programing灯一直闪烁，该如何解决？

**Comment by walker2048** [comment]
有板子上有两个usb接口，确认连接到stlink口，另外确认stlink跳线设置正确。或者直接去钉钉群问厂家

**Comment by yxg820627** [comment]
连接的是stlink口，跳线如下图，这样设置的正确吗？


![_20181018100300](https://user-images.githubusercontent.com/4961807/47127023-e9534300-d2bd-11e8-8515-03843c12fff5.jpg)

**Comment by walker2048** [comment]
确认下驱动是否安装正确，也可以在 ST-LINK Utility看看是否找得到stlink。如果用别的stm32开发板能连上，就得找厂家看看是不是板子有问题了。如果别的stm32开发板也连不上，就是驱动或者系统问题（ghost版缺失文件）。
