### ISSUE TITLE
MQTT topic is forced to start with slash

### ISSUE THREAD

**Issue by wanglingsong** [alibaba/AliOS-Things#66]
I'm trying to run a mqtt app on my device. After several unsuccessful test, I noticed that the mqtt client of AliOS will check the topic name and if the topic name does not start with slash "/", error would be return. Anyone could explain why?

**Comment by wanglingsong** [comment]
Referenced code here:
https://github.com/alibaba/AliOS-Things/blob/master/framework/connectivity/mqtt/mqtt_client.c#L235

**Comment by caveguy** [comment]
We have fixed this issue. Thank you for your advice.
