### ISSUE TITLE
k_ringbuf.c存在可能的逻辑bug

### ISSUE THREAD

**Issue by zhoucsu** [alibaba/AliOS-Things#682]
**Describe the bug**
可以选择创建两种链表，在创建RINGBUF_TYPE_FIX链表时，没有对数据块大小进行合理设置有可能导致后面的push函数产生越界

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):
3. example: 
假设选择创建的ringbuf种类为RINGBUF_TYPE_FIX，申请的ringbuf总大小为7，每一个数据块的大小为3；那么连续push两个块进去再pop出一个后，再push进去一个则会使指针指向创建的ringbuf之外的区域。

**Expected behavior**
指针跑飞

**Screenshots**

**Additional context**

**Comment by zqyhcf** [comment]
ringbuf_init是个内部接口，在调用其的外部接口中都已经有了约束，包括krhino_ringbuf_init、krhino_fix_buf_queue_create以及queue创建时调用的queue_create。

**Comment by librae8226** [comment]
@zhoucsu 谢谢反馈！
如上提到，该接口预期是给内部代码使用的，所以目前不会出现描述中问题。但出于代码健壮性考虑，是否方便提交一个 pull request 给我们？
