### ISSUE TITLE
无法通过串口打印long long类型

### ISSUE THREAD

**Issue by taksing-leung** [alibaba/AliOS-Things#687]
**Describe the bug**
无法通过串口打印long long类型

**environment**
1. branch(version): 2.0
2. Desktop OS(windows linux or macOS):win10 esp8266
3. example: 
linkkitapp
**Expected behavior**
比如下面代码:
long long a = 1541050898757;
printf("lld! %lld\n",a);

串口会打印出 
lld! ld

而无法输出正确的值

**Screenshots**

**Additional context**

**Comment by xiaowenxia** [comment]
@taksing-leung 请使用这种方法：
