### ISSUE TITLE
研究了半天，没大看明白， 还是想给REPO的Master提些建议。

### ISSUE THREAD

**Issue by csnol** [alibaba/AliOS-Things#69]
这个REPO还处在搭建期， 热心的代码贡献者（或合作者 ）都希望把自己的体系放进阿里的平台中，可以理解。我也盼望着国产MCU或IC模块产业壮大起来， 但在代码结构方面还想几条建议： 
    
1.  感谢MXCHIP人员的努力和贡献。但却大量照搬了MiCO的代码， STM32系列的移植也是使用MiCO的模版。有些细节上需要注意。    
见 AliOS-Things/platform/mcu/include/platform_peripheral.h 第27行
``` C++ 
MCU-specific data types are defined in <MiCO-SDK>/platform/MCU/<MCU_family>/platform_mcu_peripheral.h
```
但这个库文件却不是所有MCU的通用文件，在其它非MiCO移植的MCU目录下是没有的。另外还有些MiCO的参数和结构命名。**是不是AliOS-Things其实是基于MiCO的RTOS的？**  即便是这样，也最好是移植，不要照搬。    
**建议添加一个变体variants目录，将特殊的定义和宏都放在变体variants目录。**    

还有一点，在STM32F和L系列中ST的HAL 库，CMSIS库（可以用在IAR和Keil），但用了MiCO编程结构和习惯，学习成本太高。

2. ESP8266仅进行网络层和串口flash空间分区的定义， 找不到引脚结构，HSPI，内部RTC，DeepSleep， 唤醒等等相关定义和注解。不会是只使用了ESP8266 的AT命令模式吧？！ 现在还不明白ESP-8266作为核心（不依赖其它MCU）的项目如何操作， 我是在PlateformIO和Arduino上编译的。

3. 引导+框架+应用的多Bin结构的FOTA想法很不错，虽然Repo是Apache 2.0 的开源授权，但还是建议不要包含太多无法解读的".bin"和“.a“二进制文件。理解并尊重专利，不过我不会在我的“**联网**”项目中使用不知道源码的底层文件，尤其还是WiFi相关的文件，实在懒得写完芯片再用WireShark、端口扫描类程序做安全测试。
建议说明这些bin和静态库a文件的编译过程和方法。我看很多二进制文件是可以GIT到源码自己编译出来的。

之所以写这么多，是希望AliOS-Things 能越做越好，能真正用起来，让中国自主的IoT项目越来越多。 

以后会常来看看。
 
祝好！  
CS.Nol

**Comment by junjiec** [comment]
@csnol 首先非常感谢这么多诚恳的建议。

AliOS Things的初衷是构建一个生态，为广大厂商及普通开发者提供一个易用可用的物联网系统。
我们有很多生态合作伙伴，这个代码仓库里面有很多他们的贡献，我们避免去重复造轮子，把有限的精力投入到像您提到的多Bin FOTA这类特性的开发上。针对你的几个问题：
1，MXCHIP是我们最早的合作伙伴之一，我们早期的目标之一是让MXCHIP的生态可以平滑过渡到AliOS Things。源码中还遗留部分您指出的问题，实际的mcu对接参考 [移植指南](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Porting-Guide)
2，ESP8266目前只是一个基础部分，我们正和乐鑫的同学一起努力完善中
3，WiFi的一些相关库都是2进制，我理解这是业界现状，我们也尊重合作伙伴保护自己的知识产权的意愿。其余部分我们主要是考虑到开发者没必要去了解这些细节，但是您的建议很好，我们会逐渐补充一些说明。

欢迎以后多提交代码，及各种意见，保持交流，共同打造一个对业界有用的系统。
