### ISSUE TITLE
Windows下编译ESP8266卡死在 Making config file for first time

### ISSUE THREAD

**Issue by siberianfox** [alibaba/AliOS-Things#690]
$ aos make linkkitapp@esp8266
aos-cube version: 0.2.63
Making config file for first time
这个是什么问题，一直无法解决，是否要用linux编译。

**Comment by xiaowenxia1** [comment]
@siberianfox 目前esp8266的工具链在windows环境下无法正常工作哈，需要在linux环境中才能正常编译esp8266，windows下可以考虑使用docker。

**Comment by siberianfox** [comment]
> @siberianfox 目前esp8266的工具链在windows环境下无法正常工作哈，需要在linux环境中才能正常编译esp8266，windows下可以考虑使用docker。
明白了，非常感谢！

**Comment by siberianfox** [comment]
好的，明白了，感谢！
