### ISSUE TITLE
请问传感器类数据应该怎么控制上报频率？

### ISSUE THREAD

**Issue by wangym307** [alibaba/AliOS-Things#696]
我需要开发一款wifi传感器的应用，功能是在手机app面板上可以监控传感器的实时测量值value_sensor。
这意味着我需要实时向云端当前的传感器数值value_sensor，应该如何控制上报的频率呢？
- 如果我希望数据足够实时，那么上报频率需要很快，比如2秒一次，这会造成大量的流量消耗。
- 如果将这个频率控制的很慢，比如10分钟一次，那么流量减少了，同时造成数据的实时性很差，当前app上看到的值可能是10分钟之前才报上来的，这个时候显示的值已经不正确了。
请问我应该如果处理这种上报频率和流量消耗之间的冲突呢？

**Comment by xiaowenxia1** [comment]
你说的**上报频率**和**流量消耗**  本来就是2个矛盾体，跟宽带的**速率**和**带宽**是一个道理，不过可以给个建议，就是数据有变化（或者变化幅度大）的时候传输频率快一点，数据变化不大的时候传输频率慢一点，跟视频的压缩算法一个意思。

**Comment by wangym307** [comment]
那如果这个传感器的数值是一直都变化很快的呢，而且变化幅度一直很大，目前做的传感器就是这种情况。

**Comment by redchenjs** [comment]
@wangym307 本地压缩，批量上传

**Comment by wangym307** [comment]
@redchenjs 应用场景是实时查看，历史数据不需要记录，也不需要绘制历史变化曲线，所以批量的方式也不太适用。
