### ISSUE TITLE
vscode插件创建项目失败

### ISSUE THREAD

**Issue by chenyulun** [alibaba/AliOS-Things#698]
**Describe the bug**
vscode插件创建项目失败
主动安装也不行
➜  ~ pip list | grep constant
constant                           0.0.4
constants                          0.6.0
**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS): macOS
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**

Create Project Fail.Traceback (most recent call last): File "/Users/chenyulun/.aos/python-venv/bin/aos", line 7, in <module> from aos.aos import main File "/Users/chenyulun/.aos/python-venv/lib/python3.6/site-packages/aos/aos.py", line 26, in <module> from .util import * File "/Users/chenyulun/.aos/python-venv/lib/python3.6/site-packages/aos/util.py", line 10, in <module> from constant import * ModuleNotFoundError: No module named 'constant'

**Comment by xiaowenxia1** [comment]
@chenyulun aos-cube只支持python2.7哈，你的当前环境是python3，所以导致冲突了，请使用python2安装aos-cube，比如如下指令：

**Comment by chenyulun** [comment]
不能够吧！不支持Python3，我用pip2重新装一遍就行了吗

**Comment by xiaowenxia1** [comment]
@chenyulun 你装个python2哈，然后用pip2装aos-cube

**Comment by chenyulun** [comment]
➜  ~ pip -V
pip 18.1 from /Users/chenyulun/anaconda3/lib/python3.6/site-packages/pip (python 3.6)
是不是要先切这个？

**Comment by chenyulun** [comment]
/Users/chenyulun/.aos/python-venv/lib下面的已经是python3.6

**Comment by xiaowenxia1** [comment]
不明白你啥意思？看起来有可能python虚拟环境也是用python3装的，最好是删除掉python-venv重新再试试。

**Comment by chenyulun** [comment]
我使用
➜  ~ which pip
/Users/chenyulun/anaconda3/bin/pip
➜  ~ conda create -n python27 python=2.7
切换环境了

**Comment by xiaowenxia1** [comment]
那你现在还有啥问题不？

**Comment by chenyulun** [comment]
没有删除干净依赖，还是读取了py3.6的东西，我本来对py不熟悉，我自己摸索着吧，谢谢了
