### ISSUE TITLE
为什么linkkitapp 配网要在上电几秒内触发do_awss_active()函数才可以

### ISSUE THREAD

**Issue by taksing-leung** [alibaba/AliOS-Things#711]
**Describe the bug**
超过5秒，触发无效。
是不是应该上电后检测flash有没有保存wifi账号密码，如果没有自动进入等待配网状态？

**environment**
1. branch(version): 2.0
2. Desktop OS(windows linux or macOS):win10 esp8266
3. example: linkkitapp

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiaowenxia1** [comment]
@taksing-leung esp8266烧录的时候，烧录模式选qio哈，就没有这个问题了。

**Comment by taksing-leung** [comment]
@xiaowenxia1 你是对的,要用支持QIO的flash才行
