### ISSUE TITLE
otaapp问题

### ISSUE THREAD

**Issue by zhi-z** [alibaba/AliOS-Things#725]
我根据官网给的otaapp走了一遍，这个例程在Linux host能够运行成功，但是我在developerkit开发板上运行就不行了，使用netmgr connect 进行联网会失败，这个是什么问题？

**Comment by xiaowenxia** [comment]
目前master分支的developerkit代码还存在问题，请使用[developer](https://github.com/alibaba/AliOS-Things/tree/developer)分支哈。
