### ISSUE TITLE
windows 10  vscode build  慢

### ISSUE THREAD

**Issue by hgnid** [alibaba/AliOS-Things#735]
**Describe the bug**
点了build 大概一分钟 才开始编译

**environment**
1. branch(version): master
2. Desktop OS(windows linux or macOS):windows 
3. example: helloword

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hgnid** [comment]
![image](https://user-images.githubusercontent.com/13962945/49203818-a029ff00-f3e4-11e8-9eb3-ea18901672c4.png)

**Comment by hgnid** [comment]
> 谢谢你给我们提的issues，能不能给一下当前windows的性能（ctrl+shift+p 然后 输入developer: startup performance可以查看详细的windows性能检测）

![image](https://user-images.githubusercontent.com/13962945/49203843-b5069280-f3e4-11e8-95df-b6834dbf7bd7.png)

**Comment by xiaowenxia** [comment]
收到，谢谢。

**Comment by hgnid** [comment]
关闭了  Windows Defender 之后 问题解决，不知道为啥点编译，windows defender就狂扫描

**Comment by xiaowenxia** [comment]
> 关闭了 Windows Defender 之后 问题解决，不知道为啥点编译，windows defender就狂扫描

关闭了 Windows Defender 之后，打开时间是多少秒呢？

**Comment by hgnid** [comment]
> > 关闭了 Windows Defender 之后 问题解决，不知道为啥点编译，windows defender就狂扫描
> 
> 关闭了 Windows Defender 之后，打开时间是多少秒呢？

大概2秒后就开始编译了，不关defender 把 rg.exe 在defender设置中 配置成例外，好像也可以。
