### ISSUE TITLE
developerkit中linkkitapp无法配网

### ISSUE THREAD

**Issue by riyuezhixing** [alibaba/AliOS-Things#739]
**Describe the bug**

**environment**
1. branch(version): master
2. Desktop OS(windows linux or macOS):ubuntu18.04
3. example: 

**Expected behavior**
配网成功

**Screenshots**
![screenshot from 2018-12-02 22-18-37](https://user-images.githubusercontent.com/6939604/49340861-53625480-f680-11e8-8247-c61b1b7d6204.png)

**Additional context**

**Comment by xiaowenxia** [comment]
你说的无法配网成功具体是指什么问题呢？
