### ISSUE TITLE
developerkit不知如何操作key, led

### ISSUE THREAD

**Issue by riyuezhixing** [alibaba/AliOS-Things#746]
**Is your feature request related to a problem? Please describe.**
文档不够详细, 想控制key, led都有点麻烦.

**Describe the solution you'd like**
完善文档, 按照硬件原理, alios接口介绍, 代码试例讲述硬件操作过程.  把developerkit打造成alios things最佳开发板.

**Additional context**

**Comment by xiaowenxia** [comment]
谢谢你的建议。关于key、led的操作可以参考这篇文档哈：https://mp.weixin.qq.com/s/Fk_eMhukdFF_esZiMszHwA
