### ISSUE TITLE
关于 linkkitapp 工程的日志打印问题？

### ISSUE THREAD

**Issue by xuhongv** [alibaba/AliOS-Things#748]
**描述**：在当前的主分支最新（也即是 2.0 `版本)，我想把底层打印屏蔽不要输出，按照文档说明调用方法 ``` IOT_CloseLog();``` ，发现还是照旧打印底层系统！

**环境**
1. branch(version):  2.0 `版本
2. Desktop OS(windows linux or macOS): docker
3. example: linkkitapp 

**Screenshots**

![2](https://user-images.githubusercontent.com/25237870/49681321-b7e73e80-fada-11e8-910f-3621005d2457.png)

**Comment by librae8226** [comment]
在 linkkit_start() 的参数处设置 log level 再试试

**Comment by xuhongv** [comment]
有待下个版本更新修复！
