### ISSUE TITLE
在 linkkitapp 代码工程中的linkit_data_arrived（）无法触发？

### ISSUE THREAD

**Issue by xuhongv** [alibaba/AliOS-Things#749]
**Describe the bug**：
- 根据《linkkitapp》的文档说明，我是输入命令符 `  aos make linkkitapp@esp8266 ` ，成功编译代码代码，也在`linkkit_example_solo.c`代码发现已经设置了云端回调方法 `linkit_data_arrived` ，但是我在 `linkit_data_arrived` 方法并没有收到云端服务器下发的信息，却在底层打印了出来！

`  
   linkkit_ops_t linkkit_ops = {

        .on_connect       = on_connect,   
        .on_disconnect    = on_disconnect,   
        .raw_data_arrived = raw_data_arrived,
        .thing_create     = thing_create,    
        .thing_enable     = thing_enable,    
        .thing_disable    = thing_disable,  
        .thing_call_service =  thing_call_service,
        .thing_prop_changed = thing_prop_changed, 
        .linkit_data_arrived =  linkit_data_arrived, 

    };
`

**environment**
1. branch(version): 2.0
2. Desktop OS(windows linux or macOS): linux
3. example:  linkitapp

**Screenshots**

![3](https://user-images.githubusercontent.com/25237870/49681401-0cd78480-fadc-11e8-9ae7-45149bb1ff5c.png)

**Comment by librae8226** [comment]
`linkit_data_arrived`这个回调是废弃的
云端下发服务进`thing_call_service`回调，下发属性进`thing_prop_changed`回调

**Comment by xuhongv** [comment]
TSL数据格式有误导致不回调！已经修复！
