### ISSUE TITLE
linkkitapp在使用阿里智能APP进行配网时失败

### ISSUE THREAD

**Issue by jxjxjinxin** [alibaba/AliOS-Things#755]
阿里智能APP V3配网时输入ssid和pwd后     程序开始解析ssid和pwd   但是zconfig_checksum_v3校验失败       显示如下：wps crc check error: recv 0xf07 != 0x1e07      这个是什么原因  该如何解决

**Comment by xiaowenxia** [comment]
目前配网的话，用的是公版app:“智能家居” 来配网的哈，具体请参考：https://living.aliyun.com/doc#muti-app.html

**Comment by jxjxjinxin** [comment]
@xiaowenxia 恩  谢谢，  那我不用飞燕平台用阿里物联网平台创建的产品似乎无法使用公版app:“智能家居” 来配网， 就算传入相应的product_key   APP也无法进行配网，公版APP是只对应在飞燕平台上创建的product嘛， 是否有相应的SDK可以进行app开发对接Linkkitapp 但又不需要传product_key的配网
