### ISSUE TITLE
MT2625平台如何移植OTA功能

### ISSUE THREAD

**Issue by OrangeNan** [alibaba/AliOS-Things#768]
你好，MT2625平台如何移植OTA功能，贵方有没有什么指导文档或者别的一些教程？
谢谢！

**Comment by OrangeNan** [comment]
你好，
    这些大概看了，感觉帮助不是很大；我使用的sdk版本是iotkit-embedded-2.3.0，主要是代码移植方面的一些问题，通过MQTT方式来实现OTA，编译下来会报出缺少很多函数实现和结构体，比如IOT_MQTT_Construct -> IOT_SetupConnInfo -> HAL_Kv_Get -> kv_open -> pthread_mutex_init，缺少的是最后的这个init，类似的还有很多。想请问下，这些是只能自己实现，还是说我移植的代码有问题？
谢谢！

**Comment by xiaowenxia** [comment]
@OrangeNan 你只是用了iotkit-embedded-2.3.0，没有使用AliOS-Things吗？如果只使用iotkit-embedded-2.3.0的话，需要适配iotkit-embedded的HAL层：[Linkkit HAL接口清单](https://code.aliyun.com/edward.yangx/public-docs/wikis/user-guide/linkkit/Prog_Guide/HAL/Required_APIs)

**Comment by OrangeNan** [comment]
好的，明白了，谢谢！
