### ISSUE TITLE
win10系统VS code使用alios-studio配置开发环境的bug

### ISSUE THREAD

**Issue by zongkai28** [alibaba/AliOS-Things#769]
**Describe the bug**
win10系统下，python已经预装，在命令行下可正常运行python和pip命令。
VS code安装alios-studio后提示："please install python and pip first"，非常令人费解。而且即便不理会这个提示，命令行手工安装aoc-cube等工具后，在后续用alios-studio编译时仍然会报python的异常。
检查发现alios-studio插件的extension.js文件中pip命令名竟然都是pip2，修改后就可以正常运行alios-studio了，而且压根都不需要再参考wiki上繁琐的环境配置流程，alios-studio全部帮忙搞定，包括后续安装aos-cube、编译器等等。
改动点如下：
![image](https://user-images.githubusercontent.com/2351796/50228533-28e3fb80-03e3-11e9-89ee-2cd06bff540a.png)
alios-studio这么好，就不要因为这点小问题困扰初学者了。

**environment**
1. branch(version): alios.alios-studio-0.10.8
2. Desktop OS(windows linux or macOS):windows 10 x64
3. example: 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2351796/50228251-70b65300-03e2-11e9-8e71-6801e70675c3.png)

**Additional context**

**Comment by xiaowenxia** [comment]
@zongkai28  **非常感谢你的建议:smile:，目前使用pip2的原因是因为aos-cube只支持python2，如果pip指令是python3的pip的话，就会导致安装或者运行aos-cube错误。你的系统不支持pip2指令的话，应该是python2版本太旧了（`python** --version`），这个我们欠考虑，非常抱歉。后续我们也计划先识别当前python环境，然后再使用pip 安装。

> 根都不需要再参考wiki上繁琐的环境配置流程，alios-studio全部帮忙搞定，包括后续安装aos-cube、编译器等等。

谢谢你的赞同！:+1: AliOS-Studio的初衷就是最简化开发环境和流程，让开发者无门槛就能快速开始开发AliOS-Things。
如果你有关于AliOS-Studio更好的建议和想法的话，非常欢迎一起交流一下哈。:smile:

**Comment by hanfengcan** [comment]
可以把 scripts 也加入系统路径

**Comment by xiaowenxia** [comment]
> 可以把 scripts 也加入系统路径

@hanfengcan 你说的是啥scripts？

**Comment by hanfengcan** [comment]
Python27\Scripts @xiaowenxia 

![d6ea98a8-f289-4673-ae36-528ac6ed7ec6](https://user-images.githubusercontent.com/4559753/50319106-7e61fa80-0500-11e9-825b-1ef7e2806ca3.png)

**Comment by xiaowenxia** [comment]
@hanfengcan 是的，我们的[相关wiki文档](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Windows-Environment-Setup)里面也说明了要把python加入到Path环境变量里面的：
![](https://camo.githubusercontent.com/92496d01e4b4e240bb1f5b57e150e94a6ca4bba2/68747470733a2f2f696d672e616c6963646e2e636f6d2f7466732f544231536c48796a716d67534b4a6a53737069585858794a4658612d3739382d3638382e706e67)

**Comment by hanfengcan** [comment]
这个只是加 python 到系统路径, 不手动把 scripts加入系统路径的话, 会找不到pip

**Comment by zongkai28** [comment]
为你们的热心回复赞一个👍
我确实是python初学者，一直偷懒用anaconda，所以系统里确实没找到过pip2.exe，这下又涨知识了👏

**Comment by xiaowenxia** [comment]
@hankchan 谢谢你的建议，关于 `alios studio增加对anaconda的支持` 我们会认真评估一下哈。

**Comment by gwfighter** [comment]
第一次编译就出现错误，不知道是不是和这个有关，只是为了实现一个简单例程：helloworld
---------------------------------------------------------------------------------------------------------


> Executing task: aos make helloworld@aaboard_demo -c config <

aos-cube version: 0.3.1
Traceback (most recent call last):
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\aos\__main__.py", line 82, in main
    cli(None)
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\aos\commands\make.py", line 33, in cli
    make_build(make_args)
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\aos\commands\make.py", line 259, in make_build
    _run_make(['-e', '-f build/Makefile', make_args])
  File "c:\users\administrator\.aos\python-venv\lib\site-packages\aos\commands\make.py", line 285, in _run_make
    make_cmd_str = ' '.join([make_cmd, 'HOST_OS=' + host_os, 'TOOLS_ROOT=' + tools_dir] + list(arg_list))
  File "c:\users\administrator\.aos\python-venv\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 3: invalid continuation byte
[AliOS-Things] ERROR: Unknown Error: 'utf8' codec can't decode byte 0xd6 in position 3: invalid continuation byte
