### ISSUE TITLE
AliOS-Things对STM32F4支持以太网口

### ISSUE THREAD

**Issue by dy604** [alibaba/AliOS-Things#773]
AliOS-Things是否对STM32F4的以太网口驱动进行了适配支持呢？

**Comment by xiaowenxia** [comment]
@dy604 我们支持[stm32f429zi-nucleo](https://github.com/alibaba/AliOS-Things/tree/master/board/stm32f429zi-nucleo)，stm32f429zi-nucleo就是用的ETH来连云的。
