### ISSUE TITLE
alios things us级或者ms级延时函数在哪查找，还有任务切换频率等设置参数？

### ISSUE THREAD

**Issue by smf408fze** [alibaba/AliOS-Things#774]

**Comment by xiaowenxia** [comment]
@smf408fze  AliOS-Things没有us级延时函数哈，ms级延时函数为[aos_msleep()](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-API-KERNEL-Guide#50-aos_msleep)，任务切换频率的宏为`RHINO_CONFIG_TICKS_PER_SECOND`，在`k_config.h`中定义，`k_config.h`位于`board/xxxx`中。
