### ISSUE TITLE
win10的Ubuntu子系统下使用AliOS Things的问题

### ISSUE THREAD

**Issue by nostalgia-w** [alibaba/AliOS-Things#775]
1. 首先我在win10下安装了Ubuntu16.04的子系统
方法：设置——>更新和安全——>针对开发人员——>开发人员模式
控制面板——>程序——>程序和功能——>启用或关闭Windows功能——>适用于Linux的Windows子系统——>确定 （然后重启）
在应用商店中搜索Ubuntu，选择Ubuntu16.04，点击获取进行下载及安装

2. 在配置环境的时候，无法安装libss1-dev:i386
![c07 49uw gh lzg pav dwb](https://user-images.githubusercontent.com/38066417/50416107-d0d14d00-0859-11e9-8089-b33b5e959968.png)

**Comment by xiaowenxia** [comment]
@nostalgia-w WSL的ubuntu16.04版本和ubuntu16.04是有一点系统架构上的差异的，目前好像还没法安装libss1-dev:i386 这样的安装包。不过安装libss1-dev 这些包也是为了能够运行app@linuxhost 这样的代码，如果你不运行linuxhost的话，就不需要安装libss1-dev包，直接安装aos-cube就可以使用。

**Comment by nostalgia-w** [comment]
好的，aos-cube安装没问题。
但还有一个问题。
我之前开发这个项目的时候是rel_1.3.1的版本，用的是另一台电脑的虚拟机，但是太卡了所以换成现在这台win10的电脑。所以我暂时用的AliOS Things的版本是rel_1.3.1的版本。

在使用命令 aos make helloworld@esp8266的时候，编译不成功。打印如下：

![xhp2p bzkf msw5emuf h](https://user-images.githubusercontent.com/38066417/50416925-2576c700-085e-11e9-9c4f-ecb5e0df47e3.png)
![2io chp3 u mh0 x_ybc z8](https://user-images.githubusercontent.com/38066417/50416938-31628900-085e-11e9-9a20-5fd396483780.png)

中间有一部分没截图

**Comment by xiaowenxia** [comment]
WSL目前编译1.x.x的代码分支确实有这个问题，暂时还不知道什么导致的，但是master分支是正常的。

**Comment by nostalgia-w** [comment]
嗯，用master分支编译的aos make helloworld@esp8266，可以编译成功，然后程序烧录到板子里能正常运行。

**Comment by walker2048** [comment]
可以考虑用docker镜像哦，比WSL要好用，而且速度也快。[地址](https://cloud.docker.com/repository/registry-1.docker.io/walker2048/easy-aos)

**Comment by zlasd** [comment]
出现以上warning的原因应该是windows和linux的换行符不同导致*.in文件解析失败，我在wsl中重新clone了一份代码之后解决了。
