### ISSUE TITLE
alios things 临界区？

### ISSUE THREAD

**Issue by smf408fze** [alibaba/AliOS-Things#784]
程序运行时，怎么禁止任务调度

**Comment by xiaowenxia** [comment]
@smf408fze 请问你在什么情况下需要使用到`禁止任务调度`功能呢？如果是保护资源的话，用互斥锁就行。

**Comment by smf408fze** [comment]
esp32 采集18B20温度，有个启动过程引脚拉低750us的要求，如果这时候任务调度会导致传感器初始化失败
有个问题，自定义的
void delay_us(uint16_t i)
{
    while(i--);
}
delay_us(2)实际用示波器测得延时会达到5ms以上，为什么？

**Comment by zqyhcf** [comment]
开关调度使用：krhino_sched_disable和krhino_sched_enable；开关中断使用：RHINO_CPU_INTRPT_DISABLE和RHINO_CPU_INTRPT_ENABLE；
直接while循环会被编译器优化掉，可以使用汇编代替，实际时间和指令周期以及cycle频率相关；
建议直接使用ROM内ets_delay_us

**Comment by xiaowenxia** [comment]
> esp32 采集18B20温度，有个启动过程引脚拉低750us的要求，如果这时候任务调度会导致传感器初始化失败
> 有个问题，自定义的
> void delay_us(uint16_t i)
> {
> while(i--);
> }
> delay_us(2)实际用示波器测得延时会达到5ms以上，为什么？

目前esp32任务调度间隔是10ms，delay_us()有可能会被任务调度打断，所以delay_us()的实际执行时间是有可能大于5ms的。

**Comment by smf408fze** [comment]
好的

**Comment by smf408fze** [comment]
I (1014972) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
每次ESP芯片IO口输入输出切换都会有日志打印输出，这个怎么关闭
aos_set_log_level(AOS_LL_NONE); 这个已经设置到aos_ll_none了

IOT_SetLogLevel和aos_set_log_level有什么区别，有没有详细点的文档介绍这些对应的函数的作用？
