### ISSUE TITLE
服务器端应该发什么样格式的json数据，才能让设备端正确的解析出来我所发的消息体呢？

### ISSUE THREAD

**Issue by mmabluesky** [alibaba/AliOS-Things#785]
rt  ，
我在服务端，发了一小段json数据，通过规则引擎转发到了我运行aliOs things的设备上，设备上跑的是linkkitApp Demo，我设备端串口显示是能收到这小段json数据，但是底下SDK一直报解析失败， 所以我想问的是，发送时我应该添加怎么的头，才能确保设备端正确解析数据呢

![image](https://user-images.githubusercontent.com/17948377/50514931-6419b500-0adc-11e9-875c-51601dc5b97d.png)

![image](https://user-images.githubusercontent.com/17948377/50515064-4ac53880-0add-11e9-8b8e-a1c6e6052368.png)

**Comment by mmabluesky** [comment]
@xiaowenxia  夏老大

**Comment by xiaowenxia** [comment]
@mmabluesky 云端下发到设备端的消息格式是一套alink的格式的，需要按照alink的格式发送，具体的格式可以看云端的下发日志：

**Comment by xiaowenxia** [comment]
@mmabluesky 看起来是用Maven仓库的形式存放源码的，具体不太清楚哈。

**Comment by mmabluesky** [comment]
@xiaowenxia 
嗯 ，本来是想看看thingPropertyPost函数的具体实现来着，
