### ISSUE TITLE
mk3080运行linkkit 原demo通过iot上的OTA升级失败？

### ISSUE THREAD

**Issue by MrZhouWang** [alibaba/AliOS-Things#791]
**Is your feature request related to a problem? Please describe.**
OTA升级报错

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/23515496/50635935-2d85e380-0f8f-11e9-8ebb-0b049dd23dc4.png)
![image](https://user-images.githubusercontent.com/23515496/50635953-3d052c80-0f8f-11e9-886d-0f25dd021107.png)

**Additional context**

**Comment by xiaowenxia** [comment]
@MrZhouWang 能不能描述一下：
* 哪个分支？
* 哪个example？ linkkitapp？

看起来你要进行ota升级的binary很大：`1402672`，请确认一下这个binary是否有问题。
