### ISSUE TITLE
kv set的一个问题

### ISSUE THREAD

**Issue by nostalgia-w** [alibaba/AliOS-Things#797]
环境：
        使用的芯片是esp8266，自己建立的项目里加入了cli功能，使用linkkitapp连接智能生活开放平台
目的：
        在烧录完程序后，通过串口使用kv set命令写入devicename和devicesecret。
问题：
       在使用kv set命令的时候，写devicename没有问题，kv set key xxxxxx (with enter)，就可以成功写入。但是写devicesecret的时候，需要在发完kv set key xxxxxxxx（with enter） 后再发送一条 空信息（with enter），才能成功。但是我之前用的是rel1.3.1，没有这个问题，devicename和devicesecret使用同样操作就可以写进去。
      devicename ：test_06    ，  devicesecret ：wQ1xOzFH3kLdjCTLfi8Xbw4otRz0lHoq
      这两个是参考代码里，devicename和devicesecret，就用这两个长度写，就有这个问题，如果devicesecret减少到wQ1xOzFH3kLdjCTLfi8Xbw4otRz0l的长度，就可以跟devicename一样的操作写进去了，不需要再发一个  空信息（with enter）。
      用了几个串口工具都是这样的情况。

**Comment by QianTony** [comment]
请问下你直接通过aos_kv_set函数接口可以连续set成功不？ 要确认下问题是出在kv还是cli字符解析处理问题

**Comment by nostalgia-w** [comment]
![k e3fgzkpjg ksfsn f oe8](https://user-images.githubusercontent.com/38066417/50815782-57f1eb00-1359-11e9-985c-e6af8a7cfa94.png)

类似这样的? 这个运行没有问题，能写入成功，也能用kv list读出来
要试试data是长数据吗？

![rdn_ l _7hq7ku2j ch lqg](https://user-images.githubusercontent.com/38066417/50816170-b7042f80-135a-11e9-98b1-2e3c7a3eb115.png)

像这样写，能写进去，kv list读出来是完整的
![arl85ugl0 b3s vurslfy](https://user-images.githubusercontent.com/38066417/50816246-ee72dc00-135a-11e9-8ef0-f0c2f7b49fb2.png)

**Comment by xiaowenxia** [comment]
@nostalgia-w 目前有一个已知的问题，就是esp8266 一次性只能接受`<=30`个字符

**Comment by nostalgia-w** [comment]
就是我之前用的是rel_1.3.1，没有这个问题。
现在换成master分支（不然不能再win10的子系统编译），然后遇到了这个问题。
智能生活开放平台的secret长度刚好超过30个字符，-_-
不过也还好，多发一个 回车就可以了。
只是跟之前不一样了，所以问一下是什么问题，看看能不能解决

**Comment by xiaowenxia** [comment]
谢谢你的反馈哈。
