### ISSUE TITLE
用飞燕平台测试APP，使用哪个例程能实现给developerkit开发板配网并连接

### ISSUE THREAD

**Issue by YeFly9** [alibaba/AliOS-Things#829]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by xiaowenxia** [comment]
使用`linkkitapp`哈。

**Comment by YeFly9** [comment]
嗯嗯，我试了，修改了三元组，打开了APP不能发现设备，设备重启也没反应，这是设备的串口打印的数据：
start-----------hal
trace config close!!!

[000000]<V> aos framework init.

俐	蟬tart-----------hal
trace config close!!!

[000000]<V> aos framework init.

**Comment by xiaowenxia** [comment]
@YeFly9 目前developerkit 配网这一块还是有问题的。。

**Comment by gwfighter** [comment]
请问developerkit配网现在搞定了么？正打算买他们的板子玩玩呢。

**Comment by gwfighter** [comment]
> @YeFly9 目前developerkit 配网这一块还是有问题的。。

请问developerkit配网现在搞定了么？正打算买他们的板子玩玩呢。

**Comment by gwfighter** [comment]
@xiaowenxia 请问developerkit配网现在搞定了么？正打算买他们的板子玩玩呢。

**Comment by gwfighter** [comment]
@YeFly9 有最近进展了么？可以通过APP配网了么？

**Comment by xfdr0805** [comment]
我也是卡到配网这里，设备连接云平台没有问题
