### ISSUE TITLE
使用VSCode编译ESP8266_RTOS_SDK时，在烧录时烧录失败，求助

### ISSUE THREAD

**Issue by YeFly9** [alibaba/AliOS-Things#832]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
错误提示：A fatal error occurred: Failed to connect to ESP8266: Timed out waiting for packet header

**Additional context**

**Comment by YeFly9** [comment]
![image](https://user-images.githubusercontent.com/46669992/51293266-193eed80-1a49-11e9-8179-d047e3e494c1.png)

**Comment by xiaowenxia** [comment]
你这个问题不应该问我们:flushed:，应该问问乐鑫那边。。。https://github.com/espressif/ESP8266_RTOS_SDK
