### ISSUE TITLE
关于alios基础信息：缺少文件？支持的硬件较少？

### ISSUE THREAD

**Issue by dingguoxing** [alibaba/AliOS-Things#84]
stm系列板卡配置中没有*.mk文件？
不知道是不是我下载代码不全？还是……
通过网页浏览也没有发现mk文件？

另外，支持的开发板比较少，支持的核种类更少，只支持Cortex-M4？

**Comment by junjiec** [comment]
目前b_l475e有mk，其他的是给予keil／iar工程，我们正在增加makefile支持
b_l475e可以参考这里：https://github.com/alibaba/AliOS-Things/wiki/stm32-networking
支持的cpu非常丰富，arm架构支持m0，m3，m4等，xtensa等也支持
参考platform/arch目录

**Comment by dingguoxing** [comment]
谢谢；
m0,m3是platform\arch\arm\armv6m\armcc\m0plus 路径下的吗？
m7支持吗？

**Comment by junjiec** [comment]
m0使用platform\arch\arm\armv6m\，gcc／armcc／EWARM代表不同编译器的版本
m3,m4共用platform\arch\arm\armv7m\

m7的支持进行中，下个版本会发布，敬请期待

**Comment by librae8226** [comment]
Much more architectures have been supported now so close it.
Feel free to reopen it once any further help needed.
