### ISSUE TITLE
蓝牙例程breeze无法正常发送数据

### ISSUE THREAD

**Issue by linyuanding** [alibaba/AliOS-Things#841]
我只能在接收数据的回调函数中才能把数据APP才能收到消息，我自己写一个定时器去发消息APP就收不到消息了。
希望有人能告诉我为什么在接收数据的回调中能发送数据，在回调以外就不能发送了？

**Comment by luxuguang-leo** [comment]
Hi，
直接调用breeze_post是OK的，但你需要保证发消息不block yloop事件，因为breeze组件依赖底层的yloop机制，如果在上层使用while循环会阻碍yloop机制，推荐使用方式：

main{
aos_post_delayed_action( , simulate_data, NULL);
aos_loop_run();
}

void simuate_data()
{
    //
    //breeze_post();
   //aos_post_delayed_action(, simulate_data, NULL)
}

**Comment by linyuanding** [comment]
感谢，我试试这个方法。

**Comment by linyuanding** [comment]
嗨！
我用了你说的方法去发送数据，还是不行 
![1127f3d51d2323e3b73c088fbee4963](https://user-images.githubusercontent.com/42051405/51579124-c22e9200-1efa-11e9-9aad-4a84a95e703e.png)
![2c70fd5e255da6b7959f68e42eb8bde](https://user-images.githubusercontent.com/42051405/51579126-c3f85580-1efa-11e9-80f4-e174cdb6b1b8.png)

**Comment by luxuguang-leo** [comment]
发送数据的判断条件应该是认证通道结束之后，而不是蓝牙连接

**Comment by linyuanding** [comment]
按照你说的，我把判断条件了为了，认证成功之后再去发送，依然没成功。
![image](https://user-images.githubusercontent.com/42051405/51587892-3f6afe80-1f1d-11e9-94a7-2c26e6c84d91.png)

**Comment by linyuanding** [comment]
没有错误信息啊，log还是跟之前一样，breeze_post（）调用完成后触发dev_status_changed_handler（），打印“dev_status_changed(): Tx-done.”表示发送完成
![image](https://user-images.githubusercontent.com/42051405/51594804-3df70180-1f30-11e9-8c6d-0fe96bb79597.png)

**Comment by linyuanding** [comment]
![image](https://user-images.githubusercontent.com/42051405/51594940-88787e00-1f30-11e9-8635-bad9dea0f297.png)

**Comment by luxuguang-leo** [comment]
这个demo的APP的逻辑应该是在收到非自己发送的数据处理后不会打印，显示Tx-done应该是数据通过indication发送成功了。

**Comment by linyuanding** [comment]
你的意思是我的数据已经发送过去了，APP没有打印出来？

**Comment by luxuguang-leo** [comment]
你可以抓包或者在协议栈加打印来确认indication有无发送成功

**Comment by linyuanding** [comment]
我在底层打印显示成功，我买个抓包器试试。
