### ISSUE TITLE
求助，example中linkkitapp的配网手机端APP是使用哪个呀？

### ISSUE THREAD

**Issue by mq9494** [alibaba/AliOS-Things#844]
刚开始接触AliOS-Things，使用的ESP8266，在阿里物联网平台创建了产品，然后编译linkkitapp后下载进行配网，使用阿里智能APP不成功，想问一下该怎么正确的操作。

**Comment by xiaowenxia** [comment]
@mq9494 在这里哦：[公版APP](https://living.aliyun.com/doc#muti-app.html)，需要配合[智能生活开放平台](https://living.aliyun.com/)使用。

**Comment by mq9494** [comment]
好的，明白了。谢谢~
