### ISSUE TITLE
Timer开启后剩余时间如何获取

### ISSUE THREAD

**Issue by sukangjian** [alibaba/AliOS-Things#845]
typedef struct {
    klist_t       timer_list;
    klist_t      *to_head;
    const name_t *name;
    timer_cb_t    cb;
    void         *timer_cb_arg;
    sys_time_t    match;
    sys_time_t    remain;
    sys_time_t    init_count;
    sys_time_t    round_ticks;
    void         *priv;
    kobj_type_t   obj_type;
    uint8_t       timer_state;
    uint8_t       mm_alloc_flag;
} ktimer_t;
开启的定时器的剩余时间怎么获取？，对remain变量进行打印，打印出来的值是我创建时设置的周期值；
定时器已经开启在运行打印，当前的tick值也能打印出来 ，打印读取结构体的 timer_state  状态也没问题

**Comment by xiaowenxia** [comment]
能提供一下以下信息吗？

**Comment by xiaowenxia** [comment]
@sukangjian 能提供一下这些信息吗？

- 哪个分支？
- 相关的代码贴一下。
- 运行日志也贴一下看看。

**Comment by zqyhcf** [comment]
timer->match表示为该定时器的运行期望执行时刻，其等于g_timer_count，则表示定时器时间到。

**Comment by sukangjian** [comment]
> timer->match表示为该定时器的运行期望执行时刻，其等于g_timer_count，则表示定时器时间到。



> @sukangjian 能提供一下这些信息吗？
> 
> * 哪个分支？
> * 相关的代码贴一下。
> * 运行日志也贴一下看看。

![image](https://user-images.githubusercontent.com/46954421/51591840-033d9b00-1f29-11e9-9783-66b0032b9c33.png)
![image](https://user-images.githubusercontent.com/46954421/51591944-5c0d3380-1f29-11e9-999e-ede71bee919f.png)

**Comment by sukangjian** [comment]
> timer->匹配表示为该定时器的运行期望执行时刻，其等于g_timer_count，则表示定时器时间到。

假如我开启了一个10s定时器，我要如何获取它还有多长时间到呢？用remain打印出来的值为周期值而且没变化

**Comment by zqyhcf** [comment]
如上所述，打两个值：g_timer_count,timer->match

**Comment by sukangjian** [comment]
![image](https://user-images.githubusercontent.com/46954421/51595672-3f292e00-1f32-11e9-93e6-b06eeea6ed72.png)
![image](https://user-images.githubusercontent.com/46954421/51595693-4c461d00-1f32-11e9-88fd-f694755fe6e1.png)
还是不能获取剩余的时间，g_timer_count没有动态变化，只进入中断函数才发生变化

**Comment by sukangjian** [comment]
> 如上所述，打两个值：g_timer_count,timer->match

![image](https://user-images.githubusercontent.com/46954421/51649173-47c74600-1fbe-11e9-9870-c76128a8017b.png)

**Comment by zqyhcf** [comment]
使用g_tick_count替换g_timer_count可以看到每次的递增tick，g_timer_count也是有意义的，只是不是每次来一次tick就增长，只会有定时器时间到了才刷新。你这个log也能看出来值已经刷新了。
