### ISSUE TITLE
DEBUG时出现找不到debugger的情况

### ISSUE THREAD

**Issue by yayayi333** [alibaba/AliOS-Things#849]
![4hz w b7uw y qti q ijj](https://user-images.githubusercontent.com/47095326/51812516-d1438480-22ec-11e9-900d-b8ad9c119fbf.png)

按照提示进行开发环境配置，在启动DEBUG时，出现如图提示信息。请问是什么原因？

**Comment by xiaowenxia** [comment]
你的`MIDebuggerPath`是怎么写的呢？

**Comment by yayayi333** [comment]
"customLaunchSetupCommands": [],
            "launchCompleteCommand": "exec-run",
            "osx": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb"
            },
            "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb"
            },
            "windows": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb.exe"
            }

**Comment by xiaowenxia** [comment]
`arm-none-eabi-gdb.exe` 所在的目录是不是不在你的Path环境变量里面？ 终端里面看看能不能运行`arm-none-eabi-gdb.exe`.

**Comment by yayayi333** [comment]
![6xwy983hw7q h8f1 92z6ex](https://user-images.githubusercontent.com/47095326/51812792-10bea080-22ee-11e9-83bc-353b9c8a7773.png)
测试可以运行

**Comment by yayayi333** [comment]
可以运行，然后出现新的报错，ST Utilty确认安装完成。
![6gwbl uz v yiqn gs](https://user-images.githubusercontent.com/47095326/51813410-17024c00-22f1-11e9-8438-6e98504992c2.png)

**Comment by xiaowenxia** [comment]
这里面没有使用ST-Utilty哦，使用的是./build/cmd/win32/st-util.exe 这个软件，你确认下这个路径对不对。

**Comment by xiaowenxia** [comment]
@yayayi333 AliOS-Things目录下面会生成`.gdbinit`，看看这里面的st-util.exe 配置的是否正确？

**Comment by xiaowenxia** [comment]
@yayayi333  `aos make clean` 然后重新编译哦。

**Comment by yayayi333** [comment]
直接修改.gdbinit中的路径是否可行？

**Comment by xiaowenxia** [comment]
也可以的，但是`.gdbinit`是`aos make app@board`的时候自动生成的，下次编译的时候会自动更改.gdbinit.

**Comment by xiaowenxia** [comment]
👍
