### ISSUE TITLE
对于aos_test.c中的任务栈溢出问题

### ISSUE THREAD

**Issue by sukangjian** [alibaba/AliOS-Things#855]
![image](https://user-images.githubusercontent.com/46954421/52627544-98143280-2ef0-11e9-9a55-c309f719da92.png)
![image](https://user-images.githubusercontent.com/46954421/52627622-c560e080-2ef0-11e9-8649-957cfcd78a17.png)
![image](https://user-images.githubusercontent.com/46954421/52627753-11ac2080-2ef1-11e9-9dd1-9d575b705834.png)

**Comment by sukangjian** [comment]
程序执行创建任务task1成功后，未进入task1函数中，打印任务栈溢出，程序跑飞；不清楚为什么程序会在这里打印任务栈溢出，将stack_size加大到6K还是打印任务栈溢出

**Comment by xiaowenxia** [comment]
能不能描述的再详细一些：
1.  哪个分支？
2.  哪个board？

**Comment by sukangjian** [comment]
> 能不能描述的再详细一些：
> 
> 1. 哪个分支？
> 2. 哪个board？

AliOS-Things/test/testcase/certificate_test/aos_test.c
M0核armv6m

**Comment by xiaowenxia** [comment]
哪个分支呢？ master还是rel_1.3.3还是其他的分支？

在 board/ 目录里面对应哪个板子型号呢？

**Comment by sukangjian** [comment]
> 哪个分支呢？ master还是rel_1.3.3还是其他的分支？
> 
> 在 board/ 目录里面对应哪个板子型号呢？
rel_1.3.0,STM32L073RZ-Nucleo

**Comment by xiaowenxia** [comment]
好的。

**Comment by sukangjian** [comment]
问题已解决，原因是创建测试任务的栈的值设置的太小，导致测试时任务栈溢出
