### ISSUE TITLE
请问PWM控制，调用哪个接口咧！

### ISSUE THREAD

**Issue by phoenixfengqi** [alibaba/AliOS-Things#858]
**Is your feature request related to a problem? Please describe.**
请问PWM控制，调用哪个接口咧！
int32_t hal_pwm_init(pwm_dev_t *pwm);
int32_t hal_pwm_start(pwm_dev_t *pwm);
int32_t hal_pwm_stop(pwm_dev_t *pwm);
是这些接口吗，发现芯片级有其对应的PWM API，但是没有实现这几个接口

**Describe the solution you'd like**

**Additional context**

**Comment by xiaowenxia** [comment]
如果芯片的代码里面没有实现这些接口的话，那就是这款芯片暂时不支持`hal_pwm_*`这些接口哈，需要自己手动实现，或者直接调用芯片的pwm接口。

**Comment by phoenixfengqi** [comment]
明白，谢谢！
