### ISSUE TITLE
VS Code IDE 增加辅助调试窗口

### ISSUE THREAD

**Issue by wizephen** [alibaba/AliOS-Things#860]
为方便用户调试、使用VS Code IDE，强烈建议VS Code IDE  alios-studio 开发小组增加如下调试辅助窗口：
1.  CPU 通用寄存器窗口；
2.  Memory/Peripheral I/O 读写窗口；
3.  反汇编显示窗口；

谢谢！

**Comment by xiaowenxia** [comment]
谢谢你的建议哈，我们会评估一下，非常感谢。:+1: 😄
