### ISSUE TITLE
linkkitapp连接linkdevelop(IOT物联网平台)配网手机端APP无法登陆

### ISSUE THREAD

**Issue by jonesfu** [alibaba/AliOS-Things#864]
在mk3060平台上通过linkkitapp连接物联网平台，注意不是智能生活平台. 我按照linkdevelop的做法搭建了一个可视化Android APP, 配置完成后平台生成一个APP，安装后要手机号登陆，但是问题是该APP不认任何手机号码，该怎么解决？

**Comment by xiaowenxia** [comment]
Android APP的问题需要[提交工单](https://selfservice.console.aliyun.com/ticket/createIndex?spm=5176.2020520129.103.2.316f46ae7vKJEt)问一下哦。

**Comment by jonesfu** [comment]
账号问题解决了，在物联网平台->移动应用开发->可视化搭建左边有三个菜单，分别是编辑，配置，账号。要进入账号页面加入用户后，手机APP端才能登陆。

不过又有另一个问题，该APP没有配网功能，已经发工单再问了。以上信息给大家参考。

**Comment by xiaowenxia** [comment]
谢谢分享。！

**Comment by gwfighter** [comment]
看来提交工单和这里提交issue不是一个部门哦？

**Comment by gwfighter** [comment]
> 账号问题解决了，在物联网平台->移动应用开发->可视化搭建左边有三个菜单，分别是编辑，配置，账号。要进入账号页面加入用户后，手机APP端才能登陆。
> 
> 不过又有另一个问题，该APP没有配网功能，已经发工单再问了。以上信息给大家参考。

有最新消息了么？
