### ISSUE TITLE
mk3060平台如何提高uart FIFO size

### ISSUE THREAD

**Issue by jonesfu** [alibaba/AliOS-Things#867]
mk3060平台缺省的UART FIFO SIZE是256，希望能提高到1024，但是查看platform/moc108/moc108.mk发现3060平台所有功能都是依赖moc108.a这个library无法修改。

自己尝试把platform/moc108/hal/uart.c编译进去，但是函数执行没有效果，不知道要如何修改了。。。

**Comment by xiaowenxia** [comment]
你怎么更改FIFO SIZE的呢？

**Comment by jonesfu** [comment]
1. 修改platform/moc108/hal/uart.c中#define UART_FIFO_SIZE 1024
2. 同时把函数名改掉避免跟moc108.a冲突，比如hal_uart_init改成high_hal_uart_init
3. 修改platform/moc108/moc108.mk加入$(NAME)_SOURCES +=  hal/uart.c

这样可以编译通过，也可以调用，但在3060上实际执行的时候收不到任何uart数据

**Comment by xiaowenxia** [comment]
那这个`high_hal_uart_init()` 在哪里调用到呢？

**Comment by jonesfu** [comment]
在helloworld.c主程序中调用
