### ISSUE TITLE
alios-things环境中如何使用http方法

### ISSUE THREAD

**Issue by jonesfu** [alibaba/AliOS-Things#868]
目前大部分云都提供http resetfull api, 在alios-things环境中要如何使用http方法？

**Comment by xiaowenxia** [comment]
@jonesfu 你是想要哪种http方法呢？http client还是http server ？

**Comment by jonesfu** [comment]
http client

**Comment by xiaowenxia** [comment]
`http client` 目前还没有实现，如果你的开发板使用的是lwip的话，可以参考lwip提供的示例实现一套哦。

**Comment by xiaowenxia** [comment]
也可以参考下linkkit里面的http client代码实现：https://github.com/alibaba/AliOS-Things/blob/master/middleware/linkkit/sdk-c/src/infra/utils/misc/utils_httpc.c

**Comment by jonesfu** [comment]
好的，我参考修改下
