### ISSUE TITLE
alios studio menuconfig怎么打开

### ISSUE THREAD

**Issue by scarleast** [alibaba/AliOS-Things#874]
**Describe the bug**

**environment**
1. branch(version): rel2.0
2. Desktop OS(windows linux or macOS):Mac
3. example: 

想问一下，alios studio的make menuconfig在哪里可以打开？自己移植一些已有的app，LED,按键以及linkkitapp，很好奇makefile是怎么生成的，完全看不懂/app/example的这些Makefile的规则啊。

**Comment by xiaowenxia** [comment]
@scarleast 目前2.0的代码还不支持make menuconfig，makefile文档可以参考这份文档：[AliOS Things 构建系统](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-build-system.zh)。

**Comment by scarleast** [comment]
@xiaowenxia 感谢！
