### ISSUE TITLE
linkitapp使用什么加密方式？

### ISSUE THREAD

**Issue by scarleast** [alibaba/AliOS-Things#880]
**Describe the bug**
linkitapp使用的是什么加密方式？TLS吗？

**environment**
1. branch(version): rel2.0
2. Desktop OS(windows linux or macOS):mac
3. example: 

看文档介绍，说阿里云物联网平台MQTT接入的时候支持TLS之类，想问下，Alios linkitapp里面通过MQTT连接云，是否使用了TLS加密？如果需要，应该在修改什么地方？

**Comment by xiaowenxia** [comment]
linkkitapp使用了一套鉴权的机制保证安全性，同时也默认mqtt需要使用加上TLS进行安全通讯。 linkkitapp这些功能都有，不需要更改哈。
