### ISSUE TITLE
连接飞燕平台，WiFi配网

### ISSUE THREAD

**Issue by scarleast** [alibaba/AliOS-Things#884]
**Describe the bug**
我希望通过alios的linkkitapp demo连接飞燕平台，飞燕平台并没有提供PRODUCT_SECRET，而在使用APP配网阶段，实际测试必须从物联网平台找到对应产品的PRODUCT_SECRET填入才能保证设备的正常wifi配网，否则配网会出现失败的情况，应该是广播的加密数据利用了PRODUCT_SECRET。

想问一下，连接飞燕平台，使用其公版APP配网，是否可以不设置PRODUCT_SECRET，完成配网阶段。
**environment**
1. branch(version): rel2.0
2. Desktop OS(windows linux or macOS): Mac
3. example:

**Comment by xiaowenxia** [comment]
@scarleast 飞燕平台是有提供`PRODUCT_SECRET`的，在`功能定义` 页面的右边面板里有。

**Comment by scarleast** [comment]
好的，感谢
