### ISSUE TITLE
单总线传感器如何在sensor 框架下创建

### ISSUE THREAD

**Issue by comporsa** [alibaba/AliOS-Things#885]
**Is your feature request related to a problem? Please describe.**
例如18b20温度传感器，只需要一根总线，进行gpio 电平控制即可。在执行sensor_obj_register时，只有DEV_INT，DEV_DATA_READY，DEV_FIFO这三个选项比较接近，但它们也是为中断型引脚准备的。请问这种类型的传感器是否可以加入sensor框架？如果可以，应该如何操作？

**Describe the solution you'd like**

**Additional context**

**Comment by walker2048** [comment]
alios的hal库里，并没有1 wire的协议头文件定义，默认也没有此协议的调用函数。具体请查阅device\sensor\hal\sensor_drv_api.c。如果需要从sensor组件添加具体的传感器，仍需添加1 wire协议的头文件和对应执行函数，另外还可能需要增加其他文件。
