### ISSUE TITLE
编译  tinyengine_app@developerkit  问题

### ISSUE THREAD

**Issue by kennycmt** [alibaba/AliOS-Things#890]
**Describe the bug**
in  windows ，branch:master, aos make  tinyengine_app@developerkit , found a error:

build/aos_target_config.mk:334: *** Unknown component: middleware.linkkit.iotkit - directory or makefile for component not found. Ensure the middleware/linkkit/iotkit directory contains iotkit.mk. Stop.
make: *** No rule to make target 'out/tinyengine_app@developerkit/config.mk', needed by 'main_app'. Stop.

**Comment by xiaowenxia** [comment]
@kennycmt sorry, `tinyengine_app`  not available in master, please try [developer](https://github.com/alibaba/AliOS-Things/tree/developer) branch.
