### ISSUE TITLE
stm32f4xx_cube的HAL Driver库应该要更新了

### ISSUE THREAD

**Issue by comporsa** [alibaba/AliOS-Things#898]
**Describe the bug**
alios things 里的这个库旧了点，居然没有stm32f4xx_hal_exti.c这个文件。

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiaowenxia** [comment]
@comporsa 目前是没有的，要使用的话你可以自己手动添加进去。:smile:
