### ISSUE TITLE
0.3版的aos如何自动生成keil或iar工程？

### ISSUE THREAD

**Issue by comporsa** [alibaba/AliOS-Things#912]
老版本的做法无法使用。请及时修改相关的wiki以给出明确的说明。

**Comment by xiaowenxia** [comment]
请参考这个哈：
* [自动生成 Keil MDK 工程](https://dev.iot.aliyun.com/doc/detail/aliosthings?spm=a2c56.12366940.0.0.7eb25206lY7J3i#keilautogen.html)
* [自动生成 IAR 工程](https://dev.iot.aliyun.com/doc/detail/aliosthings?spm=a2c56.12366940.0.0.7eb25206lY7J3i#iarautogen.html)

**Comment by xiaowenxia** [comment]
@comporsa 针对2.1代码的话，需要使用下面的指令生成keil或者iar：

```sh
# 生成默认配置
aos make app@board -c config

# 生成keil工程同时编译
aos make IDE=keil
```

或者
```sh
# 生成默认配置
aos make app@board -c config

#  仅生成keil工程
aos make export-keil
```
