### ISSUE TITLE
windows10 下vscode 烧写错误

### ISSUE THREAD

**Issue by DorBlack** [alibaba/AliOS-Things#926]
---host_os:Win32
[ERROR]: Firmware upload failed!

[AliOS-Things] ERROR: "scons" returned error code -1.
[AliOS-Things] ERROR: Command "scons -f c:\AliOS-Things-rel_2.1.0\build/ucube.py COMMAND=upload APPLICATION=mqttapp BOARD=stm32l476rg-nucleo" in "c:\AliOS-Things-rel_2.1.0"
---

**Comment by xiaowenxia** [comment]
@DorBlack 有详细的命令输出log麽，这么点信息看不出来啥问题。
