### ISSUE TITLE
aos_uart_send()问题

### ISSUE THREAD

**Issue by kkong522** [alibaba/AliOS-Things#93]
1. aos_uart_send()和vfs有什么关系？为什么放在vfs.c里面？
2. 不能写死用uart0，必须是可以配置的，不同的板子，debug uart不一定是UART0

**Comment by jason-sophia** [comment]
最新版本已经将该函数移出，并提供可配置的接口，还未正式发布，谢谢建议

**Comment by librae8226** [comment]
谢谢 @jason-sophia
有任何疑问欢迎继续提出 😊  @kkong522
