### ISSUE TITLE
针对开发板的差分升级功能

### ISSUE THREAD

**Issue by kentzh** [alibaba/AliOS-Things#935]
developerkit开发板，希望验证差分升级功能，以方便后期连接NB模块时使用，但发现云端似乎不支持该开发板，能否还有其它方法进行验证？

另外，后期云端有开通搭载了AliosThings的其它设备的差分升级功能吗？

**Comment by xiaowenxia** [comment]
@kentzh 请问你是哪个NB模块呢？

**Comment by kentzh** [comment]
现在还没定，应该会用BC26或SIM7020，NB的带宽有限，希望能用到差分升级的功能

**Comment by xiaowenxia** [comment]
NB模块目前还不支持差分升级哈。

**Comment by kentzh** [comment]
依据https://help.aliyun.com/document_detail/58328.html?spm=5176.11485173.0.0.7e7859afV2DD7b的介绍，差分升级采用了切片的方式，这样可以减少更新数据量，节约时间和流量，应该和使用什么模块没有关系吧？
我们采用的是MCU+NB模块的方式，AliosThings跑在MCU上，NB只是通路啊

**Comment by kentzh** [comment]
在developerkit开发板上，使用WIFI已经做过OTA验证，整包OTA是可以的，现在想验证下差分OTA

**Comment by xiaowenxia** [comment]
> 依据[https://help.aliyun.com/document_detail/58328.html?spm=5176.11485173.0.0.7e7859afV2DD7b的介绍，差分升级采用了切片的方式，这样可以减少更新数据量，节约时间和流量，应该和使用什么模块没有关系吧？](https://help.aliyun.com/document_detail/58328.html?spm=5176.11485173.0.0.7e7859afV2DD7b%E7%9A%84%E4%BB%8B%E7%BB%8D%EF%BC%8C%E5%B7%AE%E5%88%86%E5%8D%87%E7%BA%A7%E9%87%87%E7%94%A8%E4%BA%86%E5%88%87%E7%89%87%E7%9A%84%E6%96%B9%E5%BC%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%8F%AF%E4%BB%A5%E5%87%8F%E5%B0%91%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE%E9%87%8F%EF%BC%8C%E8%8A%82%E7%BA%A6%E6%97%B6%E9%97%B4%E5%92%8C%E6%B5%81%E9%87%8F%EF%BC%8C%E5%BA%94%E8%AF%A5%E5%92%8C%E4%BD%BF%E7%94%A8%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9D%97%E6%B2%A1%E6%9C%89%E5%85%B3%E7%B3%BB%E5%90%A7%EF%BC%9F)
> 我们采用的是MCU+NB模块的方式，AliosThings跑在MCU上，NB只是通路啊

那你是用的什么MCU？目前差分升级支持的MCU有限，你也可以自己适配差分升级功能哈。

**Comment by taotaodong527** [comment]
Are there any strictions to support OTA Diff feature? Such as RAM and Flash requirements? Are there any specific docunments of how to porting OTA Diff feature
