### ISSUE TITLE
be push app.bin显示send timeout

### ISSUE THREAD

**Issue by Runingforever** [alibaba/AliOS-Things#936]
**Describe the bug**

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Runingforever** [comment]
> **Describe the bug**
在linux环境下运行sudo push app.bin
显示
> 文件长度 = 4776
send timeout, please reboot device!
>
环境
linux
参考
https://github.com/alibaba/AliOS-Things/wiki/boneengine_gpio_led_example

**Comment by xiaowenxia** [comment]
tinyengine 的问题需要问[这里](https://github.com/aliyun/TinyEngine)的。

**Comment by Runingforever** [comment]
404 not found？？？
