### ISSUE TITLE
Wiki 勘误

### ISSUE THREAD

**Issue by Tsai1005** [alibaba/AliOS-Things#942]
https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-FreeRTOS-Porting-Guide.zh

3.9 其他系统相关接口

3.9.1 整体API对比

aos_init	vTaskStartScheduler	内核相关模块初始化
aos_start		                                内核启动进入任务调度

对应关系有问题，aos_init 对应Null / aos_start 对应 vTaskStartScheduler;
解析也不准确，vTaskStartScheduler 包含内核模块初始化，并且开始调度

**Comment by zqyhcf** [comment]
确认之前表格格式问题，已经修改。aos_start也不是完全对应vTaskStartScheduler； 修改为：aos_init + aos_start  =>vTaskStartScheduler

**Comment by Tsai1005** [comment]
Nice job
