### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by xiaoyang432** [alibaba/AliOS-Things#944]
**Describe the bug**
请问为什么新的branch会多消耗70多KB的内存 ？

**environment**
1. branch(version): rel_2.1.0
2. Desktop OS(windows linux or macOS):windows
3. example: linkkitapp

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiaowenxia** [comment]
@xiaoyang432 应该不会消耗这么多内存的，有可能mcu的**栈**更改过，或者一些全局静态变量更改为了**malloc**这样的动态内存。

**Comment by xiaoyang432** [comment]
整个SDK都没有改动过，直接编译烧录就发现多耗了70多KB的内存，该问题可以直接复现的，我测试的MCU是esp32devkitc

**Comment by xiaoyang432** [comment]
@xiaowenxia 找到具体的问题点了，是AliOS-Things\platform\mcu\esp32\bsp\entry.c 中 hal_wifi_init();的问题，如果运行该函数就会消耗70多KB的内存，之前的版本没有这个问题的，请帮忙解决，谢谢！

**Comment by xiaowenxia** [comment]
@xiaoyang432 感谢你反馈的问题哈:smile:，你的统计方法能贴一下哈，我们内部排查下。

**Comment by xiaoyang432** [comment]
@xiaowenxia 对，主要是esp_wifi_init(&cfg)这个函数消耗了40多KB的内存，统计方法及窗口打印的数据如截图所示
![alios_esp32_wifi_init_bug](https://user-images.githubusercontent.com/23206168/55923670-fb90b700-5c38-11e9-8121-ea490d331e7b.jpg)
![alios_esp32_wifi_init_bug2](https://user-images.githubusercontent.com/23206168/55923677-01869800-5c39-11e9-8b74-e4b5e7d027df.jpg)
