### ISSUE TITLE
怎么新增一个类型单板

### ISSUE THREAD

**Issue by linrx1511** [alibaba/AliOS-Things#945]
看了wiki文档“Add a new board example”只是介绍了AOS-R-2.0.0及之前的版本的方法，感觉2.1.0变化比较大，请问R-2.1.0怎么增加一个新的类型开发板？怎么新建一个项目？好像文档介绍都不多。

**Comment by walker2048** [comment]
方式是一样的，只是增加了config.in文件配合kconfig使用罢了

**Comment by linrx1511** [comment]
> 方式是一样的，只是增加了config.in文件配合kconfig使用罢了

好的，谢谢，可 以了
