### ISSUE TITLE
ramfs_rename 函数的逻辑疑问

### ISSUE THREAD

**Issue by ifoxhz** [alibaba/AliOS-Things#949]
在函数ramfs_rename
    entry->fn = ramfs_mm_realloc(entry->fn, strlen(new));
    strcpy(entry->fn, new);
    if (entry->fn == NULL) {
        return RAMFS_ERR_MALLOC;
    }
如果fn会是NULL的话，strcpy应该已经crash了。
并且确实有可能为NULL, 如果输入0长度的new_path,就可能为NULL.

**Comment by jason-sophia** [comment]
非常感谢，确实有问题，我们会在下一个版本修复
