### ISSUE TITLE
mac下用VS Code编译helloworld@developerkit不过

### ISSUE THREAD

**Issue by jamesyao54** [alibaba/AliOS-Things#966]
> Executing task: aos make helloworld@developerkit <

aos-cube version: 0.3.3
Check if required tools for developerkit exist

Build command updated, please follow steps:
*********************************************************************
Step 1: config:
$ aos make helloworld@developerkit -c config
---> Or more config: $ aos make menuconfig

Step 2: build:
$ aos make    # VAR=value if needed

---> Or oneline command for config and build:
$ aos make helloworld@developerkit -c config && aos make
*********************************************************************
build/Makefile:119: *** Build Target Deprecated!.  Stop.
[AliOS-Things] ERROR: "/Users/yaofeng/Documents/Code/aliyun-iot/AliOS-Things/build/cmd/osx/make" returned error code 2.
[AliOS-Things] ERROR: Command "/Users/yaofeng/Documents/Code/aliyun-iot/AliOS-Things/build/cmd/osx/make HOST_OS=OSX TOOLS_ROOT=/Users/yaofeng/Documents/Code/aliyun-iot/AliOS-Things/build -e -f build/Makefile helloworld@developerkit" in "/Users/yaofeng/Documents/Code/aliyun-iot/AliOS-Things"

这个报错。求大神帮忙看下。

**Comment by walker2048** [comment]
请看输出说明，人家已经说了，编译命令已升级，具体步骤XXXX
