### ISSUE TITLE
ios端在notifyProvisionResult配网成功后获取不到token

### ISSUE THREAD

**Issue by letfly** [alibaba/AliOS-Things#968]
请问wifi设备端mqtt推送哪条topic，触发ios端notifyProvisionResult配网成功？在阿里后台日志处已看到mqtt推送带有token的topic，但ios端获取不到token

**Comment by xiaowenxia** [comment]
@letfly 你是自己开发的app嘛？

**Comment by letfly** [comment]
是的，
ios端
![image](https://user-images.githubusercontent.com/6472609/57277439-bdbb6d00-70d6-11e9-95e4-55a8943da6d7.png)
安卓端
![image](https://user-images.githubusercontent.com/6472609/57277555-f78c7380-70d6-11e9-8635-fb456fb30ed2.png)
安卓端getToken有60*1000ms时间判断，但ios端getToken没有时间判断

**Comment by letfly** [comment]
ios端的getDeviceToken如何使用，只调用一次，还是需要做个while 60*1000ms时间判断？但sdk应该处理的吧

**Comment by letfly** [comment]
@xiaowenxia

**Comment by xiaowenxia** [comment]
@letfly 这个问题我们解决不了哈，需要[提交工单](https://selfservice.console.aliyun.com/ticket/category/link_living)问一下。

**Comment by letfly** [comment]
@xiaowenxia  OK，已提工单
