### ISSUE TITLE
When shell by 'aos make linkkitapp@mk3060 -c config && aos make', there is some error

### ISSUE THREAD

**Issue by letfly** [alibaba/AliOS-Things#979]
![image](https://user-images.githubusercontent.com/6472609/57432782-5aae0f80-7269-11e9-9bf8-ad531efae619.png)
need fix the makefile, or move the middleware/uagent/ota/2nd_boot/rec_pub.h?

**Comment by xiaowenxia** [comment]
@letfly  `aos make clean` 再试试？ 看看你当前代码是否有改动？

**Comment by letfly** [comment]
@xiaowenxia 赞，可以了
