### ISSUE TITLE
OTA升级容易失败

### ISSUE THREAD

**Issue by xiaoyang432** [alibaba/AliOS-Things#981]
**Describe the bug**
OTA升级的时候很容易失败，失败原因提示“ota verify hash failed”，然后再也不能升级成功了，请帮忙解决，谢谢！

**environment**
1. branch(version): 
2. Desktop OS(windows linux or macOS):
3. example: 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by MinjunHuang** [comment]
我在ESP32上也是这个问题，@xiaoyang432 ，你有新的进展吗？
