### ISSUE TITLE
Ubuntu16.04不能编译helloworld

### ISSUE THREAD

**Issue by smalleha** [alibaba/AliOS-Things#995]
aos-cube version: 0.3.3
Check if required tools for starterkit exist

Config completed, please run build directly: $ aos make

build/Makefile:129: *** Build Target Deprecated!。 停止。
[AliOS-Things] ERROR: "/home/zsq/AliOS-Things/build/cmd/linux64/make" returned error code 2.
[AliOS-Things] ERROR: Command "/home/zsq/AliOS-Things/build/cmd/linux64/make HOST_OS=Linux64 TOOLS_ROOT=/home/zsq/AliOS-Things/build -e -f build/Makefile helloworld@starterkit" in "/home/zsq/AliOS-Things"
---
终端进程命令“/bin/bash  -c 'aos make helloworld@starterkit'”无法启动 (退出代码: 2)

**Comment by xiaowenxia** [comment]
2.1的版本，编译指令更改为了：
```sh
# 配置
aos make helloworld@starterkit -c config

# 编译
aos make
```
