### ISSUE TITLE
符号或者变量未定义，跳转至错误的同名头文件

### ISSUE THREAD

**Issue by athmoon** [alibaba/AliOS-Things#997]
**符号或者变量未定义**

**Win10  VScode  aos-cube version: 0.3.3 **
1. branch(version):  
2. Desktop OS(windows linux or macOS):Win10
3. example: 

**Expected behavior**
1，符号或者变量未定义
2，

**Screenshots**

![vscodeUndefine](https://user-images.githubusercontent.com/870776/59827211-a8d72800-936a-11e9-9627-b4c621301782.png)

 
![vscodeF12](https://user-images.githubusercontent.com/870776/59828116-dfae3d80-936c-11e9-8e39-82c28fd5f7be.png)

**Additional context**

**Comment by athmoon** [comment]
通过明确指定路径，将其他同名include路径排除掉应该就可以了
ctrl=Shift+P 
C/C++: Edit configurations (UI)
Include path 

${workspaceFolder}/platform/mcu/stm32f1xx/drivers/CMSIS/Device/ST/STM32F1xx/Include
${workspaceFolder}/3rdparty/**
${workspaceFolder}/app/example/blink/**
${workspaceFolder}/board/stm32f103ve-wsc/**
${workspaceFolder}/platform/mcu/stm32f1xx/drivers/STM32F1xx_HAL_Driver/Inc/**
${workspaceFolder}/drivers/**
${workspaceFolder}/include/**
${workspaceFolder}/kernel/**
${workspaceFolder}/middleware/**
${workspaceFolder}/network/**
${workspaceFolder}/osal/**
${workspaceFolder}/platform/mcu/stm32f1xx/**

**Comment by xiaowenxia** [comment]
👍 赞！！

**Comment by athmoon** [comment]
ctrl=Shift+P
C/C++: Edit configurations (UI)
Defines 根据芯片类型定义例如：
![ref](https://user-images.githubusercontent.com/870776/59832064-a201e280-9375-11e9-8fb9-1cbe91c0cb4b.png)


STM32F103xE

**Comment by athmoon** [comment]
aos 如果可以自动配置 include和define就好了！
