### ISSUE TITLE
alios things 1.3.4版本编译不成功

### ISSUE THREAD

**Issue by Ellsion** [alibaba/AliOS-Things#998]
最近在做阿里飞燕的项目，使用庆科的EMW3080模块，对应的alios things版本是1.3.4，编译器使用
alios-studio,win7系统。
但是发现怎么都编译不成功，试着编译了好几个demo都失败。请问这种情况怎么解决。

以下是报错情况：

C:\AliOS-Things-1.3.4>aos make helloworld@mk3080
aos-cube version: 0.2.53
Check if required tools for mk3080 exist
...(省略中间过程)
...
build/aos_target_config.mk:320: *** Unknown component: platform/mcu/rtl8710bn - directory or makefile for component not found.
Ensure the platform/mcu/rtl8710bn directory contains rtl8710bn.mk.  Stop.
make.exe: *** No rule to make target 'out/helloworld@mk3080/config.mk', needed by 'main_app'.  Stop.
[AliOS-Things] ERROR: "C" returned error code 2.
[AliOS-Things] ERROR: Command "C : / A l i O S - T h i n g s - 1 . 3 . 4 / b u i l d \ c m d / w i n 3 2 / m a k e . e x e   H
O S T _ O S = W i n 3 2   T O O L S _ R O O T = C : / A l i O S - T h i n g s - 1 . 3 . 4 / b u i l d   - e   - f   b u i l d / M a k e f i l e   h e l l o w o r l d @ m k 3 0 8 0" in "C:\AliOS-Things-1.3.4"

**Comment by xiaowenxia** [comment]
> build/aos_target_config.mk:320: *** Unknown component: platform/mcu/rtl8710bn - directory or makefile for component not found.

看起来少了东西，你下载的代码是否是完整的呢？
