### ISSUE TITLE
alios things 安装环境后编译出错

### ISSUE THREAD

**Issue by Ellsion** [alibaba/AliOS-Things#999]
alios-studio python2和git都安装好后，编译出现以下错误
PS C:\AliOS-Things-1.3.4> aos make helloworld@mk3080
Could not import runpy module
ImportError: No module named 'runpy'
PS C:\AliOS-Things-1.3.4> ImportError: No module named 'runpy'

请问怎么解决？

**Comment by xiaowenxia** [comment]
应该是aos-cube没有安装对，重装python和aos-cube试试.

**Comment by Ellsion** [comment]
重装没用，我换了一台电脑OK了
